### ISSUE TITLE
(UPDATED!!!) STILL looking for group members for a ChIP-seq analysis centered project

### ISSUE THREAD

**Issue by wongoli** [STAT540-UBC/Discussion#10]
Hello everyone! 

My name is Olivia and I spoke in class today about my idea of a project. We are currently still looking for 2 additional members! 

Brief description of our concept of the group project follows:

We will be looking at mutations of proteins that regulate long non-coding RNA and how such mutations affects gene expression in budding yeast. Analysis will be performed for RNA-seq, ChIP-seq, and expression microarray data. 

To those who are still interested in joining this group, please comment below if you have not already done so. 

Thanks!

**Comment by dchiu911** [comment]
This is Derek! I'm in MSc. Biostatistics and I would like to join your group!

**Comment by basienka** [comment]
Hey there! My name's Basia, I'm one of the statistics grad students and looking for a group! Let me know if you're still looking for another member :)

**Comment by gcohenfr** [comment]
Hi Basia, I saw you were trying to join the Asthma group as well. Given that Derek is in this group, I prefer if you join the other group that needs a student from Stat.

**Comment by AlisonMcAfee** [comment]
We should probably close this!
