### ISSUE TITLE
Looking for STAT or BIOF expertise - Epigenetics

### ISSUE THREAD

**Issue by jamesmelanson** [STAT540-UBC/Discussion#100]
Hi everybody!

We're a group of five biologists with experience in epigenetics, developmental biology, and biochemistry. Looking for somebody with expertise in statistics, or computer science!

Our teammates:
James Melanson | Experimental Medicine | @jamesmelanson
Kate Watt | Reproductive and Developmental Sciences | @hannibelle
Giulia Del Gobbo | Medical Genetics | @gdelgobbo
Luke Gooding | Reproductive and Developmental Sciences | @ldgooding
Samuel Schafer | Reproductive and Developmental Sciences | @schafers

Currently there's a bunch of ideas being thrown around, as we have a couple of different data sets involving 450K methylation data.

Sperm 450K methylation (Themes: Infertility)
Placenta 450K methylation (Themes: Pregnancy complications including intrauterine growth restriction; neural tube defects)
- James; Kate, Giulia, Lucas, Samuel

**Comment by santina** [comment]
Hello, your [project repo](https://github.com/STAT540-UBC/team_IUGRoup_DNAm) has been created.  Looks like an interesting project! @halldorbjarni @gdelgobbo and @ldgooding make sure to check your email for an invitation to join the organization so you can edit the repo.

**Comment by halldorbjarni** [comment]
I'm not in this group! :) @santina

**Comment by santina** [comment]
sorry wrong tag. Thanks! @jamesmelanson

**Comment by santina** [comment]
Sara and I are your assigned advisors. Looking forward to working with you!

**Comment by hannibelle** [comment]
Hello Santina,

Thanks for letting us know! Happy we'll be getting to work with you :)

Regards,

Kate
