### ISSUE TITLE
Group: The epigenetic determinants of gender 

### ISSUE THREAD

**Issue by eclaks** [STAT540-UBC/Discussion#101]
We've formed a group and are planning on doing analysis on this paper:
"Brain feminization requires active repression of masculinization via DNA methylation"
http://www.nature.com.ezproxy.library.ubc.ca/neuro/journal/v18/n5/full/nn.3988.html

as per Tony Hui's idea:
https://github.com/STAT540-UBC/Discussion/issues/97

| GitHub ID | Name (Department) |
| --- | --- |
| @RashedHUBC | Rashed Hoque (Statistics) |
| @emminic93 | Emma Titmuss (Genome Science and Tech) |
| @eclaks | Emma Laks (Genome Science and Tech) |
| @hui-tony-zk | Tony Hui (Genome Science and Tech - Bioinformatics) |
| @david-rattray | David Rattray (Biochemistry) |

[proposal to follow](https://drive.google.com/folderview?id=0B3maFFJDc03uZ2tPaTVUTE5uTzA&usp=sharing_eid&ts=569fdf5f&usp)

@santina 
@marjanfarahbod 
@saramostafavi

**Comment by saramostafavi** [comment]
Great, very interesting! Good luck and will get back to you when we see the proposal +1:

**Comment by eclaks** [comment]
Thanks Sara. For the proposal, are you concerned about style? Can we structure it as an outline page of points or do you prefer it in a paragraph form?

**Comment by santina** [comment]
It looks like @eclaks  and @david-rattray haven't accepted invitation to join STAT540 organization yet. 

I made a [repo](https://github.com/STAT540-UBC/team_treed_rats-DNA-methylation) for you guys. You two should have gotten emails from Github and once you join you'll be able to edit it. Let me know if you can't edit it or some other problem.

**Comment by santina** [comment]
Hello again.  Sara and I are your assigned advisors. We look forward to working with you and your project!
