### ISSUE TITLE
Team Formed!

### ISSUE THREAD

**Issue by lulock** [STAT540-UBC/Discussion#102]
Our team members:
- Angela Mo | Pathology and Laboratory Medicine | @angelamo
-  Genevieve Rocheleau | Experimental Medicine | @genrocheleau
-  Louie Dinh  | Computer Science | @louiedinh
-  Derek Cho | Statistics | @derekcho
- Leila Methnani | Computer Science | @lulock

@marjanfarahbod 
@santina 
@saramostafavi

**Comment by santina** [comment]
[Your repo](https://github.com/STAT540-UBC/team_GLLAD_HIV) is created!  @louiedinh and @angelamo you aren't in the organization yet so make sure to check your email and accept the invitation.

**Comment by santina** [comment]
Hello again! Paul and I are your assigned advisors. Looking forward to working with you and your project!
