### ISSUE TITLE
Project Group Composition: Yeastie Grapes (still seeking members)

### ISSUE THREAD

**Issue by fergusonandrew** [STAT540-UBC/Discussion#103]
**Project Group Composition**

Our current team:

Jay Martiniuk | LFS WRC\* (Food Science) | @jmartiniuk
Nicholas Dimopoulos | LFS WRC\* (Plant Biology) | @ndimopoulos
Andrew Ferguson | LFS WRC\* (Food Science) | @fergusonandrew

We would enthusiastically welcome other members with a statistics/bioinformatics/computer science background to join our project.  If you enjoy _wine_, this is the group for you. 

*Faculty of Land and Food Systems, Wine Research Centre

---

**Our project:**

We have several **RNAseq** datasets generated from grape berry samples. The datasets were originally compiled to look at **grape gene expression** under various conditions, but they also contain a lot of information about the **yeast and fungal communities** living on the surface of the berries. These yeast and fungi can have both beneficial and detrimental impacts on grape and wine quality (e.g. presence of pathogens, spoilage or helpful fermenting yeast).

Some ideas include profiling yeast and fungal populations/gene expression at:

various ripening stages
different states of grapevine water deficit
different stages of grape berry firmness and other possibilities

Then correlating this data with microbial communities, and further looking at the relative expression of microbial genes in relation to genes expressed in the grapes. 

@santina 
@marjanfarahbod 
@saramostafavi

**Comment by santina** [comment]
Woah this sounds cool :smile_cat: ! I'm excited to see what will turn out from this project. :grapes:

**Comment by saramostafavi** [comment]
Sounds very cool, neat idea/data, and would be great opportunity for a CS/Stat students to build expertise in "statistical data integration" in genomics.

**Comment by santina** [comment]
Hey your repo is made! 

@ndimopoulos and @jmartiniuk looks like you're not in the organization yet, so check your email for invitation because I made a team for you guys. Once joined, you should be able to write to [your project repo](https://github.com/STAT540-UBC/team_META-VEG_wine). Close the issue if there aren't any issue with accessing the repo.

**Comment by santina** [comment]
Hello again! Paul and I are your assigned advisors. Looking forward to working with you!
