### ISSUE TITLE
Team formed

### ISSUE THREAD

**Issue by halldorbjarni** [STAT540-UBC/Discussion#104]
Our team members:

Halldor Bjarni Thorhallsson | Computer Science | @halldorbjarni
Chris May | Interdisciplinary Oncology | @cgmay
Ian Garber | Experimental Medicine | @igarber
Samuel Hinshaw | Bioinformatics | @samhinshaw
Farnush Farhadi | Bioinformatics | @farnushfarhadi

@santina 
@marjanfarahbod 
@saramostafavi

**Comment by santina** [comment]
Hello, here's your [project repo](https://github.com/STAT540-UBC/team_FISCH_MassSpec)!  @cgmay and @farnushfarhadi, make sure to check your email for invitation to this organization so you can edit the repo like the rest of the team :smiley:

**Comment by marjanfarahbod** [comment]
Dear all FISCH team members, 
@halldorbjarni
@cgmay
@igarber
@samhinshaw
@farnushfarhadi

Paul and I are your assigned instructors for the project. I have already added our names as the instructors to your README.md file in your project repository. I guess this would be my first and last commit to your project README.md file! Don't forget to pull it first...

You can post your project related issues in your project repository issues.

**Note:** please respond to your github invitations. 

Cheers and good luck!
