### ISSUE TITLE
Project group formed

### ISSUE THREAD

**Issue by Irrationone** [STAT540-UBC/Discussion#105]
Wai Ho Choy | Experimental Medicine | @hochoy
Xiaoting Ding | Statistics | @IreneDing
Parker Jobin | Biochemistry/Molecular Biology | @pjobin10
Xuan Li | Statistics | @AnnieXuanLi
Shumin Wang | Botany | @shumin11
Allen Zhang | Bioinformatics | @Irrationone

We will be analyzing the composition of the immune microenvironment in high-grade serous ovarian cancer from the perspective of TCR-seq, BCR-seq, array-based gene expression, and whole genome sequence data to determine differences in spatially separated sites.

**Comment by santina** [comment]
Hello, @hochoy  @IreneDing @pjobin10  @AnnieXuanLi  @shumin11  and @Irrationone, 

Thanks for making this issue. Don't forget to update it when you guys have an idea of your project plan (one sentence describing the project is sufficient at this point). 

Seeing that you have 6 people while another group (issue #103) working on the wine project only has 3,  perhaps one of you could consider switching over to them, maybe someone in stats or bioinformatics?  

In your proposal and individual reports (see [here](http://stat540-ubc.github.io/subpages/assignments.html#final-deliverables)) you'll talk about how each of you will contribute to the project, so you want to make sure everyone will have enough work to talk about. You can do that by either adjusting the size of the group, or the complexity of the project.

**Comment by saramostafavi** [comment]
Dear group members @hochoy @IreneDing @pjobin10 @AnnieXuanLi @shumin11 and @Irrationone, I strongly recommend that one of you joins the group with 3 students. This will help balance the work load and will allow each of you to uniquely lead a coherent part of the project.  If you have questions, I and the TAs are happy to discuss this with you on Wednesday after the class or during the seminar. We suggest you make this move soon, as the proposals are due on Friday.

**Comment by Irrationone** [comment]
We only have 5 students planned to lead parts of the project -- @shumin11 is auditing the course and will be playing more of an observer role within our group. 
The nature of our project idea we have entails analysis of multiple types of high-throughput data, resulting in our decision to have 5 main group members. Is this still a problem? If so, it's something our group can discuss when we meet on Wednesday. Thanks!
@saramostafavi @santina

**Comment by saramostafavi** [comment]
Ok, please discuss among yourself, and we can talk it over together at the seminar. It would be very helpful to the class overall if one of the statistics students could move to the other group with 3 members.

**Comment by hochoy** [comment]
Hi all, Just wanted to add that I am also an audit student (pending a signature from my advisor). I am not a stats student though.

**Comment by santina** [comment]
Hello, I made you guys a [project repo](https://github.com/STAT540-UBC/team_PHASAX_ovarian-cancer)! Very detailed project proposal in #109 , so you probably won't have much work to do for the final proposal. 

@IreneDing, @pjobin10, @shumin11, it looks like you haven't joined the STAT540 organization, so make sure to check your email for that invitation so you can start editing this project repo.

**Comment by IreneDing** [comment]
@santina 

I just joined the STAT 540 organization, can you please invite me to the repo? Thanks

**Comment by santina** [comment]
@IreneDing  Mmm I think you already have access to the repo. Maybe try editing it?

**Comment by IreneDing** [comment]
@santina I get a 404 no access when I try to click the hyperlink to the project repo. I can't see it from the STAT540 ubc organization either

**Comment by santina** [comment]
Ohh, you didn't accept the invitation to join the team. In the team view it still shows that it's pending invitation. Check your email to see if you have an email sent from Github about team PHASAX?

**Comment by IreneDing** [comment]
@santina  I just joined. Thank you

**Comment by santina** [comment]
@IreneDing   Glad it works out ! :smiley:

**Comment by marjanfarahbod** [comment]
Dear all PHASAX team members, 
@hochoy
@IreneDing
@pjobin10
@AnnieXuanLi
@shumin11
@Irrationone

Paul and I are your assigned instructors for the project. I have already added our names as the instructors to your README.md file in your project repository. I guess this would be my first and last commit to your project README.md file! Don't forget to pull it first...

You can post your project related issues in your project repository issues. 

@pjobin10 **Please accept your github invitation**

Cheers and good luck!
