### ISSUE TITLE
Team information

### ISSUE THREAD

**Issue by michekwon** [STAT540-UBC/Discussion#106]
Our teammates: 

Michelle Kwon | Cell and Physiological Sciences | @michekwon
Min Feng | Genome Sciences and Technology | @min110
Gal Av-Gay | Statistics | @galotalp
Mitchell Braam | Genome Sciences and Technology | @mibraam 
Nelly Saber | Genome Sciences and Technology | @nellysaber

Our project options: 

1) Investigating the mechanism of leptin therapy in type 1 diabetes
2) Investigating the changes in proteome with Mycobacterium tuberculosis infection

**Comment by santina** [comment]
Hello, I made you guys a [project repo](https://github.com/STAT540-UBC/team_Lepin_diabete).  You didn't give me a teamname in the proposal so I just named your team "Lepin" for now, but let me know if you come up with one and want me to change it :+1: 

@min110 and @mibraam looks like you haven't accepted the invitation to join the organization, so make sure to check your email for that invitation so you can start putting your work in this repo. :smile:

**Comment by min110** [comment]
Hey, @santina I did not get the invitation via email , would you please re-send it to me ? Thanks !

**Comment by santina** [comment]
@min110  I resent it. Let me know if it works out for you.

**Comment by min110** [comment]
Not yet, even not in the JUNK , Santina , is it my gmail (feng.min110@gmail.com ) by default ?

**Comment by santina** [comment]
@min110  It should be sent to the email that you signed up for Github with or whatever the primary one is. So if you go to your settings(by clicking on your icon on the right hand top corner) > email, then you'll see what's the primary email.

**Comment by min110** [comment]
Oh , You are right ! It is my fault that the Primary email by default is one I have not used for quite a while and cant remember the password .. 
Would you mind resend the invitation as I have already changed the primary email address ? 
Many Thanks !

**Comment by santina** [comment]
@min110  Sure. I just resent it. Hope it works out this time :)

**Comment by min110** [comment]
Yes! Thanks Santina;) It works !
