### ISSUE TITLE
Team JaWSPR Formed

### ISSUE THREAD

**Issue by shamsbhuiyan** [STAT540-UBC/Discussion#107]
Our team Members:

Jasleen Grewal | Bioinformatics | @jasgrewal
Wendy Zhang | Experimental Medicine |@w-zhang
Shamsuddin A. Bhuiyan | Bioinformatics | @shamsbhuiyan
Phillip Richmond | Bioinformatics | @Phillip-a-Richmond
Rachelle Farkas | Bioinformatics | @rafarkas
### Team JaWSPR: Expression Analysis of an Alcohol Tolerance Mouse Model

 **Ja**sleen Grewal, **W**endy Zhang, **S**hams Bhuiyan, **P**hillip Richmond, **R**achelle Farkas
January 29th, 2016

In 1981, McClearn greatly impacted the alcohol sensitivity field when he introduced the world to the Inbred Long Sleep (ILS) and Inbred Short Sleep (ISS) mice [MCCLEARN 1981]. The strains were selected for and named by their variable response to a high dose of alcohol, which is measured by a phenomenon known as the Loss of Righting Reflex (LORR).  After roughly 30 generations of selection for this trait, the resultant lines were inbred through brother sister mating to produce an isogenic line. Initial hypotheses regarding metabolic rate were investigated, but were disproven and the sensitivity was linked to differences in the brain [Kakihana 1966].  The ILS and ISS mice were also crossed and inbred to produce the recombinant inbred (RI) panel named LXS—which spans a sleep time spectrum—allowing for mapping of traits in a quantitative trait loci (QTL) manner [Williams 2004].  Presently, we have the unprecedented ability to investigate the gene expression profiles of these mice using RNA-sequencing, which is exactly what Richard Radcliffe at the University of Colorado School of Pharmacology decided to pursue.  Dr. Radcliffe has been studying these mice for the past 15 years, and designed an experiment that includes RNA-sequencing of the brains of the ILS, ISS, and 40 individual LXS strains under both saline and ethanol treatment.  The data generated in the course of this experiment has resulted in a total of 252 RNA-seq libraries from mice whole-brain samples, covering the 2 conditions (saline control and ethanol treatment), with 3 biological replicates for each condition, and a few sets of technical replicates. A bioinformatics based analysis of this dataset will entail identification of significant expression differences between the ILS and ISS cohorts, using the saline treated strains as respective controls for normalizing against batch and technical effects. Additionally, we will look for gene expression trends and patterns in the LXS RI panel.  Since the panel represents a spectrum of phenotypes, we may also expect a subset of genes to be expressed in a spectral manner—modulating across genotypes.  The main intent of this analysis is to identify expression signatures that distinguish the ethanol sensitivity phenotype. The resultant signatures that we observe can then be used by Dr. Radcliffe’s lab in downstream expression-QTL (eQTL) analyses, linking genotypes to expression patterns in an effort to further decode the molecular mechanisms behind sensitivity to alcohol. 

_References_
Kakihana R, Brown DR, McClearn GE, Tabershaw IR. Brain sensitivity to alcohol in inbred mouse strains. Science 154, 1574-1575 (1966) 

McClearn GE. Genetic differences in the effect of alcohol upon behaviour of mice. In Proceedings of the third international conference on alcohol and road traffic, J. Havard, ed. London: British Medical Association, pp 153-155 (1962) 

McClearn GE, Kakihana R. Selective breeding for ethanol sensitivity: Short-Sleep and Long-Sleep mice. In Development of Animal Models as Pharmacogenetic Tools, M.G. E., R.A. Deitrich, V.G. Erwin, eds. Rockville, MD: National Institute on Alcohol Abuse and Alcoholism, pp 147-159 (1981) 

Williams RW, Bennett B, Lu L, Gu J, DeFries JC, Carosone-Link PJ, Rikke BA, Belknap JK, Johnson TE. Genetic structure of the LXS panel of recombinant inbred mouse strains: a powerful resource for complex trait analysis. Mamm Genome 15,

**Comment by santina** [comment]
Your [project repo](https://github.com/STAT540-UBC/team_JaWSPR_drunk-mice) has been made. @shamsbhuiyan @w-zhang @Phillip-a-Richmond  @rafarkas be sure to join the organiztion (check your email).   Let me know if there's any issue.

**Comment by saramostafavi** [comment]
OK, I took the group "JaWSPR". Thanks everyone for being so flexible!

On Fri, Jan 29, 2016 at 1:23 PM, Santina Lin <notifications@github.com>
wrote:

> Your project repo <https://github.com/STAT540-UBC/team_JaWSPR_drunk-mice>
> has been made. @shamsbhuiyan <https://github.com/shamsbhuiyan> @w-zhang
> <https://github.com/w-zhang> @Phillip-a-Richmond
> <https://github.com/Phillip-a-Richmond> @rafarkas
> <https://github.com/rafarkas> be sure to join the organiztion (check your
> email). Let me know if there's any issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAT540-UBC/Discussion/issues/107#issuecomment-176974976>
> .
>



-- 

Sara Mostafavi
Assistant Professor, Dept. of Statistics, and Dept. Medical Genetics,
University of British Columbia
Scientist, Centre for Molecular Medicine and Therapeutics
Vancouver BC
Canada

**Comment by shamsbhuiyan** [comment]
Hey @santina - I can't seem to join our project repo?

**Comment by santina** [comment]
@shamsbhuiyan  because you haven't accepted the invitation yet.  Check your email !

**Comment by santina** [comment]
Only Jasleen is in it right now. Because when I invited you guys to the team, you weren't members of the organization yet. 
![screen shot 2016-02-02 at 10 01 34 am](https://cloud.githubusercontent.com/assets/1039839/12759040/e99b7ebc-c993-11e5-8bf3-4c0c241671ed.png)

If you don't know where the email got sent, go to the upper right hand corner, click on your avator to go to "settings" > email to see your primary email.

**Comment by shamsbhuiyan** [comment]
Oh I got it! Accepted. Thanks

**Comment by marjanfarahbod** [comment]
Dear all JaWSPR team members, 
@jasgrewal
@w-zhang
@shamsbhuiyan
@Phillip-a-Richmond
@rafarkas

Sara and I are your assigned instructors for the project. I have already added our names as the instructors to your README.md file in your project repository. I guess this would be my first and last commit to your project README.md file! Don't forget to pull it first...

You can post your project related issues in your project repository issues.

Cheers and good luck!
