### ISSUE TITLE
Team formed

### ISSUE THREAD

**Issue by joeho604** [STAT540-UBC/Discussion#108]
Our team members:

Dan Seale | GSAT  | @danseale
Kevin Ao | GSAT  | @kao7
Amalia Rose | Biochemistry |@amaliar
Joe Ho | Microbiology | @joeho604

Project ideas: (more to come...)

@santina 
@marjanfarahbod 
@saramostafavi

**Comment by santina** [comment]
Hello! I made you guys a team and here's your [group project repo](https://github.com/STAT540-UBC/team_GutCHECK_microbiome). @danseale, @kao7, and @amaliar, make sure you check your email for an invitation to join the STAT540 organization in order to be able to write to this repo.

**Comment by marjanfarahbod** [comment]
Dear GutCHECK team members, 
@danseale
@kao7
@amaliar
@joeho604

Sara and I are your assigned instructors for the project. I have already added our names as the instructors to your README.md file in your project repository. I guess this would be my first and last commit to your project README.md file! Don't forget to pull it first...

You can post your project related issues in your project repository issues.

**Notice:** You should all respond to your invitations for joining the team/organizationSTAT540 before you can contribute to your project repository. 

Cheers and good luck!
