### ISSUE TITLE
Displaying plots in R markdown files on Github

### ISSUE THREAD

**Issue by tshalev** [STAT540-UBC/Discussion#11]
Has anyone figured out how to make plots appear on Github when uploading R markdown files? It seems to run fine when I knit it in R studio but when I push the file to Github the plots disappear.

**Comment by wdurnoUBC** [comment]
You need to push Markdown (md) files for that. The Rmd files describe R code that has yet to run.

**Comment by tshalev** [comment]
OK. Pushing the markdown file puts a link to the images rather than running the plot function and loading the images themselves; the link is to the folder on my computer so it is broken and doesn't lead anywhere. Is there a way of converting the rmd file to md? I was just telling rstudio to retain the md files when knitting the rmd.

https://github.com/STAT540-UBC/zz_shalev-tal_STAT540_2015/blob/master/Seminar_02_assignment_markdown_Tal.md

**Comment by jennybc** [comment]
If you look at your raw Markdown you'll see figures being embedded via links like so:

```sh
![plot of chunk unnamed-chunk-2](./Seminar_02_assignment_markdown_Tal_files/figure-html/unnamed-chunk-2.png)
```

But if those figures are not present in your repo __on GitHub__ they cannot be displayed.

You need to commit all the figures created locally and placed in the subdirectory `Seminar_02_assignment_markdown_Tal_files/figure-html/` at the same time you're committing the Markdown files. If you are using, for example, RStudio as your Git client, they should be there available for "clicking" when you are selecting files to commit. Click on them. Then push to GitHub. Now the images will be where they need to be a display properly on GitHub.

**Comment by tshalev** [comment]
Thanks, that seems to work.

**Comment by swils6** [comment]
I can only get my images to appear as a separate file and not integrated into my markdown file. I think my problem is that I don't have an MD file. When I chose for rMarkdown to keep source file, and knit my script a get an error like this:

Error: pandoc document conversion failed with error 97
In addition: Warning message:
running command '"C:/Users/Samantha/Desktop/RStudio/bin/pandoc/pandoc" CoinFlips_Good.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output CoinFlips_Good.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\Samantha\Documents\R\win-library\3.1\rmarkdown\rmd\h\default.html" --variable "theme:bootstrap" --include-in-header "C:\Users\Samantha\AppData\Local\Temp\Rtmp2ZH85i\rmarkdown-str170436312e7.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=C:\Users\Samantha\Documents\R\win-library\3.1\rmarkdown\rmd\h\highlight"' had status 97 


It then proceeds to delete all my work from the folder. Any suggestions on how to fix this?

**Comment by jennybc** [comment]
Follow the directions here to keep the intermediate markdown:

http://stat545-ubc.github.io/block007_first-use-rmarkdown.html

Or are you already doing exactly that?

**Comment by jennybc** [comment]
Also, make sure you are using very latest RStudio, `knitr`,and `rmarkdown`.

**Comment by swils6** [comment]
I have been following those directions from the stat 545 site, and just ran through them again to make sure. I have the figures in a "_files" folder, the html document, and the rmd file. But when I chose to  keep source markdown file it continues to throw that error. When the document is knitting I can see a md file be created and then it is deleted.

**Comment by jennybc** [comment]
I've looked at your Rmd file on GitHub. Not sure if that's close to what you're working with locally? But it has lots of extra / conflicting YAML front matter, for example. If you still have all of that strange YAML, that could be the root problem here.

When you say

>  I have the figures in a "_files" folder

you aren't doing any thing *actively* about that right? If you just knit a Rmd that makes figures, this folder will get created automagically for you and the figures will be put in it.

**Comment by swils6** [comment]
Thanks so much! I just figured it out!

**Comment by paullovachy** [comment]
Not able to view graphs in my markdown files still. Have the images saved here:
https://github.com/paullovachy/Predictive-Modeling-R/tree/master/Time%20Series/Time%20Series%20Graphs

But cant get them to populate where they should in my markdown file here:
https://github.com/paullovachy/Predictive-Modeling-R/blob/master/Time%20Series/ARIMA_Forecasting.md

Any advice is welcome!

**Comment by singha53** [comment]
@paullovachy do you have an associated Rmd file?

**Comment by paullovachy** [comment]
Hi, yes it is located here:
https://github.com/paullovachy/Predictive-Modeling-R/blob/master/Time%20Series/ARIMA%20Forecasting.Rmd

**Comment by singha53** [comment]
@paullovachy change your output to 
output: github_document

**Comment by paullovachy** [comment]
@singha53  Hmm still not displaying the graphs. Is it because I'm not specifying in the Rmd or md files where on github the graphs are located? Thank you for the help as well!

**Comment by jennybc** [comment]
Not sure why I'm watching this repo, but while I'm here, I highly recommend building paths with the package here:

https://github.com/jennybc/here_here#readme

I didn't write it, but it's super handy.

**Comment by paullovachy** [comment]
@jennybc Thank you, this is very helpful!

**Comment by gndoshi** [comment]
Hi, 
I'm unable to view my graphs and images as well. Well, to be honest, this is how I did things, 
1) created a repo
2) uploaded my RMD doc
3) uploaded my dataset

Now, I'm confused what to do or rather how to execute my code. Please, I've been trying since hours, I would appreciate anyone's advice/help/guidance! Thank you!!

**Comment by gndoshi** [comment]
@jennybc In all honesty, I don't even understand what the 'here' package is doing. It's setting a working directory?

**Comment by jennybc** [comment]
Maybe this step-by-step tutorial will help:

http://happygitwithr.com/rmd-test-drive.html

**Comment by ivieira000** [comment]
Hi, I'm having the same issue that I'm not being able to display the graphs on my Md file on Github. I have all pics in the repository together with the Md and Rmd files, I just can't get it to work. https://github.com/ivieira000/HW4

Thanks!!
