### ISSUE TITLE
Paper review - 01

### ISSUE THREAD

**Issue by marjanfarahbod** [STAT540-UBC/Discussion#110]
Hi guys, it is time for paper review exercise! 
Please go ahead and put the name of your paper, linked to the journal or pubmed, with year it was published, like this:

**[Loss of motoneuron-specific microRNA-218 causes systemic neuromuscular failure](http://classic.sciencemag.org/content/350/6267/1525.long)**  - December 2015

You can find the instructions for this assignment in [here](http://stat540-ubc.github.io/subpages/assignments.html#paper-review)

 [This is the guideline](http://stat540-ubc.github.io/homework/paper_critique/PRguideline.html)

[Paper review example 01](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/paper_critique/paperReviewMarjan.md) Marjan 
[Paper review example 02](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/paper_critique/paperReviewSantina.md) Santina

**Comment by hannibelle** [comment]
[Hypomethylation within gene promoter regions and type 1 diabetes in discordant monozygotic twins](http://www.ncbi.nlm.nih.gov/pubmed/26782299) - January 2016

**Comment by fergusonandrew** [comment]
[Different mechanisms of resistance modulate sulfite tolerance in wine yeasts](http://link.springer.com/article/10.1007%2Fs00253-015-7169-x) - January 2016

**Comment by cgmay** [comment]
[Profiling tissue-resident T cell repertoires by RNA sequencing](http://www.ncbi.nlm.nih.gov/pubmed/26620832) - November 2015

**Comment by samhinshaw** [comment]
[Phylogeographical analysis of the dominant multidrug-resistant H58 clade of Salmonella Typhi identifies inter- and intracontinental transmission events](http://www.dx.doi.org/10.1038/ng.3281) - May 2015

**Comment by mibraam** [comment]
Clonal Analysis via Barcoding Reveals Diverse Growth and Differentiation of Transplanted Mouse and Human Mammary Stem Cells - February 2014

**Comment by lulock** [comment]
[**Schizophrenia risk from complex variation of complement component 4**](http://www.nature.com.ezproxy.library.ubc.ca/nature/journal/vaop/ncurrent/full/nature16549.html) - January 2016

**Comment by Irrationone** [comment]
[Interactions between immunity, proliferation and molecular subtype in breast cancer prognosis](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3798758/) - April 2013

**Comment by shamsbhuiyan** [comment]
[A spectral approach integrating functional genomic annotations for coding and noncoding variants](http://www.ncbi.nlm.nih.gov/pubmed/26727659) - January 2016

**Comment by hui-tony-zk** [comment]
[Coverage recommendations for methylation analysis by whole-genome bisulfite sequencing](http://www.nature.com/nmeth/journal/v12/n3/full/nmeth.3152.html) Nov 2014

**Comment by amaliar** [comment]
[Predicting functional regulatory SNPs in the human antimicrobial peptide genes DEFB1 and CAMP in tuberculosis and HIV/AIDS](http://www.sciencedirect.com/science/article/pii/S1476927115301523) - December 2015

**Comment by emminic93** [comment]
[MEF2B mutations in non-Hodgkin lymphoma dysregulate cell migration by decreasing MEF2B target gene activation](http://www.nature.com/ncomms/2015/150806/ncomms8953/full/ncomms8953.html) - August 2015

**Comment by David-Rattray** [comment]
[Metagenomic Analysis of Crohn’s Disease Patients Identifies Changes in the Virome and Microbiome Related to Disease Status and Therapy, and Detects Potential Interactions and Biomarkers](http://www.ncbi.nlm.nih.gov/pubmed/26313691) - Nov 2015

**Comment by farnushfarhadi** [comment]
[Integrative approaches for large-scale transcriptome-wide association studies](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3506.html) - Feb. 2016

**Comment by derekcho** [comment]
[Genome-wide study identifies two loci associated with lung function decline in mild to moderate COPD](http://www.ncbi.nlm.nih.gov/pubmed/22986903) - January 2013

**Comment by RashedHUBC** [comment]
[Comparison of normalization and differential expression analyses using RNA-Seq data from 726 individual Drosophila melanogaster] (http://www.ncbi.nlm.nih.gov/pubmed/?term=Comparison+of+normalization+and+differential+expression+analyses+using+RNA-Seq+data+from+726+individual+Drosophila+melanogaster) - January 2016

**Comment by genrocheleau** [comment]
[Gene expression profile in long-term non progressor HIV infected patients: In search of potential resistance factors](http://www.sciencedirect.com.ezproxy.library.ubc.ca/science/article/pii/S016158901400128X) - May 2014

**Comment by joeho604** [comment]
A metagenome-wide association study of gut microbiota in type 2 diabetes - October 2012

**Comment by michekwon** [comment]
[Treatment of Obesity with Celastrol](http://www.cell.com/abstract/S0092-8674%2815%2900559-0) - May 20

**Comment by ndimopoulos** [comment]
[Systems‐based analysis of Arabidopsis leaf growth reveals adaptation to water deficit](http://msb.embopress.org/content/8/1/606) - August 2012

**Comment by gdelgobbo** [comment]
[Whole Blood Gene Expression Profile Associated with Spontaneous Preterm Birth in Women with Threatened Preterm Labor](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0096901) - May 2014

**Comment by jmartiniuk** [comment]
[Genome-wide transcriptional profiling of Botrytis cinerea genes targeting plant cell walls during infections of different hosts] (http://journal.frontiersin.org/article/10.3389/fpls.2014.00435/full#) - September 2014

**Comment by jasgrewal** [comment]
[Computational analysis of cell-to-cell heterogeneity in single-cell RNA-sequencing data reveals hidden subpopulations of cells] (http://www.nature.com/nbt/journal/v33/n2/full/nbt.3102.html) - January 2015

**Comment by IreneDing** [comment]
[Molecular Signature of Smoking in Human Lung Tissues ](http://www.ncbi.nlm.nih.gov/pubmed/22659451)- Aug 2012

**Comment by rafarkas** [comment]
[MicroRNA Expression Profiling in HCV-Infected Human Hepatoma Cells Identifies Potential Anti-Viral Targets Induced by Interferon-α](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0055733) - February 2013

**Comment by w-zhang** [comment]
[Transcriptome analysis in calorie-restricted rats implicates epigenetic and post-translational mechanisms in neuroprotection and aging](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4699360/) - December 2015

**Comment by nellysaber** [comment]
[Proteome- and Transcriptome-Driven Reconstruction of the Human Myocyte Metabolic Network and Its Use for Identification of Markers for Diabetes](http://www.cell.com/cell-reports/fulltext/S2211-1247%2815%2900385-X) - May 2015

**Comment by schafers** [comment]
[Pregnancy-related complications and adverse pregnancy outcomes in multiple pregnancies resulting from assisted reproductive technology: a meta-analysis of cohort studies](http://www.ncbi.nlm.nih.gov/pubmed/25910567) - June 2015

**Comment by halldorbjarni** [comment]
[Similarity network fusion for aggregating data types on a genomic scale](http://www.nature.com/nmeth/journal/v11/n3/abs/nmeth.2810.html) - January 2014

**Comment by angelamo** [comment]
[Transfer RNA detection by small RNA deep sequencing and disease association with myelodysplastic syndromes](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4581457/) - September 2015

**Comment by jamesmelanson** [comment]
[Genome-wide nucleosome specificity and function of chromatin remodellers in ES cells](http://www.ncbi.nlm.nih.gov/pubmed/26814966) - January 2016

**Comment by jamesmelanson** [comment]
[Single-cell analysis reveals a stem-cell program in human metastatic breast cancer cells](http://www.ncbi.nlm.nih.gov/pubmed/26416748) - October 2015

**Comment by louiedinh** [comment]
[ A comparison of normalization methods for high density oligonucleotide array data based on variance and bias](http://www.ncbi.nlm.nih.gov/pubmed/12538238)

**Comment by eclaks** [comment]
[Modular Genetic Control of Sexually Dimorphic Behaviors] (http://www.sciencedirect.com.ezproxy.library.ubc.ca/science/article/pii/S0092867411015716) - February 2012

**Comment by pjobin10** [comment]
[Defining the transcriptome and proteome in three functionally different human cell lines](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3018165/) - December 2010

**Comment by hochoy** [comment]
[Enterotypes of the human microbiome](http://www.ncbi.nlm.nih.gov/pubmed/21508958) - May 2011

**Comment by ldgooding** [comment]
Comparison of genome-wide and gene-specific DNA methylation between ART and naturally conceived pregnancies.-Jan 2015

**Comment by galotalp** [comment]
[Bioinformatics prediction of HIV coreceptor usage](http://www.nature.com/nbt/journal/v25/n12/full/nbt1371.html) - December 2007

**Comment by kao7** [comment]
[Transcriptomics-based screen for genes induced by flagellin and repressed by pathogen effectors identifies a cell wall-associated kinase involved in plant immunity ](http://link.springer.com/article/10.1186%2Fgb-2013-14-12-r139) - December 2013

**Comment by min110** [comment]
[Integration of electrophysiological recordings with single-cell RNA-seq data identifies neuronal subtypes](http://www.nature.com/nbt/journal/v34/n2/full/nbt.3443.html)**  - December 2015

**Comment by ldgooding** [comment]
[Comparison of genome-wide and gene-specific DNA methylation between ART and naturally conceived pregnancies.](http://www.ncbi.nlm.nih.gov/pubmed/25580569) - January 2015

**Comment by AnnieXuanLi** [comment]
Differential expression analysis of human endogenous retroviruses based on ENCODE RNA-seq data[http://www.ncbi.nlm.nih.gov/pubmed/26530187] - November 2015

**Comment by blaiseratcliffe** [comment]
[Disentangling Detoxification: Gene Expression Analysis of Feeding Mountain Pine Beetle Illuminates Molecular-Level Host Chemical Defense Detoxification Mechanisms](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0077777) - November, 2013

**Comment by danseale** [comment]
[Community-wide transcriptome of the oral microbiome in subjects with and without periodontitis](http://www.nature.com/ismej/journal/v8/n8/full/ismej201423a.html) - March 2014
