### ISSUE TITLE
How's the assignment going? 

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#113]
You can ask questions by opening issues in the discussion board to get help from your peers and TAs.  

Also, please remember to regularly push your work to your repo, along with all the intermediate files.

**Comment by min110** [comment]
hey @santina I have some problems of understanding the questions , for example . in question 3. 
> Write out in English and as an equation the model you are using to assess differential expression. In the context of that model, what statistical test are you performing?

1. here , are we suppose to use limma even if it is only a one way anova ? 
2. for the equation, do you mean  y=xa+ error this equation  ? or the equation of T test ? or F test ? 
3. just find out I dont know how to type those equations with markdown 

Thanks !

**Comment by marjanfarahbod** [comment]
Hi Min, 

Thanks for being brave and posting your question here! 

Ok, here we go:

1.  You should fit a linear model. Remember from lecture notes (sort of, from 7 to 10!) that you could use both linear model and one way anova for differential expression. Here, it is required that you use linear model. limma is a package in R which has function for linear models.  

2. We mean the equation of linear model. You don't need to type the equation in a fancy way, just write it  in simple letters, explain what are the elements in it in English. :) Just make it clear that you know what is a linear model and how you model the data using it. 

3. As I said, it is OK. We don't require fancy mathematical phrases. 

Cheers and have fun!
