### ISSUE TITLE
Limma with both quantitative and treatment covariates

### ISSUE THREAD

**Issue by Phillip-a-richmond** [STAT540-UBC/Discussion#115]
Hello,
Within problem 5 we are supposed to run the linear model with a combination of time and treatment as the covariates, and then run the comparison between the treatments.  How does this impact our contrast matrix?

Here's what I have at the moment, but the intersection with 3 isn't that great:

design3 <- model.matrix(~0+ Treatment \* TimeInDigits,NHBEMetadata)
colnames(design3) <- c("Smoker","Control","Time","Treatment_Time")
contrast_matrix2 <- makeContrasts(Smoker-Control+Time+Treatment_Time,levels=design3)

It was simple for question 3, where we only needed:

contrast_matrix <- makeContrasts(Smoker-Control,levels=design)

In the seminar-6 it's broken down where each dev stage is it's own covariate, but with continuous/quantitative Time covariate, I'm unsure how to modify this argument (also not 100% sure my design matrix is correct).

Any suggestions?
Cheers,
Phil

**Comment by santina** [comment]
Hi @Phillip-a-richmond! The workflow for this question is in the latter part of lecture 10 and seminar 6. 

Your design matrix would be made like this:
`design3 <- model.matrix(~Treatment * TimeInDigits,NHBEMetadata)` without the 0.

**Comment by Phillip-a-richmond** [comment]
Thank you @santina !
