### ISSUE TITLE
Paper review - 02

### ISSUE THREAD

**Issue by marjanfarahbod** [STAT540-UBC/Discussion#119]
Hi guys, 

We have graded all the paper reviews from those responded to the paper review 01 issue. Those who opened an issue for marking the review already got their mark and feedback as well. 
It is time for paper review exercise (2nd one!)

**Important:** Make sure to open an issue for marking your paper review by the deadline on April 1st and put the last commit ID in it. It will be considered as late submission if you fail to open the issue or open it after the deadline. 
#### In general

Most of you did a very good job on understanding the goal of the paper and giving some comments on the mathematical methods. Some of you made good points about the biological experiment and design as well. 
#### First point - We asked for a review, not only a summary.

I wanted to emphasize that "writing a summary of a paper" is **very different** than "writing a review on a paper" and the goal of this exercise is the latter. It is important that you mention the goal and finding of the paper and the project as a baseline to write your review, however, **if you do not comment on the paper or you can not judge the procedures, you ARE NOT doing a review**. If you want to know how to learn this, the key is that you ask questions, like:
Why did the do it this way?
Why this method?
Why this dataset?
Why this database? What else is out there?
How could it be better?
#### Second point - Coherence is an important feature...

Scientific writing needs practice:
1. Before writing each sentence, make sure you know what is it exactly that you want to say in that sentence. After writing it, read it yourself. Does it say what you meant to say? Is it clear?  
2. Try not to use uninformative adjectives and adverbs (no _supercalifragilisticexpialidocious_!). Use the words only if you need to. It is not the goal to impress/confuse the reader by fancy/big/complicated words, the goal should be to transfer the idea/information in the most simple way. 
### Last but not least...

I shall refer you to these required items for the paper review from the assignment page: 
1. A brief review of the goal, findings and conclusion of the paper written by the student. (1.5 point)
2. A list (or mentioning) of the related datasets/databases and data types used in the study. In the case of datasets, provide some details of the data matrix and meta data. (1 point)
3. A brief review of the analytical steps in the paper with more details on some selected parts which are relevant to the course materials. You don’t need to understand all of the analysis, but should be able to identify the key analysis/method used to answer the question the paper is intended to answer. (1.5 point)
4. Some comments and critiques about the analytical steps, alternative suggestions or improvements. (1 point)

[This link](https://class.coursera.org/sciwrite-2012-001) on scientific writing to a Coursera course for those interested. 

---

Please go ahead and put the name of your paper, linked to the journal or Pubmed, with the year it was published in, like this:

**[Loss of motoneuron-specific microRNA-218 causes systemic neuromuscular failure](http://classic.sciencemag.org/content/350/6267/1525.long)**  - December 2015

You can find the instructions for this assignment in [here](http://stat540-ubc.github.io/subpages/assignments.html#paper-review)

 [This is the guideline](http://stat540-ubc.github.io/homework/paper_critique/PRguideline.html)
Here's [a resource on how to read a paper](https://github.com/jtleek/readingpapers) provided by Sara

[Paper review example 01](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/paper_critique/paperReviewMarjan.md) Marjan 
[Paper review example 02](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/paper_critique/paperReviewSantina.md) Santina

Good luck!

**Comment by fergusonandrew** [comment]
[Filling annotation gaps in yeast genomes using genome-wide contact maps](https://bioinformatics-oxfordjournals-org.ezproxy.library.ubc.ca/content/30/15/2105.full.pdf) - April 2014

**Comment by Irrationone** [comment]
[Immune and stromal classification of colorectal cancer is associated with molecular subtypes and relevant for precision immunotherapy](http://www.ncbi.nlm.nih.gov/pubmed/26994146) - March 2016

**Comment by cgmay** [comment]
[pVAC-Seq: A genome-guided in silico approach to identifying tumor neoantigens](http://genomemedicine.biomedcentral.com/articles/10.1186/s13073-016-0264-5) - January 2016

**Comment by hannibelle** [comment]
[Corona cell RNA sequencing from individual oocytes revealed transcripts and pathways linked to euploid oocyte competence and live birth](http://www.ncbi.nlm.nih.gov/pubmed/26995658) - March 2016

**Comment by jmartiniuk** [comment]
[Dynamics of the Saccharomyces cerevisiae Transcriptome during Bread Dough Fermentation](http://aem.asm.org/content/79/23/7325.full) - December 2013

**Comment by lulock** [comment]
[**DephosSite: a machine learning approach for discovering phosphotase-specific dephosphorylation sites**](http://www.nature.com/articles/srep23510) - March 2016

**Comment by genrocheleau** [comment]
[Genome-wide Methylation Profiles Reveal Quantitative Views of Human Aging Rates](http://ac.els-cdn.com.ezproxy.library.ubc.ca/S1097276512008933/1-s2.0-S1097276512008933-main.pdf?_tid=0bfad81c-f2c6-11e5-92e3-00000aacb35f&acdnat=1458936992_5303f607285148e902173ed1c3ed8b8d) - January 2013

**Comment by emminic93** [comment]
[Integrative Analyses of Colorectal Cancer Show Immunoscore Is a Stronger Predictor of Patient Survival Than Microsatellite Instability](http://www.cell.com/immunity/abstract/S1074-7613(16)30064-4?_returnURL=http%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1074761316300644%3Fshowall%3Dtrue) - March 2016

**Comment by RashedHUBC** [comment]
[http://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-015-0146-5](Differential expression analysis of human endogenous retroviruses based on ENCODE RNA-seq data) - November 2015

**Comment by ndimopoulos** [comment]
[Grapevine Rootstocks Differentially Affect the Rate of Ripening and Modulate Auxin-Related Genes in Cabernet Sauvignon](http://journal.frontiersin.org/article/10.3389/fpls.2016.00069/full) - February 2016

**Comment by joeho604** [comment]
[Defining the microbial transcriptional response to colitis through integrated host and microbiome profiling] (http://www.nature.com/ismej/journal/vaop/ncurrent/full/ismej201640a.html) - March 2016

**Comment by David-Rattray** [comment]
Development of a computational framework for the analysis of protein correlation profiling and spatial proteomics experiments. - Apr 2015

**Comment by gdelgobbo** [comment]
[Novel DNA methylation profiles associated with key gene regulation and transcription pathways in blood and placenta of growth-restricted neonates](https://www.ncbi.nlm.nih.gov/pubmed/25496377) - January 2015

**Comment by farnushfarhadi** [comment]
[Systematic analysis of somatic mutations impacting gene expression in 12 tumour types] (http://www.nature.com/ncomms/2015/151005/ncomms9554/pdf/ncomms9554.pdf) - October 2015

**Comment by danseale** [comment]
[Conservation and divergence of gene expression plasticity
following c. 140 million years of evolution in lodgepole pine (Pinus
contorta) and interior spruce (Picea glauca9 Picea engelmannii)](http://onlinelibrary.wiley.com/doi/10.1111/nph.12819/full) - April 2014

**Comment by AnnieXuanLi** [comment]
[Differential Gene Expression in Colon Tissue Associated With Diet, Lifestyle, and Related Oxidative Stress.](http://www.ncbi.nlm.nih.gov/pubmed/26230583) - July 2015

**Comment by samhinshaw** [comment]
[Differential gene network analysis for the identification of asthma-associated therapeutic targets in allergen-specific T-helper memory responses](http://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-016-0171-z) - Feb 2016

**Comment by galotalp** [comment]
[Molecular mechanism of ethylene stimulation of latex yield in rubber tree (Hevea brasiliensis) revealed by de novo sequencing and transcriptome analysis](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4806457/)- March 2016

**Comment by shamsbhuiyan** [comment]
[BayMeth: improved DNA methylation quantification for affinity capture sequencing data using a flexible Bayesian approach.](http://www.ncbi.nlm.nih.gov/pubmed/24517713)

**Comment by min110** [comment]
[Comprehensive evaluation of differential gene expression analysis methods for RNA-seq data](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4054597/)-SEP2013

**Comment by schafers** [comment]
[DNA Methylation Landscapes of Human Fetal Development](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005583) - October 2015

**Comment by jasgrewal** [comment]
[Novel drug target identification for the treatment of dementia using multi-relational association mining](http://www.nature.com/articles/srep11104) - July 2015

**Comment by rafarkas** [comment]
[An atlas of active enhancers across human cell types and tissues](http://www.nature.com/nature/journal/v507/n7493/full/nature12787.html) - March 2014

**Comment by pjobin10** [comment]
[The Urinary Bladder Transcriptome and Proteome Defined by Transcriptomics and Antibody-Based Profiling.](http://www.ncbi.nlm.nih.gov/pubmed/26694548) - Dec 2015

**Comment by w-zhang** [comment]
[Methylation on the Circadian Gene BMAL1 Is Associated with the Effects of a Weight Loss Intervention on Serum Lipid Levels.](http://jbr.sagepub.com/content/early/2016/02/11/0748730416629247.long)- Feb 2016

**Comment by halldorbjarni** [comment]
[Kernel approaches for differential expression
analysis of mass spectrometry-based
metabolomics data](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0506-3) - March 2015

**Comment by nellysaber** [comment]
[Reprogrammed Stomach Tissue as a Renewable Source of Functional β Cells for Blood Glucose Regulation] (http://www.cell.com/cell-stem-cell/abstract/S1934-5909%2816%2900004-7) - March 2016

**Comment by amaliar** [comment]
[Differential dynamics of the mammalian mRNA and protein expression response to misfolding stress](http://www-ncbi-nlm-nih-gov.ezproxy.library.ubc.ca/pmc/articles/PMC4731011/#msb156423-bib-0052) - Jan 2016

**Comment by IreneDing** [comment]
[Molecular Signature of Smoking in Human Lung Tissues](http://www.ncbi.nlm.nih.gov/pubmed/22659451)  - June 2012

**Comment by farnushfarhadi** [comment]
[Identification of a pan-cancer oncogenic microRNA superfamily anchored by a central core seed motif](http://www.nature.com/ncomms/2013/131113/ncomms3730/full/ncomms3730.html) - Nov. 2013

**Comment by angelamo** [comment]
[Systematic identification of genetic
influences on methylation across the
human life course](http://download.springer.com/static/pdf/833/art%253A10.1186%252Fs13059-016-0926-z.pdf?originUrl=http%3A%2F%2Fgenomebiology.biomedcentral.com%2Farticle%2F10.1186%2Fs13059-016-0926-z&token2=exp=1459515405~acl=%2Fstatic%2Fpdf%2F833%2Fart%25253A10.1186%25252Fs13059-016-0926-z.pdf*~hmac=ee3a094b0c0f186a7a184baeb32325822e1dda0ba81d305517f6b7a6b41f62fd) - Mar. 2016

**Comment by eclaks** [comment]
[High-throughput identification of genotype-specific cancer vulnerabilities in mixtures of barcoded tumor cell lines](http://www.nature.com/nbt/journal/vaop/ncurrent/full/nbt.3460.html) -  February 2016

**Comment by kao7** [comment]
[Effect of prior drought and pathogen stress on Arabidopsis transcriptome changes to caterpillar herbivory](http://www.ncbi.nlm.nih.gov/pubmed/26847575) - Feb 2016

**Comment by hui-tony-zk** [comment]
[Brain feminization requires active repression of masculinization via DNA methylation.](http://www.nature.com/neuro/journal/v18/n5/full/nn.3988.html) - May 2015

**Comment by ldgooding** [comment]
[Imprinted genes and imprinting control regions show predominant intermediate methylation in adult somatic tissues](http://www.futuremedicine.com/doi/full/10.2217/epi.16.8) - March 2016

**Comment by derekcho** [comment]
[Robust meta-analysis of gene expression using the elastic net](http://nar.oxfordjournals.org/content/early/2015/03/30/nar.gkv229.full) - March 2015

**Comment by jamesmelanson** [comment]
[Hierarchical Oct4 Binding in Concert with Primed Epigenetic Rearrangements during Somatic Cell Reprogramming](http://www.sciencedirect.com.ezproxy.library.ubc.ca/science/article/pii/S2211124716000334) - February 2016

**Comment by Phillip-a-richmond** [comment]
I posted the issue in my own repo.

[An extended set of yeast-based functional assays accurately identifies human disease mutations](https://github.com/STAT540-UBC/zz_richmond-phillip_STAT540_2016/blob/master/PaperCritique2/Genome%20Res.-2016-Sun-gr.192526.115.pdf) - Genome Research 2016

[Issue](https://github.com/STAT540-UBC/zz_richmond-phillip_STAT540_2016/issues/5)
