### ISSUE TITLE
Problems in displaying equations while viewing from Github

### ISSUE THREAD

**Issue by RashedHUBC** [STAT540-UBC/Discussion#120]
Hello,
I have written some equations for specifying models in Q3, Q4 and Q5. After writing when I checked the `.html` file created from `RStudio` it looked fine. But after uploading (push) to `Github` I have found that the equations are not displaying!!! The codes are displayed now!!! 
Can anyone have some idea regarding this?

**Comment by santina** [comment]
How did you write your equations? On which file on GitHub is not showing your equation?

**Comment by RashedHUBC** [comment]
Actually I wrote equations like using the formulation $$Y = AX + C$$ in the `.Rmd` file of my assignment. When I viewed the `.md` file in the Github I only saw the code chunk for writing equation rather then equation.
