### ISSUE TITLE
****About your homework****

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#121]
Hi folks, 

A few people have emailed us that they have trouble pushing your work onto Github. While most of you have submitted an issue to signal us that you've completed the assignment, there are problems with some of your the files on your GitHub repo.

I'd ask you to check a few things if you haven't: 
1. Click on your .md file on Github, do you see your figures, code, everything you expected to be there? Does it read like a nice report?  
2. Did you push all your files onto Github? (.Rmd, .md, .html, the folder with all the files). These files are auto-generated when you "knit" your .Rmd, and it's the .md file we are gonna look at because it has the figures. You also need to push the data you used in the assignment onto GitHub if you have been working with local copies of them on your computer. 
3. If you prefer that we view your .html file instead of .md, have you given us a link that works? see [the tips](http://stat540-ubc.github.io/subpages/assignment_tips.html#linking-to-html-files-in-the-repo) 
4. If you clone a fresh copy of your repo from Github onto any computer in any folder, open up a new RStudio session, knit the .Rmd file, does it just work?  It should!  Your report should be self-contained and shouldn't depend on how you name certain files outside of your repo (i.e use relative paths) 

If you have checked off all of the above, great! Go enjoy your weekend. **If not, stay tuned on this issue and please read [the assignment tips](http://stat540-ubc.github.io/subpages/assignment_tips.html) if you skipped reading it before.**

**Comment by santina** [comment]
okay, if there were some problems with your assignment submission, I have left a comment or two on your homework submission issues.

**Comment by marjanfarahbod** [comment]
Hi, 

I realize that many of students have problems with any of the things below: 

1. commit/ push to their repository
2. making .md file 
3. some other stuff. 

#### Here is the deal:

**We, strictly, expect to see an issue open by latest today for your homework, if you meant to submit today**. The time you open your issue and submit the commit history is the time we consider as the time you hand in your homework. This is for us to be sure that your code have not changed (locally) when you submit your .md later during the week.

#### Here is what we suggest you do if you have problems: 

If you have problem making .md from .rmd or problem pushing to github, you can just upload your .rmd manually from github user interface, make an issue and submit the commit history for that .rmd **today**. Again, this is for us to be sure that your code have not changed (locally) when you submit your .md later during the week.

Alternatively (try to avoid), you can email me or Santina your code or your .rmd and make the .md and .html later during the week. 

 **Notice (again):** unlike the paper review homework, we are not going to check your commit history to make sure you finished your homework on time (cause the time could be changed locally). The time you make the issue and submit your commit history for .md (or, alternatively and if you have problem with that, your .rmd), is the time we will consider as your homework-hand-in-time. 

#### Finally: 
Those who made the issue today will already miss some (although small) point for submitting late, as it was your responsibility to submit on-time and go through the instructions/trouble shooting before the last minute.
