### ISSUE TITLE
p.adjust()

### ISSUE THREAD

**Issue by samhinshaw** [STAT540-UBC/Discussion#125]
I am confused about how `p.adjust(adjust.method = "BH")`/`p.adjust(adjust.method = "fdr")` performs its correction.  

FDR correction in and of itself makes sense to me (as explained in [Bernard's lecture](http://stat540-ubc.github.io/lectures/lect11_multipleTesting.pdf) and at [this website](http://www.biostathandbook.com/multiplecomparisons.html)).  

As described in [Benjamini and Hochberg (1995)](http://www.stat.purdue.edu/~doerge/BIOINFORM.D/FALL06/Benjamini%20and%20Y%20FDR.pdf), you (the users) **sets** your q-value threshold (or false discovery rate) q*. 

![fdr](https://cloud.githubusercontent.com/assets/14186005/14329851/4ccc2bea-fbf2-11e5-9dbf-2e25e10d4177.png)

If you change this threshold, your q-value will change, because the formula used to compute your q-value incorporates this (i/m x q*)

Therefore, how is it possible that the `p.adjust(adjust.method = "BH")` does not require any Q value (false discovery rate) specified? My question is addressed in [this bioconductor support thread](https://support.bioconductor.org/p/7084/), but I do not fully understand the answer.  Perhaps I have a fundamental misunderstanding of how FDR correction works.

**Comment by hui-tony-zk** [comment]
Here's my interpretation of this:

The `p.adjust` function calculates the **adjusted p-value** given only the distribution of `p`-values, which is equivalent to the `q`-value. Then, the user pre-defines a `q`-value, and anything with a `q`-value less than the chosen threshold `q` is taken to be significant.

| Sample | adjusted p-value |
|--------|---------|
| a      | 0.0006  |
| b      | 0.004   |
| c      | 0.04    |
| d      | 0.1     |
| e      | 0.8     |

A chosen "q" cutoff of 0.05 means that `a, b, and c` are significant, and the proportion of false discoveries in your "significant" list (a, b, and c) is 5%.

From http://statweb.stanford.edu/~tibs/ftp/fdringenomics.pdf

> Suppose that features with q-values less than or equal to 5% are called significant in some genome-wide test of significance. **This implies that among all significant features, about 5% of them are false positives.**

**Comment by hui-tony-zk** [comment]
Whoops, I just realized I didn't answer your question. Let's try again:

So basically, the (i/m x q*) is used to satisfy the inequality. Therefore, the q-value that `p.adjust` calculated is the minimum q value that still satisfies the inequality Pi < i/m*q
