### ISSUE TITLE
Transferring ownership of the repos  - Individual repositories  

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#126]
Hi everyone, 

The semester is coming to an end. The STAT540 GitHub organization can only host a limited number of private repositories as of now, so we'll be either giving you back your repo or delete them. 

Perhaps some of you have already mirrored cloned your repo and don't really care about the issues in the original repo, or that you don't feel like you will look back to the content of your repo ever again, then you can ignore this issue. 

However, if you want your individual repo under your own GitHub account, say something in this issue! (I'll just need your GitHub ID to transfer the ownership of the repo, so you can just type some blank lines or say whatever.)  

Please respond to this issue by April 30. After that, we'll delete whatever that's left from this year.  

Thanks!  Have an awesome summer 🍹

**Comment by genrocheleau** [comment]
me :)

**Comment by lulock** [comment]
Hey, I'd like ownership! Thanks :relaxed:

**Comment by Irrationone** [comment]
yes please!

**Comment by w-zhang** [comment]
Sign me up!

**Comment by santina** [comment]
Anyone else wants their repo ?

**Comment by min110** [comment]
Me! thans Santina ! 
git ID : Min110
 Min

**Comment by santina** [comment]
If you don't have a horray reaction icon to your comment, that means I haven't transfered your repo to your account. I cannot do this for some of you because your GitHub account doesn't have at least one unused private repository available. 

To be able to make your account host private repos for free, you need tell GitHub that you're a student and upgrade your account to [Micro plan](https://github.com/account/plans). See [this](https://education.github.com/pack/offers) and scroll down to GitHub, obv check out other free developer tools for students :)   The reason why I want your repo to remain private is because the course might reuse some questions from the assignment next year. 

Sorry that I didn't realize this earlier, but you should definitely get that free Micro plan with GitHub, just like any free, useful stuff you can get while you're still a student!
