### ISSUE TITLE
Paper review selection

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#128]
It is time for paper review exercise! 
Please go ahead and put the name of your paper, linked to the journal or pubmed, with year it was published, like this:

**[Loss of motoneuron-specific microRNA-218 causes systemic neuromuscular failure](http://classic.sciencemag.org/content/350/6267/1525.long)**  - December 2015

You can find the instructions for this assignment in [here](http://stat540-ubc.github.io/subpages/assignments.html#paper-review)

 [This is the guideline](http://stat540-ubc.github.io/homework/paper_critique/PRguideline.html)

[Paper review example 01](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/paper_critique/paperReviewMarjan.md) Marjan 
[Paper review example 02](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/paper_critique/paperReviewSantina.md) Santina

**Comment by oktokat** [comment]
[Soil Microbiome Is More Heterogeneous in Organic Than in Conventional Farming System](https://www-ncbi-nlm-nih-gov.ezproxy.library.ubc.ca/pmc/articles/PMC5209367/) - January 2017

**Comment by rasiimwe** [comment]
[Systematic analysis of somatic mutations impacting gene expression in 12 tumour types](http://www.nature.com/articles/ncomms9554) - October 2015

**Comment by suminwei2772** [comment]
[Genome-wide changes in lncRNA, splicing, and regional gene expression patterns in autism](http://www.nature.com.ezproxy.library.ubc.ca/nature/journal/v540/n7633/pdf/nature20612.pdf) - 15 December 2016

**Comment by Hbrewis** [comment]
[Nucleosome Density ChIP-Seq Identifies Distinct Chromatin Modification Signatures Associated with MNase Accessibility](http://www.cell.com/cell-reports/fulltext/S2211-1247(16)31475-9) - November 2016

**Comment by cwarren5124** [comment]
[Genomic analyses identify molecular subtypes of pancreatic cancer](http://www.nature.com/nature/journal/v531/n7592/full/nature16965.html#transcriptomic-classification-of-pdac) - February 2016

**Comment by rasiimwe** [comment]
@singha53  @farnushfarhadi  @santina 
Hi,
I am still new to my lab and currently trying to learn as much as I can from my labmates. To do this, I follow their work, ask questions and review their papers. For this assignment, are we allowed to review papers from our labs?

**Comment by ppavlidis** [comment]
@rasiimwe I don't see an issue with using a paper from our own lab. As long as the writeup is your own work etc.

**Comment by rasiimwe** [comment]
@ppavlidis Great! Thanks

**Comment by myuen89** [comment]
[A 17-gene stemness score for rapid determination of risk in acute leukaemia](http://www.nature.com/nature/journal/v540/n7633/full/nature20598.html) - December 2016

**Comment by mccag94** [comment]
[Plasma Protein Biomarkers for Depression and Schizophrenia by Multi Analyte Profiling of Case-Control Collections](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0009166) - February 2010

**Comment by AdrianLJones** [comment]
[Identification of Type 1 Diabetes–Associated DNA Methylation Variable Positions That Precede Disease Diagnosis](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002300).  September 2011

**Comment by psomdeb25** [comment]
@singha53 @farnushfarhadi @santina
Can we write up a review of a Nature letter if it has statistical plots in it? 

- Thank you!

**Comment by ppavlidis** [comment]
@psomdeb25 Most papers in Nature are letters, if that's what you are referring to - the topic matters more: if it's a high-dimensional biology paper, any journal article would be appropriate. If you link to it we can check to be sure ...

**Comment by ChristinaMi** [comment]
[Host and Environmental Factors Influencing Individual Human Cytokine Responses](https://www.ncbi.nlm.nih.gov/pubmed/27814508) - November 2016

**Comment by stephblain** [comment]
[Among-lake reciprocal transplants induce convergent expression of immune genes in threespine stickleback](http://onlinelibrary.wiley.com/doi/10.1111/mec.13295/epdf) - September 2015

**Comment by psomdeb25** [comment]
Cell-of-origin chromatin organization shapes the mutational landscape of cancer - February 2015

**Comment by sonjasoo** [comment]
[Transcriptomic Analysis of Autistic Brain Reveals Convergent Molecular Pathology](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3607626/#SD3) - June 2011

**Comment by MaryHe** [comment]
[Diagnostic Test Accuracy of a 2-Transcript Host RNA Signature for Discriminating Bacterial vs Viral Infection in Febrile Children](http://jamanetwork.com/journals/jama/fullarticle/2545687) - August 2016

**Comment by acavalla** [comment]
[Single-cell epigenomic variability reveals functional cancer heterogeneity](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1133-7) - Jan 2017

**Comment by jie-cui** [comment]
[Insulator dysfunction and oncogene activation in IDH mutant gliomas](https://www.ncbi.nlm.nih.gov/pubmed/26700815)

**Comment by kevinjep** [comment]
[Whole-exome sequencing of circulating tumor cells provides a window into metastatic prostate cancer.](https://www.ncbi.nlm.nih.gov/pubmed/?term=circulating+tumor+cells+whole-exome+sequencing+lohr) -May 2014

**Comment by HAMacKay** [comment]
[Monolignol ferulate conjugates are naturally incorporated into plant lignins](http://advances.sciencemag.org/content/2/10/e1600393) - October 2016

**Comment by dakep** [comment]
[Lusardi TA et al. _MicroRNAs in Human Cerebrospinal Fluid as Biomarkers for
Alzheimer's Disease_. J Alzheimers Dis. 2017;55(3):1223-1233.](https://www.ncbi.nlm.nih.gov/pubmed/27814298)

**Comment by nivretta** [comment]
[Holtman, I. R. et al. Induction of a common microglia gene expression signature by aging and neurodegenerative conditions: a co-expression meta-analysis. Acta Neuropathologica Communications 3, 31 (2015).](https://actaneurocomms.biomedcentral.com/articles/10.1186/s40478-015-0203-5)

**Comment by vivianlac** [comment]
[Combined image and genomic analysis of high grade serous ovarian cancer reveals PTEN loss as a common driver event and prognostic factor](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0526-8) - December 2014

**Comment by kaskelso** [comment]
[Genome-wide RAD sequence data provide
unprecedented resolution of species boundaries and
relationships in the Lake Victoria cichlid adaptive
radiation](https://www.researchgate.net/profile/Oliver_Selz/publication/262493287_Genome-wide_RAD_sequence_data_provide_unprecedented_resolution_of_species_boundaries_and_relationships_in_the_Lake_Victoria_cichlid_adaptive_radiation/links/53d5280a0cf2a7fbb2ea5614.pdf) - October 2012

**Comment by gjahesh** [comment]
[OncoNEM: inferring tumor evolution from single-cell sequencing data](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0929-9)
Genome Biology 201617:69
DOI: 10.1186/s13059-016-0929-9

**Comment by emmagraham** [comment]
[Characteristics and Predictive Value of Blood Transcriptome Signature in Males with Autism Spectrum Disorders](http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0049475&type=printable)
PLoS One, Dec 2012
DOI: 10.1371/journal.pone.0049475

**Comment by fangwuwang** [comment]
[Mapping Whole-Transcriptome Splicing in Mouse Hematopoietic Stem Cells](http://www.cell.com/stem-cell-reports/abstract/S2213-6711(16)30278-8)
Stem Cell Reports, Jan 2017

**Comment by Nichalle** [comment]
[Ultrasensitive proteome analysis using paramagnetic bead technology](http://msb.embopress.org/content/msb/10/10/757.full.pdf) 
Molecular Systems Report, Oct 2014
DOI 10.15252/msb.20145625

**Comment by annizubc** [comment]
RNA Sequencing Analysis Reveals Interactions between Breast Cancer or Melanoma Cells and the Tissue Microenvironment during Brain Metastasis[https://www-hindawi-com.ezproxy.library.ubc.ca/journals/bmri/2017/8032910/](url)
BioMed Research International January 2017

**Comment by annizubc** [comment]
[https://www-hindawi-com.ezproxy.library.ubc.ca/journals/bmri/2017/8032910/](RNA Sequencing Analysis Reveals Interactions between Breast Cancer or Melanoma Cells and the Tissue Microenvironment during Brain Metastasis)
BioMed Research International Jan 2017

**Comment by annizubc** [comment]
[RNA Sequencing Analysis Reveals Interactions between Breast Cancer or Melanoma Cells and the Tissue Microenvironment during Brain Metastasis](https://www-hindawi-com.ezproxy.library.ubc.ca/journals/bmri/2017/8032910/)
BioMed Research International Jan 2017

**Comment by Dalalghamdi** [comment]
Whole-exome sequencing of individuals from an isolated
population implicates rare risk variants in bipolar disorder. 

PMID: 28195573 DOI: 10.1038/tp.2017.3

Feb 2017

**Comment by abaghela** [comment]
[http://www.jimmunol.org.ezproxy.library.ubc.ca/content/197/2/655#sec-2](url)

**Comment by abaghela** [comment]
[Transcriptional Profiling of Th2 Cells Identifies Pathogenic Features Associated with Asthma](http://www.jimmunol.org.ezproxy.library.ubc.ca/content/197/2/655#sec-2)

**Comment by kdever** [comment]
Single-cell transcriptomes identify human islet cell signatures and reveal cell-type–specific expression changes in type 2 diabetes

Genome Research, November 2016

**Comment by kdever** [comment]
[Single-cell transcriptomes identify human islet cell
signatures and reveal cell-type–specific expression
changes in type 2 diabetes](http://genome.cshlp.org/content/27/2/208.full)

Genome Research, November 2016

**Comment by kgibso29** [comment]
[Influence of donor age on induced pluripotent stem cels](http://www.nature.com/nbt/journal/v35/n1/full/nbt.3749.html)

Nature Biotechnology, 2017

**Comment by cmramirez91** [comment]
[αT-catenin in restricted brain cell types and its potential connection to autism](https://jmolecularpsychiatry.biomedcentral.com/articles/10.1186/s40303-016-0017-9)

Journal of Molecular Psychiatry, 2016

**Comment by Jwong684** [comment]
[DNA Methylation Dynamics of Human Hematopoietic Stem Cell Differentiation](http://www.cell.com/cell-stem-cell/fulltext/S1934-5909(16)30360-5)

Cell, December 2016

**Comment by slee94** [comment]
(G9a/GLP Complex Maintains Imprinted DNA Methylation in Embryonic Stem Cells)[https://www.ncbi.nlm.nih.gov/pubmed/27052169]

Cell Reports, 2016

**Comment by annizubc** [comment]
[Whole-transcriptome sequencing identifies a distinct subtype of acute lymphoblastic leukemia with predominant genomic abnormalities of EP300 and CREBBP.](https://www-ncbi-nlm-nih-gov.ezproxy.library.ubc.ca/pubmed/?term=Whole-transcriptome+sequencing+identifies+a+distinct+subtype+of+acute+lymphoblastic+leukemia+with+predominant+genomic+abnormalities+of+EP300+and+CREBBP
)
Genome Research, Feb 2017

**Comment by MingWan10** [comment]
[Genome-wide association study identifies peanut allergy-specific loci and evidence of epigenetic mediation in US children](https://www.ncbi.nlm.nih.gov/pubmed/25710614)
Nature Communications, Feb 2015

**Comment by samschaf** [comment]
[Whole genome grey and white matter DNA methylation profiles in dorsolateral prefrontal cortex
](http://onlinelibrary.wiley.com/doi/10.1002/syn.21959/full)
Synapse, Feb 2017

**Comment by nolanshe** [comment]
[Single-cell RNA-seq reveals changes in cell cycle and differentiation programs upon aging of hematopoietic stem cells](http://genome.cshlp.org/content/25/12/1860.full?sid=2210057d-4439-4568-8e7f-1fc4b8c5ee5c) 

Genome Research, Oct 2015

**Comment by rg7486** [comment]
[Social Status Alters Immune Regulation and Response in Infection in Macaques](http://science.sciencemag.org.ezproxy.library.ubc.ca/content/354/6315/1041) - November 2016

**Comment by wvictor14** [comment]
[Cell specific patterns of methylation in the human placenta](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3092685/) - 2011 March

**Comment by dejonggr** [comment]
[Discovery and functional prioritization of Parkinson’s disease candidate genes from large-scale whole exome sequencing](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1147-9) - Jan 2017

**Comment by faelicy** [comment]
[Reconstructing lineage hierarchies of the distal lung epithelium using single-cell RNA-seq](http://www.nature.com/nature/journal/v509/n7500/pdf/nature13173.pdf) - April 2014

**Comment by mhkinney** [comment]
[Rapid adaptive evolution of colour vision in the threespine stickleback radiation] (http://rspb.royalsocietypublishing.org/content/283/1830/20160242) - May 2016

**Comment by dvalgardson** [comment]
[Differentiation of pluripotent stem cells to muscle fiber to model Duchenne muscular dystrophy](http://go.galegroup.com.ezproxy.library.ubc.ca/ps/i.do?p=HRCA&u=ubcolumbia&id=GALE|A428998602&v=2.1&it=r&sid=summon&authCount=1) - Sept 2015

**Comment by atoor92** [comment]
[Niche and host-associated functional signatures of the root surface microbiome](https://www.ncbi.nlm.nih.gov/pubmed/?term=niche+and+host-associated+functional+signatures+of+the+root+surface+microbiome
)- September 2014

**Comment by rawnakhoque** [comment]
[Gene Expression Profiling of Breast Cancer Brain Metastasis](http://www.nature.com/articles/srep28623#methods) - June 2016

**Comment by acarnold** [comment]
[Modeling ecological drivers in marine viral communities using comparative metagenomics and network analyses](http://www.pnas.org/content/111/29/10714.full) - June 2014
