### ISSUE TITLE
Data sources?

### ISSUE THREAD

**Issue by AdrianLJones** [STAT540-UBC/Discussion#129]
I'm a stats student looking around for a project.  In class Prof Pavlidis mentioned that there are thousands of publicly available datasets but I don't know where to start looking.

Any pointers to good aggregators or databases to start with?

Thanks

**Comment by singha53** [comment]
Hi Adrian,

Here are a few:
1) [ArrayExpress](https://www.ebi.ac.uk/arrayexpress/browse.html?sortby=assays&sortorder=descending)

2) [NCBI](https://www.ncbi.nlm.nih.gov/home/download.shtml): access to multiple databases, e.g. 

a) Gene Expression Omnibus (GEO)
_Specific examples:_
If you have an accession number from a paper, you can directly download the data using the R library [GEOquery](https://bioconductor.org/packages/release/bioc/html/GEOquery.html)
The photoRec dataset used for seminar 01 is also on GEO: https://github.com/STAT540-UBC/STAT540-UBC.github.io/tree/master/examples/photoRec

b) Database of Genomic Structural Variation (dbVar), Database of Genotypes and Phenotypes (dbGaP)

3) Cancer Datasets (Multiple Omics) - The Cancer Genome Atlas
- https://cancergenome.nih.gov/
- http://firebrowse.org/

Best,
A

**Comment by AdrianLJones** [comment]
Thanks!
