### ISSUE TITLE
Group looking for dataset

### ISSUE THREAD

**Issue by ChrisCameron1** [STAT540-UBC/Discussion#13]
Hi,

We are a group of 5 but have yet to find an appropriate dataset. Wondering if anyone has dataset suggestions? Ideally, we would like to work with raw data that has yet to be statistically analyzed.

Thanks.

**Comment by swils6** [comment]
You can find a lot of datasets on GEO (http://www.ncbi.nlm.nih.gov/geo/) just beware that some major issues may be missing data.

**Comment by gcohenfr** [comment]
Still looking for a dataset? I can contact you with a researcher at UBC that has longitudinal gene data and needs help with the analysis. Please, talk to me if so.

**Comment by ChrisCameron1** [comment]
We just recently agreed on a dataset for our project. Thanks anyways!
