### ISSUE TITLE
Finding a project group + pitches

### ISSUE THREAD

**Issue by nivretta** [STAT540-UBC/Discussion#130]
Victor (@wvictor14) put together a [google doc](https://docs.google.com/document/d/1RBAk6S-HJoTkfRgb9On6Ny3fUNCzzOcPYwKVfLSfoHA/edit) to share pitches and organize teams. Please contribute!

**Comment by santina** [comment]
@STAT540-UBC/students 
Remember to think about your potential project, get to know people, pitch in class, and form a group before Jan 25! 😸

**Comment by gjahesh** [comment]
I was wondering if any one is going to work with any sort of plant data ( probably people from Forestry, plant sciences, etc)?
Thanks!

**Comment by dvalgardson** [comment]
@gjahesh 
Our group is working with unicellular algae and need one more person, if you are interested?

**Comment by psomdeb25** [comment]
@gjahesh What is the project about, that you are working on?

**Comment by psomdeb25** [comment]
@fangwuwang I looked into your project pitch and I was wondering if you are still working on the epigenomics of cell fate signalling?

**Comment by rawnakhoque** [comment]
@fangwuwang Your project looks interesting. Should you need a member I would be happy to join.

**Comment by fangwuwang** [comment]
@psomdeb25 @rawnakhoque @myuen89
Thank you for your interest in the project idea. I am not settled yet, shall we form a group? I will update the google doc then.

**Comment by psomdeb25** [comment]
@fangwuwang That sounds good to me.

**Comment by rawnakhoque** [comment]
@fangwuwang That would be great!

**Comment by gjahesh** [comment]
@dvalgardson  Thanks for the suggestion , I think I have settled with a group :)

**Comment by gjahesh** [comment]
Anyone with STAT background is left to join a group?

**Comment by fangwuwang** [comment]
We are looking for 1/+ member (see google doc project #5), if you are interested in stem cell differentiation/epigenomics!

**Comment by dvalgardson** [comment]
Our group is working with unicellular algae data and are looking for one more person!

**Comment by abaghela** [comment]
Hey everyone, I am part of a group with 4 members, and we are looking for one more! We are all in the Department of Bioinformatics (two people have more of a CompSci background, and two of us backgrounds in Biochem), but we want to branch out and see if we can get someone from another department (Stats, maybe?). 
We plan to analyze RNA-Seq data acquired by a lab in California. They obtained gene expression data for Th2 cells in a total of 80 patients. Some people had Asthma, some people have Rhinitis, and of course, there are also healthy controls. 
Both conditions are types of chronic allergic diseases, and share clinical features. However, there are some differences, namely, patients with rhinitis so do not develop asthma. We plan to find differences in gene expression in Th2 cells, to see what promotes the pathogenic nature of Th2 cells in both conditions. 
We may go further and explore correlations between gene expression and what individuals were allergic to (We also have data about that). We also might compare Th2 pathogenic signatures with other diseases that result in pathogenic Th2 (dermatitis, sinusitis)
Maybe email me, arjunsbaghela@gmail.com, if you are interested?

Thanks, 
Arjun

**Comment by gjahesh** [comment]
@dvalgardson I was wondering what type of algea data do you have? and also what are the majors are your group members so far? Thx

**Comment by nolanshe** [comment]
Hi Golnaz,


I am in Dani's group and we are going to be working with both RNA-seq and genomic sequencing data (vcf files, fasta files, etc). I believe we have one person from Botany, one from Zoology, one from Neuroscience and one from Bioinformatics. Let me know if you're interested!


Cheers,


Nolan

________________________________

**Comment by rawnakhoque** [comment]
@fangwuwang @psomdeb25 
Hi, I was wondering if we could meet to discuss on our project. You can contact me through rawnakmunni@gmail.com
Thanks,
Rawnak
