### ISSUE TITLE
For your homework: Knitting from Rmarkdown to markdown and html 

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#131]
Hi @STAT540-UBC/students , 

In case it's not super clear what the assignment instruction means when they said "knitting to markdown", I'm explaining it here. 

When you compile an R Markdown document to an HTML document, an intermediate Markdown document and other figures get created behind the scenes, but they're deleted once the HTML document is updated. To keep that intermediate Markdown document so you can use it for GitHub, change the top section (called the YAML front-matter) to the following. The keep_md option will ensure that the intermediate Markdown document that I mentioned earlier is kept around.

```
---
output: 
  html_document: 
    toc: yes
    keep_md: true
---
``` 
Each indentation is a tab, and make sure to have a space after the `:`
(If you're interested in learning more about R markdown, here's a [cheat sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf) that covers R markdown yaml matter) 

And then you can do the knitting by knitting the "knit html" button on the top.

If you are unsure or confused, check out [this example](https://github.com/STAT540-UBC/demo_santina/tree/master/seminar1), where [this Rmarkdown](https://github.com/STAT540-UBC/demo_santina/blob/master/seminar1/seminar1b.Rmd) is knitted into [this markdown](https://github.com/STAT540-UBC/demo_santina/blob/master/seminar1/seminar1b.md) and all the figures are created in [a separate folder](https://github.com/STAT540-UBC/demo_santina/tree/master/seminar1/seminar1b_files/figure-html). Read the content of the markdown for additional tips. 

Click on the button `raw` to see how the r markdown was written.

![image](https://cloud.githubusercontent.com/assets/1039839/21970586/8a31854e-db5c-11e6-8307-2b3e250a9e7b.png)

If you haven't submitted your practice homework yet, reminder that it's due in 3 days. If you're stuck, try to do as much of it as possible before the Wednesday seminar.

**Comment by santina** [comment]
Hi @STAT540-UBC/students, 

Don't mean to bug again, but it's relevant to your assignments (and future if you end up using Rmarkdown a lot). 
See this past issue here: https://github.com/STAT540-UBC/Discussion/issues/70

Your pretty html link will stop working after a while. Best to keep a markdown version in your Repo for you and your graders' convenience when we view your work. Thanks! 

P.S I personally prefer looking at your markdown! 😸

**Comment by singha53** [comment]
@STAT540-UBC/students 

Dear students,
It seems there are some rendering issues with github when working with the html_document output in the .Rmd file. Please change your output to the one below (this automatically generates a .md file as well)

```
---
output:
  github_document:
    toc: true
---
``` 

See additional details at: http://rmarkdown.rstudio.com/github_document_format.html
Let us know if you have questions,
Cheers,
A

**Comment by singha53** [comment]
@STAT540-UBC/students  The notice above is for future assignments, homework, projects etc. There is **no need** to re-submit the practice assignment with the above modification. No penalties will be applied for rendering issues for the practice assignment.
Best,
Amrit

**Comment by santina** [comment]
Thanks @singha53 
The `github_document` is a better idea.
