### ISSUE TITLE
Question: Table of Contents

### ISSUE THREAD

**Issue by MaryHe** [STAT540-UBC/Discussion#134]
Hi,

I just have a question about the table of contents generated using the option `toc: yes` in .Rmd file. On my laptop, this option automatically generates a table of content at the top of the output html file. However, when I pushed my works to github, the table of content would not show. Is there a way to solve this?

Thanks,
Mary

**Comment by singha53** [comment]
Hi Mary,
Try doctoc
http://stackoverflow.com/questions/9721944/automatic-toc-in-github-flavoured-markdown
A

**Comment by singha53** [comment]
Hi Mary,
This is even easier - change your yaml header document type in your .Rmd file:
output:
  github_document:
    toc: true

This automatically generates an md file.
http://rmarkdown.rstudio.com/github_document_format.html
A

**Comment by MaryHe** [comment]
Hi Amrit,

Thanks a lot! I'll try it!

Mary
