### ISSUE TITLE
Merging Error

### ISSUE THREAD

**Issue by jt1013** [STAT540-UBC/Discussion#135]
Hello,

I was trying to update my PracticeAssignment.rmd and tried to commit my changes from RStudio onto GitHub but ended up getting an error with a hint to pull the files and pushing it again. After pulling, I proceeded forward to commit and push again but it still gave me this error:

 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to '<my github repo>'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details. 

Has anyone else experienced this issue and resolved it?

Thanks,
Jeff

**Comment by singha53** [comment]
Hi Jeff,
How about deleting your repo and cloning your repo again. Then swap ur old files with new ones and push?
A

**Comment by jt1013** [comment]
Hi Amrit,

I'm not quite sure what happened but I guess when I committed and pushed, it got stuck. I had to abort the merge and try again.

Thanks!

**Comment by singha53** [comment]
Oh ok. great!
A
