### ISSUE TITLE
Assignment questions

### ISSUE THREAD

**Issue by suminwei2772** [STAT540-UBC/Discussion#136]
Hi @santina @farnushfarhadi @singha53 ,
I was wondering if I can get some clarification about Question 1.3 in the assignment:
The question asks to "create a plot showing the gene expression data for a random probe and the averages for all possible combinations of agent and time."
So, are we supposed to first plot the gene expression by submitting the raw data - labeling the conditions with different colors, then secondly create another plot after aggregating the data on treatment+time? 
For the second plot stated above, I didn't know what the x-axis would be. I did: 
ggplot(data.frame(rand_prob), aes(x=rownames(rand_prob), y=X1294_at)) + facet_wrap(~ Treatment + time_num)
but the plots had no data points.

*rand_prob (X1294_a) = data for one probe, annotated with each sample's treatment and time.

**Comment by farnushfarhadi** [comment]
Hey thank you for asking question :) @suminwei2772 

you use the `NHBE_transcriptome_data` which has around 22K rows! Then you pick a random row .. This is your random probe. You can have a plot of this probe with y axis = expression levels and x axis = treatment. So you would see all probes belonging to `cigarette_smoke` group on one side of the plot and all probes belonging to `control` group on the other side of your plot :) You can use `aes()` and `ggplot()` to do this easily. You should pass a factorial variable to your aes()! Check seminars for that ... You might want to label your gene expression average for each group on your plot as well. 

To have a plot for all possible combinations of agent and time, you can just repeat what you have done for each of the four different `time` levels. Time is a factorial variable here and `facet` gets factorial variable ... 

Thank you for starting assignment soon!

**Comment by suminwei2772** [comment]
@farnushfarhadi, I did something like this to separate probe expression vs Treatment plots based on time point (mean marked in black as specified by stat_summary: 

ggplot(rand_prob, aes(x=Treatment, y=X1294_at, color=Treatment)) + geom_point() + facet_wrap(~ time_num) + stat_summary(fun.y = "mean", colour = "black", size = 2, geom = "point")

Does this answer the question?
Thank you!

**Comment by suminwei2772** [comment]
@santina @farnushfarhadi 
For Q2.1: I don't understand why we are ordering/sorting on the samples based on time and agent to get correlation matrices. I was thinking of using the cor() function, and it seems I need to put in are the two matrices, for which I'm not sure what to input either.

**Comment by ppavlidis** [comment]
`cor()` will give you the correlations of the columns of a matrix. As the help (via ?cor) explains:

> `cor(x, y = NULL, ...`

y = NULL means that by default y is NULL, which is an indication that it is optional. In contrast x is required. 

It further says under details in the help it says "For cov and cor one must either give a matrix or data frame for x or give both x and y."

**Comment by suminwei2772** [comment]
Thank you for your helpful answers!
For Question 2,
When you say "make a quantitative statement about presence of an outlier: e.g., quantify for each sample, whether it “sticks out” compared to the other samples," can we do, for instance, a fold change of that sample's expression value compared to the mean of the rest of the samples? What other sort of quantification would you suggest?

**Comment by cwarren5124** [comment]
I believe I am having similar issues on the ordering and sorting. I'm not entirely sure of the definition. Does it mean that to order based on time is to have the timepoints grouped within the x axis and to sort based on treatment to have the treatment options grouped on the y axis?

**Comment by singha53** [comment]
@cwarren5124 yes and vice-versa for questions 2.1.

**Comment by cwarren5124** [comment]
@singha53   Thank you!
