### ISSUE TITLE
Did anyone happen to pick up my coffee mug after the seminar in the lab today (01 Feb)?

### ISSUE THREAD

**Issue by rbalshaw** [STAT540-UBC/Discussion#137]
Sorry to bother everyone, but I believe I left my very cool, dark blue(?) travel coffee mug.  If anyone saw it or picked it up, please let me know.

Thank you!

**Comment by farnushfarhadi** [comment]
@rbalshaw Santina and I found it today when we were leaving the seminar room! It is with me. Will bring it on Monday.

**Comment by rbalshaw** [comment]
Thank you!
