### ISSUE TITLE
Question on using techniques outside the course material

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#14]
For instance, can we use techniques like "Expectation Maximization" to deal with missing data ? or are we constrained to only the techniques taught in the course ?

In other words, if I use the techniques taught in the course, am I allowed to compare them with or apply  other techniques in the literature ?

Thanks.

**Comment by aliceZhu** [comment]
For this year, I'm not sure, it's better to check it with the Profs @gcohenfr @jennybc 

When I took this course (2013), our group used some normalization methods not taught in the course since our group was dealing with DNA methylation data.
