### ISSUE TITLE
Preprocessing for 450k methylation array

### ISSUE THREAD

**Issue by myuen89** [STAT540-UBC/Discussion#143]
@singha53 
@MingWan10

Hi Dr. Singh, we spoke earlier about methods of preprocessing 450k data and you mentioned a resource which gives a good example. Can you send it through here? 

Cheers,
@myuen89

**Comment by singha53** [comment]
Here are a couple:

Source 1: Analysis of 450k DNA methylation data with minfi
http://kasperdanielhansen.github.io/genbioconductor/html/minfi.html

Source 2: ChAMP package: "ChAMP provides a comprehensive and complete analysis pipeline from origin data file to final GSEA result"
https://bioconductor.org/packages/release/bioc/html/ChAMP.html
https://bioconductor.org/packages/release/bioc/vignettes/ChAMP/inst/doc/ChAMP.html#introduction

Source 3: PH525x series - Biomedical Data Science (see DNA methylation data analysis at the end of the webpage)
http://genomicsclass.github.io/book/

Hope this helps!
