### ISSUE TITLE
Inventor of R coming to UBC! 

### ISSUE THREAD

**Issue by singha53** [STAT540-UBC/Discussion#144]
**Data Science Institute Launch Event
by Data Science Institute**
https://www.eventbrite.ca/e/data-science-institute-launch-event-tickets-31166039463?utm_source=eb_email&utm_medium=email&utm_campaign=order_confirmation_email&utm_term=eventname&ref=eemailordconf

DESCRIPTION
**Dr. Robert Gentleman** (VP, Computational Biology, 23andMe) will be giving the inaugural DSI Distinguished Lecture, titled "Participant-focused Research for Genetics and Drug Discovery", with reception to follow.
Abstract: 23andMe is a company that pioneered the direct-to-consumer genetics market and recently started offering its technology services as an end-to-end solution to researchers conducting genetic studies. With over 1,000,000 individuals genotyped, and matched with phenotype data collected from survey responses and sensors, 23andMe is leveraging this massive dataset to better understand human traits, disease, and ancestry. Dr. Gentleman will describe how 23andMe is using its participant-focused research model for doing research and how 23andMe is collaborating with scientists to further our understanding of genetics and applying it for drug discovery.
Dr. Gentleman's Bio: https://researchers.23andme.org/robert-gentleman-phd.
* Reception is sponsored by the Pacific Institute for the Mathematical Sciences (PIMS).

**Comment by ppavlidis** [comment]
Warning: There are no tickets available any more. 

If you know who to ask (no, not me) you may be able to finagle one.

**Comment by santina** [comment]
Haha, Paul. Got it! 
It's interesting that they're pitching him as the VP of 23andMe instead of the work he did with R and Bioconductor and that he's an UBC alumnus.
