### ISSUE TITLE
Question on Analysis Assignment Q2.1

### ISSUE THREAD

**Issue by MaryHe** [STAT540-UBC/Discussion#146]
Just want to check, is the question asking us to calculate the correlation matrices and then visualise the matrices using heatmap?

Thanks in advance,
Mary

**Comment by farnushfarhadi** [comment]
@MaryHe Yes you are right. 

I guess you would like [this post](https://github.com/STAT540-UBC/Discussion/issues/140).

**Comment by MaryHe** [comment]
Thanks a lot!

Mary
