### ISSUE TITLE
Q2.2 Assess the presence of outlier samples

### ISSUE THREAD

**Issue by singha53** [STAT540-UBC/Discussion#149]
@oktokat

There were a lot of concepts (what is an outlier, univariate vs. multivariate outlier, use of mahalanobis distance) floating around in the previous issue, so I will summarize them and see if I can add to the answers regarding your question.

I agree with @ppavlidis that the question can be revised. As it currently stands its merits include its openness to many correct answers depending on how students interpret this question. The disadvantage is that it makes the job of the TAs a lot harder since they have to rationalize each answer and mark them!

The term “outlier” can be used in various contexts, is a sample different from others? (can be due to experimental, biological factors). As @dakep said, they could be coming from a different underlying distribution. Furthermore, different methods used to identify outliers are looking at different aspects of the data, and therefore may find slightly different “outlying” samples. This does not mean either is wrong!

Furthermore, as you will see, sometimes identifying outliers is a bit of an art, because they are not always so clear cut. Therefore, limma suggests you use weights for arrays (samples) instead of removing samples. However, if you have reason to believe a sample is an outlier, you should remove it. As slide 22/36 in lecture-5: Data QC and preprocessing points out: “Determine criteria for identifying outliers and stick with them”. Different individuals may have slightly different answers upon their discretion, beliefs or platform guidelines. For example, the nanoString platform which profile gene expression also contains positive controls (oligonucleotides with known spike-in concentrations). Therefore, the positive control expression values should be highly correlated with the concentrations values (correlation threshold of 0.99). If a sample has a correlatoin value below that cut-off, it is flagged. 

In the case of Q2.2 (Assess the presence of outliers), you should expect that across the 20K genes, the correlation between samples across all genes should be high. Further similar samples should have stronger correlation values than dissimilar samples based on covariates such as time, and treatment. 

> Is this the right idea surrounding mahalanobis distance? If so, how do you determine which distances are "significant" (quantifiable) outliers? The numbers we're getting are all very small (most below 0.1), which-if they're in terms of sd-aren't significant at all.
> Are we even on the right track with using mahalanobis distance? We didn't spend very much time talking about it in class, so if you have other suggestions/tips they'd be greatly appreciated!

As @rbalshaw  said, you are on the right track. However, I am surprised you were even able to calculate it given that you are in a high dimensional setting (n << p). I believe this is what @dakep was getting at. Note that the mahalanobis distance involves computing the inverse of the covariance matrix which in the of a high dimensional setting should not work! We will introduce the concept of regularization later in the course where this will become clearer. As for the assignment question, the purpose is to convert what you see on the heatmap. That is, on average what is the correlation of a given sample with all other samples, or within a group (time, treatment) of interest.

Let me demonstrate:

Suppose you profiled the gene expression for 2 genes for 100 subjects. I will add an outlier subject and show you what the mahalanobis distance is getting at.

```
library(tidyverse)
rafalib::mypar()

## simulate data with outliers
## what is an outlier? (many things!)
set.seed(324)
gene1 <- rnorm(100, mean = 0, sd = 1)
gene2 <- 0.7*gene1 + rnorm(100, sd=0.2)

## add outlier
gene1.w.outlier <- c(gene1, 1.5)
gene2.w.outlier <- c(gene2, -1)
Dat <- cbind(gene1.w.outlier, gene2.w.outlier)

par(mfrow = c(1, 2))
plot(gene2 ~ gene1, pch = 19, col = 1)
plot(Dat, col = c(rep(1, length(gene1)), 2), pch = 19)
```
![image](https://cloud.githubusercontent.com/assets/8978305/23325229/b383eca0-faa8-11e6-96aa-2130a89b2c4e.png)

Samples that are not outliers at the univariate level may be in the multivariate level.

```
## univariate outlier detection
Dat %>% as.data.frame %>% 
  gather(Gene, Exp) %>% 
  ggplot(aes(x = Exp, fill = Gene)) + geom_histogram() +
  geom_vline(xintercept = c(1.5, -1), linetype = "dashed") +
  ggtitle("Outlier within data distributions")
```

![image](https://cloud.githubusercontent.com/assets/8978305/23325297/33eacad0-faa9-11e6-8e53-42a62e261135.png)

```
par(mfrow = c(1,1))
boxplot(Dat, main = "Outlier within whiskers",
  ylab = "gene expression")
```

![image](https://cloud.githubusercontent.com/assets/8978305/23325316/6176530c-faa9-11e6-857b-61872cfff86d.png)

### So far no outliers can be detected!

Lets see how the mahalanobis distance performs.
```
## multivariate outlier detection (mahalnobis distance)
mahal <- mahalanobis(Dat, center = colMeans(Dat), cov = cov(Dat))
plot(mahal, ylab = "mahalnobis distance",
  main = "Outlier found!",
  xlab = "Samples")
```
![image](https://cloud.githubusercontent.com/assets/8978305/23325406/d9e30998-faa9-11e6-9592-56d4242d2338.png)

The reason why this works is because the mahalanobis distance as @rbalshaw mentioned, tells you how far each point is from the centroid (multivariate mean).

```
plot(Dat, ylim = c(-3, 3), xlim = c(-3, 3),
  , col = c(rep(1, length(gene1)), 2), pch = 19)
points(ellipse::ellipse(cor(Dat), ,
  scale = apply(Dat, 2, sd), center = colMeans(Dat), level = 0.95), type = "l")

```
![image](https://cloud.githubusercontent.com/assets/8978305/23325564/2ce931c0-faab-11e6-9e4b-fa6cef7e3aa6.png)

But what happens in the high-dimensional case (n << p)? Suppose you have p genes, n samples and nOutlier outliers. And your sample correlation heatmap looks like this:

```
## high dimensional dataset (p >>  n)
p = 100 # number of genes
n = 10    # number of samples
nOutlier <- 3  # number of outlier samples

sigmaCor <- 0.99^abs(outer(1:n, 1:n, "-"))
## create a p x n gene expression dataset
eset <- rmvnorm(n = p, mean = rep(0, ncol(sigmaCor)), sigma = sigmaCor) 

eset.w.outliers <- cbind(eset, matrix(runif(nOutlier*p), ncol = nOutlier))
gplots::heatmap.2(cor(eset.w.outliers), trace = "none", 
    key.xlab = "Sample correlation", key.title = "")
```

![image](https://cloud.githubusercontent.com/assets/8978305/23325669/e42c7acc-faab-11e6-865e-b5e189db2b6f.png)

You can see here that 3 samples do not agree with the rest of samples. How can you quantify this? On average how does one sample compare with the others?
```
plot(density(rowMeans(cor(eset.w.outliers))), 
  main = "Average correlation with other samples")
rug(rowMeans(cor(eset.w.outliers)))
```
![image](https://cloud.githubusercontent.com/assets/8978305/23325697/2605e5e6-faac-11e6-9840-c9f8659f0f0b.png)

What correlation value can you tolerate? Suppose I use a cut-off of 0.7.
![image](https://cloud.githubusercontent.com/assets/8978305/23325713/449a2512-faac-11e6-99a6-4a517e004f9a.png)

Using this cut-off I found 3 outliers. Note: It is not always this obvious, and you may not want to throw samples out if its not. As @ppavlidis mentioned you will learn other ways of exploring the data (e.g. Principal Component Analysis) where multivariate outliers are more evident.

Lets use the mahalnobis distance to determine outlying genes and samples:
```
## mahalanobis distance (outlier genes)
mahal2 <- mahalanobis(eset.w.outliers, 
  center = colMeans(eset.w.outliers), cov = cov(eset.w.outliers))
plot(mahal2) ## any gene outliers (probably not)
```

![image](https://cloud.githubusercontent.com/assets/8978305/23325771/d3a35ab2-faac-11e6-9154-2a2a09825336.png)

```
## mahalanobis distance (outlier samples)
mahal3 <- mahalanobis(t(eset.w.outliers), 
  center = rowMeans(eset.w.outliers), cov = cov(t(eset.w.outliers)))
```
### You should receive an error message:
Error in solve.default(cov, ...) : 
  system is computationally singular: reciprocal condition number = 1.44543e-21

That is because the covariance matrix is not invertible and thus the **mahalanobis distance cannot be computed for the samples**. This happens when you have more variables than samples. Think of this in the context of a linear model where you have a system of linear equations. When you have more unknowns (# of variables) than equations (# of samples) then the system is undetermined with an infinite number of solutions. This results in a singular matrix that is not invertible. The solutions to this problem are beyond the scope of this course: https://web.hku.hk/~gyin/materials/2015RoZouWangYinBiometrika.pdf

However, it is a good introduction to dimension reduction methods such as Principal Component Analysis, where multivariate data of p-dimensions can be represented using a few dimensions (called principal components). I will leave the detailed explanation until Lecture 14, but I can show you what you can expect (not required for the assignment):
```
pcomp <- prcomp(t(eset.w.outliers), scale. = TRUE, center = TRUE)
ggbiplot::ggbiplot(pcomp, ellipse = TRUE, circle = TRUE, var.axes = FALSE,
  group = rep("Group", ncol(eset.w.outliers)))
```
![image](https://cloud.githubusercontent.com/assets/8978305/23326088/5795783a-faaf-11e6-9a66-184c4e286f44.png)

I will touch on one more thing before I close and that is, clusters of multiple samples may not outliers, but rather driven by some biological (time, treatment) or technical variable (batch).

```
gp <- rep(c("Group1", "Group2"), c(n, nOutlier))
ggbiplot::ggbiplot(pcomp, ellipse = TRUE, circle = TRUE, var.axes = FALSE,
  group = gp)
```
![image](https://cloud.githubusercontent.com/assets/8978305/23326128/bdaf34c6-faaf-11e6-9a9f-8bc7dda25d25.png)

Now, the 3 outlying samples may belong to a different group and thus may or may not be treated as outliers. 

Let me know if you have more questions!
Cheers

**Comment by oktokat** [comment]
@singha53 Wow, thanks so much for the awesome and thorough summary! Also, seeing your code and what it produces is extremely helpful in understanding what's going on. And you're right to be surprised about getting MD in the assignment; I wasn't actually able to successfully calculate the MD, which is partially why I was confused. I think I'll be on the right track at this point.. seems I was delving a bit too deep for what the question was actually asking. Many thanks and enjoy your weekend!
