### ISSUE TITLE
Anyone know a good resource for restructuring data?

### ISSUE THREAD

**Issue by mas29** [STAT540-UBC/Discussion#15]
Code for restructuring data, like this: 

nDat <-
  with(kDat,
       data.frame(sidChar, sidNum, devStage, gType, crabHammer,
                  probeset = factor(rep(c("eggBomb", "poisonFang"),
                                        each = nrow(kDat))),
                  geneExp = c(eggBomb, poisonFang)))

and naming columns of one data frame based on another data frame, like this:

colnames(hDat) <- with(prDes, paste(devStage, gType, sidChar, sep = "_"))

is very useful, but I'd love to know how they work, and what other tools are available to restructure data in different ways. Anyone know of a good resource for this?

**Comment by wdurnoUBC** [comment]
I find reshape and dplyr useful.
http://www.statmethods.net/management/reshape.html
http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html

**Comment by jennybc** [comment]
I second @wdurnoUBC: the add-on packages `dplyr` and `reshape2` are very useful. I also suggest the package `tidyr`, which mostly just provides wrappers around functions in `reshape2` that are generally more user-friendly. Also look at the [`broom`](https://github.com/dgrtwo/broom) package which does some neat things.

RStudio just put out a good data manipulation [cheat sheet](http://www.rstudio.com/resources/cheatsheets/) for `dplyr` and `tidyr`.

We talked a lot about data manipulation, reshaping, and tidying in STAT 545, so you will find several topics of interest in this index:

http://stat545-ubc.github.io/topics.html

Such as

http://stat545-ubc.github.io/block009_dplyr-intro.html
http://stat545-ubc.github.io/block010_dplyr-end-single-table.html
http://stat545-ubc.github.io/bit001_dplyr-cheatsheet.html
http://stat545-ubc.github.io/bit002_tidying-lotr-data.html

**Comment by AlisonMcAfee** [comment]
Thank you! I was wondering the same thing.

**Comment by mas29** [comment]
Thank you everyone, these will be very helpful!
