### ISSUE TITLE
Some guidance on the assignment Q1-Q5

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#151]
Hi @STAT540-UBC/students, since the deadline for the first half of the assignment is tomorrow and that some of you might have similar questions, we will answer some of the common or likely questions (or at least point you to the right direction) we'll get on Wednesday. That way, we can have more time for more specific questions about the assignment and projects during the seminar. 

Tips: 
- Many things are in the lecture slides, seminars materials, and the issues posted by your classmates
- The Internet is your friend if you want to figure out how to do certain things in R. 

Btw when we say "how many hits are associated at p value x" we meant less than or equal to x. Sorry about that wording. 

(@singha53 @farnushfarhadi please correct me in this post if there's anything that's off. It's early after all.)

### Q1 Basic Graphing 
This one is quite straightforward, just like the graphing in the practice assignment. Some had a little hiccup with the basic graphing, for which you just need to select one random row from the data, and create a new data frame by combining information in that row and the metadata together. See #136 
Think about how that data.frame should look like for your graphing purpose.

You can unzip the big data file with `gzfile()`

### Q2 Assessing data quality 
See #136 for getting the data for your heatmap and what we meant by ordering. What does correlation mean? See #140. There are many ways to make a heatmap, like with `pheatmap` or `heatmap.2` packages, etc. Focus on drawing out the heatmap with labels first and then worry about ordering later. Look into the documentation about ordering and do your own research. Oh I already found something [here](https://www.biostars.org/p/108247/). 

About the outlier, see #149. Use correlation as a way to evaluate if something sticks out more or not. Like literally `e.g., given a sample that is least similar to all other samples: does it correlate with samples treated with same agent better than other samples treated with a different agent?`

#### 3.1 
Haven't gotten questions about fitting this linear model. I think people have figured it out with seminar 6.   I just want to point out one thing that doesn't matter much in this assignment but can matter a lot in your other projects (for this class or other places). If you do `model.matrix(~Treatment, NHBE_des)` where `NHBE_des` is the metadata, and look at your output (the design matrix), it's using "Treatmentcontrol" as your coefficient and cigarette smoke as your intercept. This is because `model.matrix` automatically chooses the first factor as the reference (when you do `str` on your metadata, the factor for cigarette_smoke shows up first). Since we only have two conditions, you'd get the same significant genes regardless which of the two conditions you use for the reference, just the opposite log fold change. But you can imagine that this matters A LOT when you have more than just two conditions. 

What you can do to change the order of factors: 
`NHBE_des$Treatment<-relevel(NHBE_des$Treatment, ref="control")`
This make the factor "control" as the first one. 

To describe your linear model in English, see [lecture 7](http://stat540-ubc.github.io/lectures/lect07_k_group_comp.pdf) and 20ish slides (this is for design matrix). That's where we first described the general linear model in the matrix formulation. Describe what each part of the equation means _in the context of this specific question_. You can either use a design matrix or contrast matrix depending on which parametrization you choose. 

#### 3.2 
The confusion for this question mostly comes from what's false discovery rate (FDR), and what do you mean by the estimated FDR for this hit list. Let's start with a little background info: 
Start by Amrit's awesome post on pvalues here: #141. _P values are uniformly distributed when null hypothesis is true_. What about when it's not true? It'd be like a histogram that's skewed right. If you overlay them (taken from [this blogpost](http://varianceexplained.org/statistics/interpreting-pvalue-histogram/) which you should definitely read! 
![image](https://cloud.githubusercontent.com/assets/1039839/23405400/e5dbe644-fd6e-11e6-9a5b-8e48b5f37089.png)

And then you say: "hey I'm gonna use p<=0.05 as my cutoff for choosing my significant genes" and draw a line there and get like 100 genes. You can see that while you're missing some blue, you're including some red, which correspond to genes for which the null hypothesis is true but by chance has low p values. Those are your false positives. So FDR = F / 100   (number of false positives/number of significant genes). How do you get the FDR. There are different ways to do it. See lecture 11 and maybe [this](http://genomine.org/papers/Storey_FDR_2011.pdf)

btw I'm using false positives and false discoveries as two interchangeable terms. However, false positive rate and false discovery rate are not the same thing as described [here](www.biomarkerdiscovery.net/FDR.html) 

With FDR, you can then get a sense of how many false discoveries you have by doing F = FDR * S .  So when we ask "what's the estimated false discovery rate for our top n genes", we are basically asking for that FDR that can tell us how many false discoveries are in our top n, by doing FDR * n. 

Where can you find those FDR? When you do `toptable()` you get two columns of P values : P.Values and adj.P.Val. The first one is the unadjusted p values, the second one is your FDR. If you don't specify an adjustment method, by default it's using the BH (Benjamini-Hochberg) method. In this case it's also called q value (correct me if I'm wrong). Each of those adjusted p values tells you the FDR at the corresponding unadjusted p value if you use that unadjusted p value as your cutoff (like the black line I drew in the figure). I think that's enough hint. 😸  For more see slide 15 and beyond in [lecture 11](https://stat540-ubc.github.io/lectures/lect11_multipleTesting.pdf). 

### Q4 Differential expression with respect to time
Make sure to use the qualitative covariate, treating the time as number. Someone told me that they were confused by the design matrix made this way because it's not made of 1 and 0 like when you use categorical covariates. We have actually seen this in the lecture. [Lecture 9](http://stat540-ubc.github.io/lectures/lect09_lin_model_III.pdf) covers this, specifically slide 11. 

### Q5 Differential expression analysis with a full model
(Yes! it's almost over. 😅 )
Remember full model means that you're taking the interaction term into account. For 5.1 when explaining the difference in the number of hits, just explain it like how you would when you do research. Think about the meanings behind the models you're using, and try to explore the data a bit by finding the overlapping probes, etc. 

Check out [Lecture 10](http://stat540-ubc.github.io/lectures/lect10_limma.pdf) slide 41 and 42. Make sure, just like the questions before, you specify the coefficient of interest in `topTable()`

Recall what the graphs would look when interaction matters and when they don't matter. You can easily explain the graphs in term of the slopes of the regression lines.

**Comment by rasiimwe** [comment]
Thanks,

This is most helpful

**Comment by santina** [comment]
@STAT540-UBC/students 
Tomorrow we'll go over the assignment Q1-5 and some guidance on the rest of the questions (Q6 - Q8) during the seminar. Feel free to bring questions. :)
