### ISSUE TITLE
Correlation Between Samples

### ISSUE THREAD

**Issue by dakep** [STAT540-UBC/Discussion#155]
@singha53 @ppavlidis , following up on our discussion today about correlation between observations. Here is my (probably ignorant/picky) understanding of the terms covariance and correlation (may it be Pearson's, Spearman's, Kendall's tau, etc.).

To me the covariance is a measure of dependence between two _random variables_ (e.g., pp. 74ff in Härdle (2007), p. 68 in Johnson (2007), or [Wikipedia](https://en.wikipedia.org/wiki/Correlation_and_dependence)). Therefore, in order to estimate the covariance/correlation between two _random variables_, you need multiple realization (observations) of these random variables (i.e., a sample of size _n_) (see, e.g., p. 6 in Johnson (2007), p. 206 in Field (2012)).

If we compute the "covariance"/"correlation" between two observations the way we learned in the course, we therefore make the following assumptions:
* _Person A_ and _Person B_ are two random variables; and
* the measured gene expressions for a single person are _a sample_ of the __same__ random variable.

In other words, we assume that every gene expression is a realization of the __same__ random variable. In our case, this means we treat the expression levels of the different genes as realizations of the single random variable "expression level of person A". I am not sure if that makes biological sense, but maybe it does? This would, however, imply we could also interpret (in a biological meaningful way) the average expression level (across all genes) as something along the line "Person A has an average expression level of XX". Would that be sensible?

### References:
Johnson, R. and Wichern, D. (2007). _Applied Multivariate Statistical Analysis_. Pearson Prentice Hall.
Härdle, W. K. and Simar, L. (2007). _Applied Multivariate Statistical Analysis_. Springer-Verlag Berlin Heidelberg.
Field, A., Miles, J., and Field, Z. (2012). _Discovering Statistics Using R_. SAGE Publications, 4th edition edition.

**Comment by dakep** [comment]
@singha53 I think you make a very important distinction here: we measure some form of _distance_ between two objects (if the _gene expressions are normalized for each observation_, i.e, "person A has on average a gene expression of 0 with variance 1"). But this must not be confused with the correlation in a statistical sense. I think the following two paragraphs from _Podani (2000): Introduction to the exploration of multivariate biological data. Backhuys Publishers._ put it nicely:

"Dissimilarities, distances and – owing to their complementary relationships – similarities have direct geometric interpretability: they express the relative positions of points in the multidimensional space. The next group of functions, on the other hand, will reveal relationships between the axes of the same space, based on the coordinates of points. Examples are coefficients of association and correlation. If the points represent a random sample from a statistical population, then the strength of association or correlation can be tested for significance by methods well-known from univariate statistics. As mentioned [below], these measures can be calculated formally even though the axes are objects or observations, but we should remember that the principle of attribute duality has limited validity in such cases. This is especially true if we wish to apply statistical tests (not discussed in this book)."

"An example is the product-moment correlation coefficient (Equation 3.70), which is meaningful primarily between characters, i.e., variables understood in the statistical sense, because calculation of the mean and the variance is involved. The correlation between two phytosociological quadrats or between two plant individuals, however, is more difficult to interpret, because the mean and variance are unclear for objects. Formally, the formula can be applied to such comparisons: a unit correlation results for two quadrats if the first has, say, twice as much cover of all species than the second. Also, the ‘correlation’ between two plants will be 1 if all size measurements for the first one are a constant times lower than for the second. That is, correlation appears to reflect proportions in size, but something seems to be incorrect when the variance is computed for a plant individual over all of its characters. An additional important difference is that although the correlation of two variables can be tested for significance (provided that the sample is random), the ‘correlation’ of two objects is not testable because the variables that describe them do not represent a ‘random sample’ (see Pielou 1984:8)."

**Comment by singha53** [comment]
@rbalshaw @ppavlidis  what do you think? Can we consider samples as random variables?
@dakep you will find correlations between samples quite often in biological studies considering biological/technical replicates: https://www.google.ca/search?q=strength+of+correlation+between+samples&rlz=1C5CHFA_enCA547CA547&espv=2&biw=1278&bih=740&source=lnms&tbm=isch&sa=X&ved=0ahUKEwij7qSwk7fSAhUY42MKHaKzAWoQ_AUIBigB#tbm=isch&q=correlation+between+replicates&*&imgrc=_

**Comment by rbalshaw** [comment]
There is no mathematical problem with this, though it has always given me a headache.  

My own leaning is to use correlations to measure similarity between variables and Mahalanobis distance (MD) to measure dissimilarity between samples.  But, I grew up in the antiseptic world of independent samples of from multivariate normal distributions.

However, 1 - correlation can be thought of a as a perfectly valid measure of "distance", just as 1/MD could be a pretty sensible measure of similarity.  When we are not worried about calculating p-values (i.e., not trying to quantify their distributional properties), then treating 1- correlation as a measure of distance would be completely reasonable -- and is often done.

**Comment by dakep** [comment]
I completely agree with you @rbalshaw. `1-rho` is a perfectly valid distance measure (if `rho` is Pearson's moment correlation, for rank-based correlations it may be a little harder to think of them as distance, but probably still possible.)

My main concern (and why I brought it up) is that this distinction may not be apparent to some of us students. Especially that you can't interpret and treat this number as a correlation in the _statistical_ sense. I think many of us would be tempted in assignment question 2.2 to statistically compare the estimated "correlation coefficients" as described in many textbooks for statistics, simply because we were not made aware of the distinction.
