### ISSUE TITLE
Additional help if required

### ISSUE THREAD

**Issue by singha53** [STAT540-UBC/Discussion#156]
Hello @STAT540-UBC/students 

Some students asked for additional help. I will be at UBC tomorrow from 4-6:30pm (Data Science Institute Launch Event). We can meet at the Life Sciences Institute at 6:45pm. Anyone else is welcome to join!
Best,
A

**Comment by Nichalle** [comment]
@singha53 Thank you for this! Am I to assume that this is on the main floor of the LSI? or in a room?

**Comment by singha53** [comment]
Apparently there is a job fair here. Im at the job fair.  Lol
