### ISSUE TITLE
Interaction Term in Full Model - Question 5

### ISSUE THREAD

**Issue by nolanshe** [STAT540-UBC/Discussion#157]
Just wondering if for Q5.1, we are supposed to include the interaction term in the "full model" or whether we should only fit a linear model with an interaction term for Q5.2, since the question does not really make it clear.

**Comment by nolanshe** [comment]
Oops sorry, I forgot to tag you guys @singha53 @ppavlidis

**Comment by farnushfarhadi** [comment]
@nolanshe Q5 is about the full model which has both time and treatment as independent variables and also the interaction between them. So it has three coefficients (and an intercept!) in total.

**Comment by nolanshe** [comment]
@farnushfarhadi  Okay so fit it with the interaction term for both Q5.1 and Q5.2. Got it!
