### ISSUE TITLE
lmFit issue Question 3.1

### ISSUE THREAD

**Issue by Nichalle** [STAT540-UBC/Discussion#158]
Just wondering if anyone else has this same issue, I tried to google... but I get lost in a trial of things not working.

When I run this on Rstudio its spits out the answer but when I try to knit it... it says error in eval couldn't find function

**Comment by Nichalle** [comment]
never mind I fixed it , i think

**Comment by santina** [comment]
Remember to have all the packages loaded `library("package_name")` and all the variables defined in your Rmarkdown.
