### ISSUE TITLE
Ordering samples question 2.1

### ISSUE THREAD

**Issue by mccag94** [STAT540-UBC/Discussion#159]
Hi @santina @farnushfarhadi @singha53 , I am still having issues with understanding how to order in R, I have the following for my code. When I run the same code, but order by transcriptome_data$Treatment instead, I am still getting the same heatmap plotted. How do I fix this, and am I even running this correctly?

```{r}
time_order <- transcriptome_data[order(transcriptome_data$time)] # order by time
time_order_mat <- data.frame(t(time_order)) # transpose to correlate by sample
cormat1 <- cor(time_order_mat)
heatmap1 <- pheatmap(cormat1)
heatmap1
```
![image](https://cloud.githubusercontent.com/assets/20196662/23534608/eb826068-ff6d-11e6-8a87-99e21a9167c0.png)

**Comment by santina** [comment]
Hi @mccag94 

Here's an example of using another package. Amrit showed this during the seminar

``` 
library(gplots) # for the heatmap.2 function
library(NMF) # for the aheatmap function

dat <- t(matrix(rnorm(10*10000), nrow = 10, ncol = 10000)) # say this is a 10 samples and 10,000 genes data
heatmap.2(cor(dat)) # A basic heatmap that doesn't have any ordering

# Now say we actually have two factors that we want to order heatmap by
time <- factor(rep(c("Group1", "Group2"), each = 5)) # five Group-1 and five Group2 
age <- 30:39 # number 30 to 39 

# this heatmap has ordering
aheatmap(cor(dat), Rowv = FALSE, Colv = FALSE, 
             annCol = list(Time = time, Age = age), 
             annRow = list(Time = time))

```

Running the code would help you understand what's happening. 

If you want to use pheatmap look at [this post]*https://www.biostars.org/p/108247/)
