### ISSUE TITLE
JB HTML Example 404 Error

### ISSUE THREAD

**Issue by AM-GH** [STAT540-UBC/Discussion#160]
@santina I'm getting a 404 when I try to check out this reference page that you posted - can you please point me in the right direction? 

http://htmlpreview.github.io/?https://raw.github.com/stat540-2014-bryan-jennifer-hw/hw01/stat540-2014-bryan-jennifer-hw01.html

**Comment by santina** [comment]
Where did you see this link?

**Comment by AM-GH** [comment]
https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/subpages/assignment_tips.md

**Comment by santina** [comment]
Oh I see. That kind of link expires after a while. Let me update that markdown.

**Comment by santina** [comment]
Here, updated [assignment tips](http://stat540-ubc.github.io/subpages/assignment_tips.html) 
I basically got rid of the use of html in knitting Rmarkdown. 

The link that was broken was meant to be an example of using README.md to describe the content of your repository. I think people already know how to do that through their project repo through [this rubric](https://stat540-ubc.github.io/subpages/group_project_rubrics.html)

**Comment by AM-GH** [comment]
Thanks!
