### ISSUE TITLE
Practice makes perfect 

### ISSUE THREAD

**Issue by Nichalle** [STAT540-UBC/Discussion#162]
Does anyone remember the name of the website where we can practice how to use R studio, I think it was Ph525 or something....

**Comment by ChristinaMi** [comment]
The R package "swirl" is a great way to learn how to use R. You just install the package in R and choose one of the courses ([click here for a course overview](https://github.com/swirldev/swirl_courses#swirl-courses)).

**Comment by AM-GH** [comment]
Agreed, [Swirl](http://swirlstats.com/) is really helpful. 

Also see: 
1. [DataCamp Introduction to R](https://courses.edx.org/courses/course-v1:HarvardX+PH525.1x+2T2016/info)
2. [StatMethods Quick-R](http://www.statmethods.net/index.html)
3. [Coursera - R Programming](https://www.coursera.org/learn/r-programming)
4. [EdX - Statistics and R](https://www.edx.org/course/statistics-r-harvardx-ph525-1x)

**Comment by AM-GH** [comment]
[Hadley Wickham's](http://hadley.nz/) book **R For Data Science** was also recommended to me. You can [access it online here](http://r4ds.had.co.nz/).

**Comment by jt1013** [comment]
There's also a github repository [here](https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md) for programming
