### ISSUE TITLE
"probe.ids" not found

### ISSUE THREAD

**Issue by oktokat** [STAT540-UBC/Discussion#163]
@santina @farnushfarhadi @singha53 @ppavlidis @rbalshaw 

Hey guys! Working on 6.2 on the assignment and trying to get the gene id's, but I keep getting an error. I copied and pasted this from the instructions into my script:

> source("http://bioconductor.org/biocLite.R")    
> biocLite("yeast2.db")                           # Download the package using biocLite
> library("yeast2.db")                            # Load the yeast2.db package 
> mget("1772391_at", yeast2ORF)                   # See what gene is that probe for 
> gene.ids <- unlist(mget(probe.ids, yeast2ORF))  # See all the genes for the list of probes

but I get this error when I run it:

> Error in mget(probe.ids, yeast2ORF) : object 'probe.ids' not found

Any suggestions? 

Thanks!

**Comment by singha53** [comment]
@oktokat you need to specific what the probe.ids object is. It is a vector of transcript ids (probe set identifiers) which you can get from your expression matrix.
