### ISSUE TITLE
QC / Normalization on DNA methylation using Minfi

### ISSUE THREAD

**Issue by wvictor14** [STAT540-UBC/Discussion#166]
@STAT540-UBC/team-badassays @singha53 @ppavlidis @farnushfarhadi 

Hi STAT540,

We are working on the preprocessing of our DNA methylation data and have some general questions on the order on which we do things with respect to quality control and normalization. In the [DNA methylation lecture 15](https://stat540-ubc.github.io/lectures/lect15_STAT540_Methylation_Presentation%20MJ%20March%202017.pdf), we learned that we do QC (remove bad samples, probes) before normalization. I think the rationale behind this ordering was that you want to remove uninformative / bad quality samples/probes before normalization because they will affect normalization, which intuitively makes a lot of sense.

While it is easy to remove samples before normalizing, removing probes is difficult with the Minfi package. The way the package is set up, to me, suggests that we should remove bad probes after normalization (samples, however are easy to remove before normalization, which I think is a bigger concern). My interpretation is mainly based on the fact that the Minfi brings your data through a series of objects of different [forms](https://www.bioconductor.org/help/course-materials/2014/BioC2014/minfi_BioC2014.pdf) (see page 5-6), and the QC functions take a downstream object (MSet), that is made only by coercion from the rawest form of the data (class: RGset) using a normalization function (or none at all). So you have your raw data and you normalize it into the object that the QC functions exclusively take.

Here is a [post](https://support.bioconductor.org/p/79282/) I found where some is asking how to remove probes before normalization in Minfi and the main developer responds confirming that Minfi is built so that the probe removal is done after normalization. 

Quote:
> But the issue you want to avoid isn't a problem at the step you are trying to avoid it. In other words, you appear to be worried that the methylation data based on probes with SNPs in their sequence or from chromosomes with varying numbers of copies will not be reliable (a valid worry, IMO). But the normalization step is really orthogonal to that worry - at that step all you are trying to do is adjust the distribution of probe intensities from different arrays so they are on comparable scales. Whether or not a given probe is accurately measuring something isn't relevant at that step - you have probes of varying intensity and you want to make those intensities 'similar' across arrays, for some definition of similar.
> 
> So really what you should be doing is processing your data up to the point that you have a MethylSet or GenomicMethylSet and then subsetting to remove data from probes that you don't trust.

So now I think we should do QC before normalization, at least when using Minfi. But I wanted to see if anyone else has any experience with preprocessing DNA methylation that could comment on our thoughts.

Cheers,
Victor
Team Methylation Badassays

**Comment by ppavlidis** [comment]
I agree with the comment you quote. The effect on normalization will be minor anyway (or I'm okay if you assume it is minor, if you can't/don't want to test this yourself).

The main question is whether you should do differential methylation analysis on those "unreliable" probes, that's where you might want to avoid them; especially to the extent that they would cause false positives. That's really what people are worried about (plus multiple test penalties from carrying probes around that are a priori going to be treated as negatives).

Also: I'm not familiar with the details of minfi; but it uses the eSet infrastructure that I've referred to in another discussion here somewhere. Don't feel that using their objects and methods is a requirement all the way through, if you need to "break out" and use another tool, you can.

If a package gets in the way of you doing the analysis the way you want, then it's the wrong package. But let's not overreact -  I don't want you to get bogged down on small issues for this course project.

**Comment by wvictor14** [comment]
Thanks for the quick response,

So I'll take out the probes that I've identified on the normalized data then, and not worry since the effect of keeping those in for normalization is minor. 

Thanks.
