### ISSUE TITLE
heatmap tutorial for R beginners

### ISSUE THREAD

**Issue by AlisonMcAfee** [STAT540-UBC/Discussion#17]
I found this tutorial useful so I just thought I would share:

http://sebastianraschka.com/Articles/heatmaps_in_r.html#customizing

**Comment by AlisonMcAfee** [comment]
Also, I would really like to be able to make the heatmap shown at the end of seminar03b with the samples grouped into "ko" and "wt" chunks... does anyone have input on how to do this?

**Comment by jennybc** [comment]
@aliceZhu @wdurnoUBC has all the heat mapping wisdom / code from 2014 migrated over?

**Comment by wdurnoUBC** [comment]
Heatmap material is in seminar 3b & 3c. I think starting from heatmap.2 is easiest.
http://stat540-ubc.github.io/sm03b_ggplot2.html
http://stat540-ubc.github.io/sm03c_lattice.html
