### ISSUE TITLE
6.2 Question 

### ISSUE THREAD

**Issue by Nichalle** [STAT540-UBC/Discussion#172]
@santina @farnushfarhadi 
Just want a bit of clarification, I found the data set that was swapped and now Im trying to figure out what it is that you want from this question..

I get that you want the probe Id and gene id etc... but is this for every probe? or one random on?

**Comment by santina** [comment]
"Fix the label swap identified in the previous question." means that you want to make sure each column have the right data (i.e. swap it back to fix the sample swap)

so like 

```
c1  c2  b1  b2 
1   2   3   3 
3   4   1   2 
```

if c2 and b1 are sample swap, then make it 

``` 
c1  c2  b1  b2 
1   3   2   3 
3   1   4   2 

```
