### ISSUE TITLE
Images in .md not displaying

### ISSUE THREAD

**Issue by wvictor14** [STAT540-UBC/Discussion#173]
Hi,

Just noticed my images are no longer displaying in the .md file. Not sure what is wrong. Instead of displaying the images in the .md file, a line of code that looks like this appears in place of each image:

![](Analysis_Assignment_P2_files/figure-html/High-volume Scatterplot Matrices-1.png)

I've made sure that I am pushing a .md file. All of the images are in the automatically-created-when-knitted folder. And I've pushed that too. I've deleted and recreated said folder and the images still do not display. 

This is what my directories look like:

zz_yuan-victor_STAT540_2017/Homework/Analysis Assignment P2/
zz_yuan-victor_STAT540_2017/Homework/Analysis Assignment P2/Analysis_Assignment_P2.md
zz_yuan-victor_STAT540_2017/Homework/Analysis Assignment P2/Analysis_Assignment_P2_files/figure-html

All my images are in ./figure-html/

The knitted html file looks fine.

Thanks,
Victor

**Comment by kevinjep** [comment]
Hey Victor,

I had the same problem and @santina helped me solve it today in the seminar. The way that worked for me is to change the output of the RMarkdown file from html_document to github_document. To do so, change the YAML front-matter to:

output: 
  github_document: 

Then when you knit this Rmd file and commit/push it to your repo all the figures should be displayed.

**Comment by wvictor14** [comment]
Nice! Thanks, it worked perfectly. 👍 

Still wondering why the .md file didn't work though. Would be good to know what the problem was.

**Comment by santina** [comment]
@kevinjep  I think it's because you have spaces in the name of your R chunk names. If you name your chunk "High-volume_Scatterplot_Matrices" instead of "High-volume Scatterplot Matrices", for example, I have a strong feeling that it'd solve the problem.

**Comment by kevinjep** [comment]
@santina  I just tried this and you were right... all the figures get displayed when I switch spaces for underscores
