### ISSUE TITLE
Venn Diagram not showing 

### ISSUE THREAD

**Issue by Nichalle** [STAT540-UBC/Discussion#174]
When I run my code I get this

edger.deep.results1 <-read.table('edger.deep.results.tsv', header=TRUE, row.names = 1)
edger.low.results1<-read.table('edger.low.results.tsv', header=TRUE, row.names = 1)
plot.new()
library(VennDiagram)
library(grid)
ven<- venn.diagram(list(RNAdeep = subset(edger.deep.results1,q.value<1e-05)$q.value,RNAlow=subset (edger.low.results1,q.value<1e-05)$q.value, filename = NULL,fill=c('red', 'blue')))

Error in venn.diagram(list(RNAdeep = subset(edger.deep.results1, q.value <  : 
  argument "filename" is missing, with no default

**Comment by santina** [comment]
This section:
```
RNAlow=subset (edger.low.results1,q.value<1e-05)$q.value
```` 
is sort of implying that venn.diagram has this argument "RNAlow" which is not true. 

Also what's 
"list(RNAdeep = subset(edger.deep.results1,q.value<1e-05)$q.value"?

**Comment by santina** [comment]
Example code:

```
# Put all genes in the list where the names will identify each region of the plot
cool_genes <- list(edgeR_deep = edger_deep_genes , edgeR_low = edger_low_genes)
# edgeR_deep and edgeR_low would be the labels in the diagram. 

# Start a new plot
plot.new()
venn.plot <- venn.diagram(cool_genes, filename = NULL, fill = c("red", "blue"))

```
