### ISSUE TITLE
poster example??

### ISSUE THREAD

**Issue by oktokat** [STAT540-UBC/Discussion#176]
@ppavlidis @rbalshaw @singha53 @farnushfarhadi @santina 

Hi everyone! I remember the TA's showing us an example of their final poster in one of the early seminars and I was wondering if we could look at it again/have access to it?? 

Thanks and happy Friday! 
:)

**Comment by singha53** [comment]
@STAT540-UBC/core 

Some poster template ideas [remember the size requirement is 48'' (W) x 36'' (H)]:

1. Research poster templates
https://www.posterpresentations.com/html/free_poster_templates.html#36x56

2. Scientific poster powerpoint templates
http://www.makesigns.com/SciPosters_Templates.aspx

3. Genigraphics
https://www.genigraphics.com/templates

4. others:
https://www.postersession.com/poster-templates.php

**Comment by rasiimwe** [comment]
Thanks Amrit.

This is helpful.

**Comment by santina** [comment]
Hey I emailed two groups from last yeat that I thought had good posters. 

You can find them  [here](https://github.com/STAT540-UBC/solution_repo/tree/master/example_posters)
