### ISSUE TITLE
GitHub organization for projects 

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#177]
@STAT540-UBC/students   😃 

@farnushfarhadi and I would just like to remind everyone the [project rubrics](https://stat540-ubc.github.io/subpages/group_project_rubrics.html), especially the part about GitHub repository. Basically, we ask you to make it easy for us to navigate through your work. That includes 
- Making your repository easy to navigate by giving your folders and files meaningful names.
- Making your analysis easy to follow, using markdown (just like your assignment) to describe the process, with the code and result 
- Putting a README.md file for each folder that describes the content of the folder (i.e. every file in the repository should have a reason to be there). 

If you're not sure how much details to put in, just imagine yourself coming back to this repository a year from now. How much information would you need so that you can reproduce all the work without any confusion? 

@farnushfarhadi anything else you want to add? 

For the posters, [here](https://github.com/STAT540-UBC/solution_repo/tree/master/example_posters) you can find two good posters from last year.

**Comment by farnushfarhadi** [comment]
Two  more things @STAT540-UBC/students :) :

- Please have a summary of all the works in the project in your root README.md file and then you add link to different part of your analysis. So your TA/instructor would see all parts of your analysis once he/she reads through your root README.md file. 

- I realized that most of your figures are generated in the `method/src` folder. But then what is in the `results` folder? you want to add only important figures/tables which are your final results to the `results` folder. Also, if you use external tools such as cytoscape, etc, you can add them into the results folder.

**Comment by santina** [comment]
@STAT540-UBC/students 
We decided that we want to give you until end of the week (Friday night) to organize your repositories, in case you want to incorporate some changes based on the feedback you received today. Thanks! 
Don't forget to fill out the survey from Amrit

**Comment by Nichalle** [comment]
@santina @farnushfarhadi 

does that also make the individual report due on the Friday night? I ask because we have to link things to the repo....

**Comment by santina** [comment]
@ppavlidis I think that make sense?

**Comment by psomdeb25** [comment]
@santina @farnushfarhadi 

Could we have a look at a sample repository from last year, in order to get an idea about how to organize our repository and markdown?

Thanks!

**Comment by rasiimwe** [comment]
Hi,

Kindly confirm the due date of the individual report.

Thanks

**Comment by santina** [comment]
Yes the individual reports are also due on Friday night.

**Comment by santina** [comment]
@psomdeb25 
Here's a nice [team repository](https://github.com/STAT540-UBC/team_treed_rats-DNA-methylation) from last year, though keep in mind that we didn't ask last year's project teams to organize their repositories in certain ways, so the way they organize it might be different from what we wrote in the rubrics.
