### ISSUE TITLE
Transferring ownership of your repositories

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#180]
Hello @STAT540-UBC/students 

The course has come to an end. Before the next semester starts, we gonna have to kick (I mean,  graduate!) all of you from the organization. That means you'll lose access to your private individual repository and group project repository unless I can transfer the ownership to you in the next few days.  

I know some people like the idea of their individual repository being something they can refer back to. Some might want to keep their group repository and make it public so they can show it to others. 

To not lose access, please do the following by April 22: 
- Make sure you already applied for the free micro plan with GitHub if you didn't do that when answering the survey at the beginning of the semester. I think most people have done it. 
>To be able to make your account host private repos for free, you need to tell GitHub that you're a student and upgrade your account to [Micro plan](https://github.com/account/plans). See [this](https://education.github.com/pack/offers) and scroll down to GitHub, obv check out other free developer tools for students :) 
- Open an issue and tag Farnush and/or me in your individual repository or group repository

### For individual repository 
- In the issue, tell us you want your repo and then we'll transfer it to you! **Once that's done, please keep your individual repository private or future students could copy your homework answer and see your grades** 

### For group repository 
- In the issue, let us know which person in the team will take the ownership of the repo (while others still remain collaborators of the repo). By default, I'll give it to whoever has the highest number of commits. It doesn't really matter who owns it anyway. 
- Also, let us know if we can make your repository public and if we could use it as an example group project for next year's students. 

Thanks!  😄

**Comment by rawnakhoque** [comment]
@santina 
How can I get the ownership of my individual repository? And also I do not want to make my individual repository public. Could you please transfer the ownership to me so that I can keep it private. Thanks.

**Comment by rawnakhoque** [comment]
I want the ownership :)

**Comment by santina** [comment]
@rawnakhoque Make sure you apply for the free micro plan with GitHub otherwise I cannot transfer your repository to you.

**Comment by psomdeb25** [comment]
Hello @santina 

I too would like to have access to my private repository. And we would like to have access to the group project repository as well. 

Thanks!

**Comment by vivianlac** [comment]
Hi @santina 

I would like to keep my repo!  Also, I wanted to take ownership of the group repo for Team MetaForest.

Thank you!

**Comment by gjahesh** [comment]
@santina 
I will keep my repo as well as being a collaborator in the group repo.

Thanks!
