### ISSUE TITLE
Update: Looking for 1 more Stats/Compsci/Bioinformatics Member!

### ISSUE THREAD

**Issue by rebailey** [STAT540-UBC/Discussion#187]
Hi guys,

We're currently a group of 3 biologists (all from GSAT) who are looking to add 1-2 more members with some stats, computer science, or bioinformatics background to round out our group. We have Helicobacter pylori sequencing data from Illumina and PacBio that we are interested in using, but we are open to new ideas as well. Let us know if you're interested in joining our group!

**Comment by vicmarza** [comment]
Hi guys, I could provide some experience with analysis of sequence data. Happy to join

Victor

**Comment by rebailey** [comment]
Awesome!

**Comment by rebailey** [comment]
Hi there, we are looking for another member. I'll open up an issue in your repo to give you my email and I can put you in touch with the rest of the group.

**Comment by rebailey** [comment]
If you guys could shoot me an email at edward.bailey@shaw.ca that would be great! Then we can get started on our proposal.

**Comment by rebailey** [comment]
Also, if anyone else is interested in joining we have 4 members as of right now and can take one more (stats or compsci background would be preferred)!
