### ISSUE TITLE
Update: Two neuroscientists with data looking for others to join (from outside of biology?)

### ISSUE THREAD

**Issue by Tristan-Philippe** [STAT540-UBC/Discussion#188]
Hello,

I am doing a PhD in neuroscience. I have gained some experience with R in the last several months, but am by no means an expert. So while I am generally open to anything it would be good to form or join a group with someone in stats, bioinformatics, and/or  computer sciences.

Thanks,
Tristan

**Comment by hydera2** [comment]
Hi! Im doing a masters in Neuroscience. Would love to join this group & see how we can also look at neuroscience data with what we are learning in this course. I also have access to some data that we could possibly use.

**Comment by Tristan-Philippe** [comment]
Hello, That sounds good, I don't have data that we could use so that works.

I guess we still need some stats, bioinformatics, and/or computer sciences people if anyone is interested.

**Comment by Tristan-Philippe** [comment]
As an update I talked with my supervisor and he is also ok with us using my data. So we have two unrelated datasets and could use either or.
