### ISSUE TITLE
Including a package in an rmd file

### ISSUE THREAD

**Issue by hamzakhanvit** [STAT540-UBC/Discussion#19]
Hi,
The dplyr package works fine from the console but shows an error if executed in an rmd file. How should I include it as a package in an rmd file? 
I tried - \usepackage{dplyr} which didn't worked.

Thanks,
Hamza

**Comment by aliceZhu** [comment]
Hey Hamza, did you call library(dplyr) before calling any of its functions? Please come to us during the seminar tomorrow, and we can take a look at the error message.

**Comment by hamzakhanvit** [comment]
It was not working with library(dplyr). I tried require(dplyr) and its working now.
