### ISSUE TITLE
Group Project- Epigenetic profiling of placentas complicated by Preeclampsia and Intrauterine Growth Restriction

### ISSUE THREAD

**Issue by swils6** [STAT540-UBC/Discussion#2]
Hi everyone,
I mentioned this in class today, but I have a dataset with ~100 samples, anexperimental design, completed design matrix, and many scripts to go with it already. 
A bit about the project: These samples have been run on the Illumina Infinium 450K array, which measures DNA methylation. The goal of my project is the characterize the profiles between pregnancy complications: preeclampsia (a maternal hypertensive disorder that is one of the leading causes of morbidity and mortality to mother and baby worldwide) and intrauterine growth restriction (poor fetal growth). Within this analysis I would want to look at the types of genes that show differential methylation and how this is related to the parthenogenesis of these pregnancy complications, and are these pregnancy complications related or distinct entities. 
I am open to people with all backgrounds but would really like help on the programming and statistics aspects of the project, as these are my weaknesses. If you want to talk more about it or have any questions feel free to contact me at swils6@alumni.ubc.ca.

**Comment by IssamLaradji** [comment]
Isn't 100 samples for a dataset too small ?

**Comment by IssamLaradji** [comment]
Also, if you could suggest a paper as a related work it would be great.

**Comment by jennybc** [comment]
I would say 100 samples is arguable quite a lot! What really matters is samples **per condition**, which would be good to document here.

In any case, so glad we are past the n = 1 days!

**Comment by swils6** [comment]
In terms of the conditions we have 20 early onset Preeclampsia cases (diagnosis <34 weeks gestation), 19 late onset preeclampsia cases (diagnosis>34weeks gestation), and 37 control samples. The cases and controls are matched for fetal sex, and their gestational ages are of a similar range, but not matched. This is due to controls mostly beings term pregnancies (with which I have mixed in pre-term due to unrelated causes), compared to EOPE which tends to be delivered much earlier. I anticipate that gestational age will need to be corrected for within the model. 
As this is unpublished data, there is no publication outlining this particular dataset. However, Blair et al (2013) details the cases for Early onset preeclampsia and some of my controls, and a sample of the types of analyses we will be looking into do as part of the project. 
http://molehr.oxfordjournals.org/content/early/2013/06/13/molehr.gat044.short

**Comment by IssamLaradji** [comment]
Sounds like a very interesting project! Thanks for the details.

**Comment by swils6** [comment]
We have one spot left in our group, and would really like some expertise in statistics/programming. Full data set, the preprocessing/Normalization will be done by the first week of Feb, and it will be ready to analyze!

**Comment by tanjahoegg** [comment]
If you guys still have a spot left in your group, I would love to join. I am a PhD student at the statistics department.

**Comment by swils6** [comment]
Do you have time to quickly meet after class?

**Comment by tanjahoegg** [comment]
Sure! Talk to you then.
