### ISSUE TITLE
Problems reading the Homework Assignment Data

### ISSUE THREAD

**Issue by Jameswells96** [STAT540-UBC/Discussion#212]
**Error in gzfile(file, "rb") : cannot open the connection calls**

This error message comes up when I try reading the homework assignment data (the design and matrix data alike) from either the website or from the downloaded files in my own directory.

I've been using readRDS

Online suggestions to fixing this problem just suggests restarting R and reinstalling packages which has not been helpful. 

Let me know if anyone else is having this problem - thanks

**Comment by oganm** [comment]
Can you share the code that lead to this?

**Comment by Jameswells96** [comment]
data = readRDS("C:/Program_Files/R_Access/gse60019_experiment_design.RDS")

**Comment by Zohreh20** [comment]
I got the same error too ! googled it but didn't get any helpful answer.

**Comment by oganm** [comment]
Below is the design data. Use this for now, we can deal with how to fix it in the seminar hour

```
structure(list(sample = c("GSM1463874", "GSM1463872", "GSM1463880", 
"GSM1463879", "GSM1463876", "GSM1463877", "GSM1463884", "GSM1463882", 
"GSM1463888", "GSM1463886", "GSM1463873", "GSM1463871", "GSM1463878", 
"GSM1463875", "GSM1463883", "GSM1463881", "GSM1463887", "GSM1463885"
), organism_part = structure(c(1L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 
1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L), .Label = c("epithelium_of_utricle", 
"sensory_epithelium_of_spiral_organ"), class = "factor"), cell_type = structure(c(2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L), .Label = c("surrounding_cell", "sensory_hair_cell"), class = "factor"), 
    time_point = structure(c(1L, 1L, 2L, 2L, 2L, 2L, 3L, 3L, 
    4L, 4L, 1L, 1L, 2L, 2L, 3L, 3L, 4L, 4L), .Label = c("E16", 
    "P0", "P4", "P7"), class = "factor"), batch = structure(c(2L, 
    2L, 3L, 3L, 3L, 3L, 2L, 2L, 1L, 2L, 1L, 1L, 3L, 3L, 2L, 1L, 
    2L, 1L), .Label = c("HWI-EAS00184", "HWI-EAS00214", "HWI-ST363"
    ), class = "factor")), class = c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -18L), .Names = c("sample", "organism_part", 
"cell_type", "time_point", "batch"))
```

**Comment by missleung** [comment]
I can't seem to download this data set from GEO either...

**Comment by Jameswells96** [comment]
Thanks the design data is accessible with your code. I'm having the same problem with the matrix data, is there another code to access that data?

**Comment by oganm** [comment]
Could you try downloading this and reading it with `dget`?

[expression.txt](https://github.com/STAT540-UBC/Discussion/files/1741662/expression.txt)

I was hoping we could meet earlier to ensure everything works but forgot we don't actually have a seminar this week. Could you confirm that you get true when you do `file.exists("C:/Program_Files/R_Access/gse60019_experiment_design.RDS")` you get a `TRUE`

**Comment by Jameswells96** [comment]
Okay that helps a lot. He used file.exist and found that it wasn't picking up the files in that directory. I moved them directly to the C drive and everything works now.

Thanks!

**Comment by oganm** [comment]
also you should be avoiding using full links. If I try to replicate your work by cloning your repo, I will fail if you use full links.

The working directory of an MD file is where it is located. All your links should be relative to the md file. And ideally you should place your data in the same directory as the md file so you can just do `readRDS("gse60019_experiment_design.RDS'')` or ``readRDS("data/gse60019_experiment_design.RDS'')`` and read the file
