### ISSUE TITLE
Developmental Stage notations (Homework 1)

### ISSUE THREAD

**Issue by missleung** [STAT540-UBC/Discussion#213]
Hi,

I have a question on what developmental stage means...and I was wondering if P0 = at birth, P4 = 4 days after birth, P7 = 7 days after birth, and etc..?

Thanks,

Lisa

**Comment by sofiaromeriana** [comment]
day or week?

**Comment by oganm** [comment]
Day. Note that you can double check the metadata by looking at the samples at GEO.

For instance [GSM1463883](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1463883)
