### ISSUE TITLE
Error from findNearestGene

### ISSUE THREAD

**Issue by WalterWasserman** [STAT540-UBC/Discussion#228]
Hello,

When I follow the seminar code exactly, I am ending up with an error from the following `getNearestGene` call:

```
hm450 <-  getPlatform(platform='HM450', genome='hg19')
probe_UCSC_name = getNearestGene(hm450)
```
The error is  "Error in as_mapper(.f, ...) : argument ".f" is missing, with no default". 

Looking into the full traceback below, it seems to be an internal issue with the function?

Error in `as_mapper(.f, ...)` : argument ".f" is missing, with no default
6. `as_mapper(.f, ...)`
5. `reduce_impl(.x, .f, ..., .init = .init, .left = TRUE)`
4. `reduce(grl)`
3. `unlist(reduce(grl))`
2. `getNearest(probes, "gene")`
1. `getNearestGene(hm450)`

Interestingly, `getNearestTSS(hm450)` and `getNearestTranscript(hm450)` work just fine.

I would appreciate any ideas on what to look into further for this, or if it is simply an issue within the package (in which case this seems non-trivial to fix).

**Comment by eneskemalergin** [comment]
Hello, I am not sure if you call the library tidyverse as a whole. Since package purr has a function called [reduce](https://www.rdocumentation.org/packages/purrr/versions/0.2.4/topics/reduce) that might be cause the problem. 

Only call ggplot2 library, and not tidyverse. That should solve it.

**Comment by WalterWasserman** [comment]
That seems to have fixed it - thanks!
