### ISSUE TITLE
seminar 4a

### ISSUE THREAD

**Issue by AlisonMcAfee** [STAT540-UBC/Discussion#23]
Feeling stuck with this seminar... I think that what I need to do is write a 'for' loop that will perform a t-test on, say, expression data for gene[1] with gene[2], then with gene[3] etc until the end of the list. Then repeat for gene[2] with gene[3], then with gene[4], etc. until all combinations have been tested.

I just don't understand the 'for' syntax well enough to write this myself! Could anyone help? 

Thanks!

**Comment by aliceZhu** [comment]
Hey Alison, are you referring to the take-home question of 4a? It's probably easier and faster to do it with the data aggregation methods (some aggregation method can be found in 4b).

**Comment by AlisonMcAfee** [comment]
Hmm thanks! prior to this I was only familiar with procedural programming... so the loop method is easier for me to grasp. I see that someone has used a combination of the 'combn' function and something similar to what I described above... 

Sometimes I feel like the seminars should come in different orders? 

Cheers

**Comment by aliceZhu** [comment]
I think it's feasible to achieve the question by only data aggregation approach (hopefully, :D), and I will try to post my own version on Wed. Yeah, I see what you mean for the order issue, and sometimes we do find it hard to order them as everyone comes with different prior background.  But for the future seminars, we will add links to cross-reference the resources that contained in different seminars, hope that helps :)
