### ISSUE TITLE
Seminar 7 - error message getNearestGene(hm450)

### ISSUE THREAD

**Issue by mylinhthibodeau** [STAT540-UBC/Discussion#230]
Dear @oganm , dear @emmagraham , dear @janstett ,

I am getting the following error message when trying to use the getNearestGene() function:

```
> hm450 <- getPlatform(platform='HM450', genome='hg19')
Fetching coordinates for hg19...
> probe_UCSC_name = getNearestGene(hm450)
Error in as_mapper(.f, ...) : argument ".f" is missing, with no default
```

Would you be able to help me out by any chance?

Thank you for your time !

My Linh

**Comment by WalterWasserman** [comment]
So this looks like the [issue](https://github.com/STAT540-UBC/Discussion/issues/228) that I posted a little while ago - the solution for me was to not import `tidyverse`, since the tidyverse ends up masking a required function. (If you want ggplot, directly importing `ggplot2` seems to work)

**Comment by mylinhthibodeau** [comment]
Thanks !
