### ISSUE TITLE
Stone cell group - details

### ISSUE THREAD

**Issue by tshalev** [STAT540-UBC/Discussion#24]

**Comment by ivanhartling** [comment]
I am in the Applied Animal Biology program and am in Ronaldo Cerri's lab. My research interests and expertise are on vitamins and metabolites in dairy.

**Comment by cronie1** [comment]
I'm in Dr. Jae-Hyeok Lee's lab in the faculty of Botany, where we study Chlamydomonas algae. I have a strong background in plant genetics and genomics, and my academic interests include plant biochemistry, biofuel engineering, and GMOs.

**Comment by jkbooth** [comment]
I'm a second year student in the GSAT program. I'm doing my thesis in the Bohlmann lab, which focuses on plant secondary metabolism. I'm interested in the role of genetics in plant metabolism, and the role of metabolites in flavour and aroma. My thesis is on terpene production in Cannabis sativa.
