### ISSUE TITLE
Need help understanding unbiased activation of T cells

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#25]
So I read this paper (http://www.sciencemag.org/content/345/6202/1254665.full) which says in the abstract,
"We analyzed gene expression in CD4+ T cells during unbiased activation or in T helper 17 (TH17) conditions from 348 healthy participants representing European, Asian, and African ancestries."

What does "unbiased activation" mean ? is that an activation done to the gene expressions without any stimulants ?

Thanks!

**Comment by kmnip** [comment]
That's referring to the "unbiased" activation of the CD4+ T-cells, not the activation of gene expression (although the activation of CD4+ T-cells does activate certain genes!!!).

I think this should clarify what "unbiased" means:
http://www.sciencepubs.org/content/345/6202/1254665?related-urls=yes&legid=sci;345/6202/1254665

>As the third arm of the ImmVar project, we performed a rigorously controlled analysis of the responses of human blood CD4+ T cells to **activation in unbiased conditions or in a culture regimen that promotes differentiation to the T helper 17 cell (TH17) phenotype**.

Hope that helps! :)

Ka Ming
