### ISSUE TITLE
Not getting invitation email 

### ISSUE THREAD

**Issue by yidie** [STAT540-UBC/Discussion#266]
Hi TAs @shamsbhuiyan @Jwong684 @jafarzadeh91,

This is Yidie Feng (#50425131). I completed the survey yesterday and haven't got the invitation email. My GitHub username is yidie. Can you look into this?

Thanks,
Yidie

**Comment by jafarzadeh91** [comment]
done.

**Comment by yidie** [comment]
Thanks!
