### ISSUE TITLE
Looking for project team members (You do not need to have data!)

### ISSUE THREAD

**Issue by urmysun** [STAT540-UBC/Discussion#267]
Hello All,
Shuxian (@ShuxianFan) and I are looking for 2 project team members ~~with data~~ to form a project group.
Shuxian is an M.Sc. student from the Department of Statistics. She finished her undergraduate program in UBC Statistics. She has been doing research work related to Vaccine study and forest products stochastic modeling.
I (@urmysun) am an M.Sc. student from the Department of Medicine. I obtained my B.Sc. from UBC Computer Science and Statistics. I have been working on several machine learning research projects including clinical data mining, neuroimage deep learning (sMRI & fMRI), and multimodal learning (video, sound, language).
~~Unluckily, our labs cannot provide proper data for the project, thus we are looking for someone **with data**.~~
Update: We can use some public dataset.
We intend to find at least one member with some biology background. If you hope to know more about us, please reach us by facebook messenger (Xiang Liu) or email (shuxian.fan@stat.ubc.ca).
Hope everyone could find a nice group!

Shuxian & Xiang

**Comment by vpichler** [comment]
Hi Shuxian and Xiang,
I am a first year PhD student studying infectious disease genomics in the Department of Microbiology and Immunology, with a biology background from both my undegrad and masters. I have not yet generated any data, so I would be happy to jump on your group.
Ginny (@vpichler)

**Comment by antjak** [comment]
Hi Shuxian & Xiang,

I am an undergraduate exchange student from Switzerland (EPFL) studying Biomedical Engineering, with a background in biology (courses and lab experience) and machine learning (I am also taking CPSC 540 this term, which is precisely about machine learning). I would be happy to join your group! You can shoot me an email if you have any questions (anthony.jakob@alumni.ubc.ca).

Anthony (@antjak)

**Comment by parashloya** [comment]
Hi Shuxian & Xiang,
I am M.Eng. student in Chemical and biological engineering and have a biotechnology background. I have completed courses like recombinant DNA technology, bioinformatics, cell biology, etc.
I am seeking people with statistics background and would be happy to be a part of your group.
You can mail me at loya.parash@gmail.com

**Comment by urmysun** [comment]
Update: We've formed a group.
