### ISSUE TITLE
Warm-Up Assignment Link?

### ISSUE THREAD

**Issue by dirediredock** [STAT540-UBC/Discussion#268]
I can't find a link or page with material for the Warm-Up assignment due Wed 16 January 2019. Is it not up yet? Cheers!

**Comment by ys-sherry-sun** [comment]
I think it's the practice_assignment.md with the guinea pig data, but not sure.. would need a TA to confirm this

**Comment by urmysun** [comment]
According to https://stat540-ubc.github.io/subpages/assignments.html, it should be https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/homework/practice_assignment/practice_assignment.md.
Hope this helps.

**Comment by wilcas** [comment]
Can confirm this is the assignment location.

**Comment by ecool50** [comment]
@wilcas  I have filled out the survey but still have yet to receive an invite? Do you know when the invites will be sent out?

**Comment by wilcas** [comment]
@jafarzadeh91 will create your repo

**Comment by jafarzadeh91** [comment]
Done.
