### ISSUE TITLE
Looking for project group members (Synovial Sarcoma Epigenomics)

### ISSUE THREAD

**Issue by alvin-q** [STAT540-UBC/Discussion#269]
Hi my name is Alvin and I'm a 3rd year student in the combined MD/PhD program at UBC. My host department is Interdisciplinary Oncology. My undergraduate degree was in Anatomy & Cell Biology at McGill.

I'm looking for group members for a project. I have some public datasets that I would like to use for the project about synovial sarcoma epigenomics. These are primarily **RNA seq and ChIP seq data** from **synovial sarcoma** cell lines.

Synovial sarcoma is a soft-tissue malignancy that primarily affects adolescents and young adults. The goal is to hopefully find something revealing about synovial sarcoma biology and ultimately bring discoveries into clinic to improve patient outcomes.

A short snippet of my research interests can be found on my G+PS profile [here](https://www.grad.ubc.ca/campus-community/meet-our-students/qiu-alvin).

Let me know if you're interested!

**Comment by joycez14** [comment]
Hi Alvin, we have a group of 3 people here needing one extra member. I am in pathology with David Huntsman, Kate is in IOP with Andrew Weng, and Rose is in Biochemistry with Dieter Bromme. Two of us are in the cancer field (ovarian, leukaemia). Also we are thinking of using public data set since we don't think we are allowed to use our own. If you are interested please let us know!

**Comment by nknoetze** [comment]
Hey Alvin, I would be interested in joining you. I am a bioinformatics student in the Master's program, and therefore have experience in R and data analysis. My projects are also based on cancer research as well. Let me know if you're interested!

**Comment by ShuxianFan** [comment]
Hi Alvin, we have a group of 2 people now looking for non-statistical background teammates! We planned to use public data too. I am M.Sc. student from the Department of Statistics. I have been doing research work related to Vaccine study and forest products stochastic modelling. @urmysun is M.Sc. student from the Department of Medicine. he obtained B.Sc. from UBC Computer Science and Statistics. He has been working on several machine learning research projects including clinical data mining, neuroimage deep learning (sMRI & fMRI), and multimodal learning (video, sound, language). Please let me know if you would like to meet us and discuss the project!

**Comment by alvin-q** [comment]
I've already started downloading some of the data from these 2 papers:
[https://www.cell.com/cancer-cell/fulltext/S1535-6108(18)30184-3](https://www.cell.com/cancer-cell/fulltext/S1535-6108(18)30184-3)
[https://www.cell.com/cancer-cell/fulltext/S1535-6108(18)30018-7](https://www.cell.com/cancer-cell/fulltext/S1535-6108(18)30018-7)

If anyone is remotely interested in this data, I'd be super keen to do the group project with it.

**Comment by joycez14** [comment]
Hi Alvin, I just chatted with my group they are okay with using the dataset. We can start reading the paper and doing some exploratory analysis in the mean time. Let us know if you want to chat / meet in person to discuss the 2 papers and the data.

**Comment by nknoetze** [comment]
Hi Alvin, I'd be happy to work on this project with you. We can talk on Wednesday if that works.

**Comment by alvin-q** [comment]
Hi thanks for the interest. I decided to join the group of 3 with @joycez14 .
