### ISSUE TITLE
eBayes

### ISSUE THREAD

**Issue by chainikonwar** [STAT540-UBC/Discussion#27]
@gcohenfr  @jennybc 
Apart from the moderated t-statistic, the eBayes() function also gives a F-statistic, is that relevant? Does it test that the contrasts are not equivalent to zero for a gene (whether the gene is differentially expressed on any contrast)
Out of curiosity, just wanted to know whether eBayes is the only way to moderate the variance?

**Comment by gcohenfr** [comment]
@chainikonwar, not sure why you've closed this issue. These are interesting questions. eBayes is the only way to moderate the variance within LIMMA. Other methods have been proposed in the literature. LIMMA is a well known and commonly used, thus we cover it in the course. G

**Comment by chainikonwar** [comment]
@gcohenfr Thank you for getting back on this. I was able to figure out some of the answers before anyone got back to me, so thought to close it.
