### ISSUE TITLE
Looking for team members

### ISSUE THREAD

**Issue by vpichler** [STAT540-UBC/Discussion#272]
Hi All.

My name is Ginny (@vpichler) and I am a first year PhD student studying infectious disease genomics in the Department of Microbiology and Immunology, with a biology background from both my undegrad and masters. Since my forte is biology, I'm looking for at least one team member with a stats background to balance the skills. I have not yet generated data in my research, so I'm flexible to pull public data or jump on any you have in mind. 

Feel free to send me an e-mail if you have any questions.
virginia.pichler@bccdc.ca

**Update: looking for one team member with stats background or related**

**Comment by vpichler** [comment]
Hi Yao and Anthony,

Thanks for getting back. Since we're all bio people, I think our fourth member should belong to stats (or related) and combined with Yao's stats/machine learning experience, we should be fine to form a team. 
I will update the issue.

**Comment by vpichler** [comment]
If everyone's on board, we can meet today at the seminar. I attend the 12 PM session, but if you go earlier, we can meet at the transition. You can spot me wearing black pants and an orange coat.

**Comment by vahidAK** [comment]
I am Vahid (@vahidAK). I am a PhD student In medical genetics. I have already worked with gene expression data and have some ideas if you are interested. As well as, I am open to new ideas. Please let me know if you are interested.

**Comment by UnaCorda** [comment]
> If everyone's on board, we can meet today at the seminar. I attend the 12 PM session, but if you go earlier, we can meet at the transition. You can spot me wearing black pants and an orange coat.

Hi Ginny,

This is Yao. I'm so sorry I didn't see your post and I'm thinking of joining another group now. I just found out that friends in my department are taking this class. I'm thinking of joining them since we can get together more often.

Thank you so much for your time. I'm so sorry about that. Please don't keep the spot for me.

Yao
