### ISSUE TITLE
Looking for group Group to be included

### ISSUE THREAD

**Issue by vahidAK** [STAT540-UBC/Discussion#273]
Hi,
My name is Vahid (@vahidAK ), I am a first year Ph.D. student in medical genetics. I have some experience with R and working with expression data and I have some Ideas for the group project. Please let me know if you need a member for your group or you interested in to make a new group.
Thanks.
vahid.akbari1369@gmail.com

**Comment by racheldunn** [comment]
We have a group of 3 (one pathology, one biostats, and one stats) and some ideas for datasets to use.   We will send an email and see if we can meetup and discuss details further.
