### ISSUE TITLE
3 students with diverse backgrounds need 4th group member

### ISSUE THREAD

**Issue by yflim** [STAT540-UBC/Discussion#274]
I'm Erica @elileger: I'm in the Cell and Developmental Biology MSc program, open to working with any kind of data! I work with C. elegans and have a background in molecular biology and genetics.
I'm Yee Fay, @yflim: 2nd-year bioinformatics MSc student, experienced coder comfortable with probability, some statistics, and elementary (and maybe fancier) data analysis; worked with TCGA data recently. I have some project options that could be put to use but am eager to explore other possibilities.
Our third group member, Bronwyn, is in medical genetics and will comment later.
We're seeking a fourth group member, ideally someone in statistics or with similar expertise.

**Comment by bposynick** [comment]
Hi everyone! As Eric said, I'm Bronwyn @bposynick and am in my first year of a MSc in Medical Genetics. My background is in biochemistry, and I have very basic experience with R and Python. My work is all wet-lab right now (I work mostly with mammalian cell culture), although I will possibly be working with gene expression data in the future, and so would love to play around with that kind of data for our project (but am open to other options as well).

**Comment by vahidAK** [comment]
Hi,
My name is Vahid. I am Ph.D. student in Medical Genetics, I have some experiences with R, and Transcriptome data analysis and have some Ideas for the project if you interested.
vahid.akbari1369@gmail.com

**Comment by yidie** [comment]
Hi everyone @yflim @bposynick @elileger,

I am Yidie, a second-year master student in statistics. Are you still looking for a stat person? If so, I would like to join!

**Comment by yidie** [comment]
Hi @bposynick 
Thanks for the quick reply. I am available to meet around noon. By the way, do we have a group chat or something similar?

**Comment by elileger** [comment]
Hi @yidie, we'll meet at noon in the LSI atrium with the round tables (next to Cafe Perugia). We've started a WhatsApp group chat so I can add you if you send me your number. Cheers!

**Comment by yflim** [comment]
Group formed.
