### ISSUE TITLE
Many repositories need work

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/Discussion#28]
Hi all, I visited your repositories today. If I did not open an issue is because your repository is fine. If I did, review it and work on the suggested points. By now, we expect you to: 

* have a nice readme file that organizes the content of your repository (you can also introduce your self here and/or add links to other pages that describe you outside STAT450).  
* show work and commitment: show work on seminar content and take home problems
* know how to commit/push to your private GitHub repository in STAT540-UBC organization account

I did not review your work at seminars. TAs will work on that and you should also open issues in the Discussion repository if you need help or want to share a cool thing you've learned.

**Comment by kmnip** [comment]
@wdurnoUBC @aliceZhu Would you like us to commit our work on the exercises in addition to our solutions to the homework problems?

**Comment by aliceZhu** [comment]
For the exercise, it would be nice to try at least half of them, especially the ones that you find challenging.
