### ISSUE TITLE
Looking for 4th (non-stats) team member

### ISSUE THREAD

**Issue by vpichler** [STAT540-UBC/Discussion#280]
Hi All,

We're a 3-member group looking for a fourth.

Ginny (@vpichler) is a first year PhD student studying infectious disease genomics in the Department of Microbiology and Immunology, with a biology background from both her undergrad and masters degrees.  

Anthony (@antjak) is an exchange student from Switzerland (EPFL) in Biomedical Engineering with a background in biology and knowledge of machine learning.

Yanchao is completing a MSc in the Stats department. 

We were recently asked to split up our four-member team since we had two stats people, so any other background will work.  We're open to data ideas and could pull from public sources. 

Feel free to shoot an e-mail too at virginia.pichler@bccdc.ca

**Comment by changbenson** [comment]
Hi I'm Benson Chang @changbenson, an MSc Genome Sciences and Technology student specializing in biotechnology and biological engineering. If you're available to have me as your fourth member, I'd be happy! My email is chang_benson@hotmail.com.

**Comment by vpichler** [comment]
Hi Benson,

Sounds like a good fit -- welcome to our team! I'll send you an e-mail with some more details.
