### ISSUE TITLE
CLOSED: Looking for one NON-Stats person

### ISSUE THREAD

**Issue by janxue** [STAT540-UBC/Discussion#285]
Hi All,

We're a 3-member group looking for a fourth.

Jessica is a first year MSc student in the Department of Oceanography, with a biology background.

Jan s a first year MSc student in the Botany, with a biology background. 

We have one other stats student.

We were recently asked to split up our four-member team since we had two stats people, so any other background will work. We're open to data ideas. We also are thinking of looking at parental and offspring data looking at hybrid vigour (aka. hybrid child produces bigger) broccoli using transcriptomic and methylomic data publicly available.

@janxue
@j-schaub
@garyzhubc
@glenn-mcguinness

**Comment by janxue** [comment]
Cool, would you want to skype and chat about it? My email is jiany23@hotmail.com and you can send me your Skype name?


_____________________________

**Comment by parashloya** [comment]
I cannot skype today but we can definitely discuss tomorrow.

**Comment by janxue** [comment]
Yo you want to meet after class? I am wearing a pink scarf with flowers on it.

________________________________

**Comment by parashloya** [comment]
Sure

**Comment by ymkng** [comment]
Hi are you still looking for a group member?

**Comment by janxue** [comment]
looking for one non-stats group member, yes. You interested?
________________________________

**Comment by ymkng** [comment]
hi yes! My name is Michelle I am in bioinformatics with microbio and compsci background and I am interested in joining your group :)

**Comment by janxue** [comment]
Cool you on campus and want to meet? Email me at jiany23@hotmail.com

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ymkng** [comment]
@janxue emailed you! on campus and can meet wherever :)

**Comment by janxue** [comment]
found person --> closing issue

**Comment by janxue** [comment]
@parashloya, we found someone, please look for another group
