### ISSUE TITLE
Uncertainty about Data Requirements

### ISSUE THREAD

**Issue by bposynick** [STAT540-UBC/Discussion#290]
Hi @shamsbhuiyan  @Jwong684  @jafarzadeh91 

I'm in a group with @elileger @yidie @yidie

We have some questions about what kind of data is needed for our project - and figured that other people might as well. 

We are thinking about maybe using data from a [C. elegans paper](http://www.genetics.org/content/210/1/263). They have raw (?) [RNA-seq counts](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE113500) for each sample and then [pooled data comparing different conditions](https://figshare.com/articles/Supplemental_Material_for_Webster_et_al_2018/6510158) (in File_S1), but I'm not sure if this is data we could use: I don't think they share their normalized data from each sample. Could we normalize it ourselves? Could we use the data from their analyses? We would most likely want to look at KEGG-style analysis to see where differentially-expressed genes cluster, and so technically we could use their analyzed data, but we would lack information such as the distribution of the raw data.

Could you shed some light on what an "ideal data set" (or an ideal RNA-seq data set) would include? 

Thanks!

(We are also unclear about what the scope of our project is/how big it should be - will this be discussed in seminar?)

**Comment by ppavlidis** [comment]
The raw gene-level count data you mention (referring to the supplementary file on GEO https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE113500&format=file) is what you want. Using "normalized" data (as typically defined) is a step further than what you'd need to run methods like limma-voom or edgeR, and we also encourage groups to work with data prior to normalizing - you can (and should) do those parts yourself.

At first (very superficial) glance this seems like a good basis for a group project: decent sample size, reasonably complex (variables include time and feeding), so several options for analyses and visualization. In terms of scope, you should endeavor to do something a little different and go beyond what they do in the paper. It can be informative to try to reproduce their results, so feel free, but typically groups do something more. And you should include QC as part of your project - basically, treat it like new data.

I hope that helps!
