### ISSUE TITLE
Seminar 3 - outputs differ from those depicted in tutorial materials

### ISSUE THREAD

**Issue by tfsevers88** [STAT540-UBC/Discussion#292]
On working through the tutorial for seminar 3, I find that the tibble I produce corresponding to the one just above Part 3, containing the columns "disease" and "mean", has different values than the one shown in the tutorial. (I'm getting a "normal" mean of 735.8 instead of 682 and "RCC" mean of 770.5 instead of 658. Note that not just the values, but their magnitudes with respect to each other have changed.) Additionally, the figure I generate in part 3 is quite different (in spite of using the same set.seed value) - instead of genes with highest counts being associated with chromosome 1, they are now associated with chromosome 12.

@Jwong684 @jafarzadeh91 @shamsbhuiyan It looks like biomaRt is updated frequently, so I'm thinking the discrepancy is due to annotation changes? (I don't see any typos or skipped steps.)

**Comment by ShuxianFan** [comment]
Hi, I got very similar numbers to those that TA had. Hope they can confirm that the result is related to the biomaRt updating. 

A tibble: 2 x 2
disease  Mean
1 normal   684.
2 RCC      657

**Comment by jwhite94** [comment]
@tfsevers88 I received the same results for the "normal" and "RCC" means. I assume we got similar p-values and final graphs as well.

Either we are both doing the same thing wrong, or it has something to do with a biomaRt update? Hopefully we can sort this out in seminar tomorrow.

**Comment by jafarzadeh91** [comment]
Hi guys, just to make sure: Did you use the exact code mentioned in the seminar or the code that is modified with adding the "transcript_length". 
The latter case can make the results wrong because some genes have multiple "transcrip_length" you are basically calculating them multiple time in the process and it imposes biases.

**Comment by wilcas** [comment]
Hi all, 
I can answer some of your questions. As for the mean issue, the answer should be close to @ShuxianFan. @tfsevers88 : As for the image, it appears that the updates I made to the seminar 3 Rmd (which add in a seed so you could reproduce the plot), were overwritten around 20 days ago. The current version of the seminar linked on the website corrects this.

Best,
Will

**Comment by tfsevers88** [comment]
The Part 2 Exercise section said to modify get the transcript lengths at the beginning, and the code to generate the tibble came later, so yes, I used the modified data frame! After Will updated the markdown, if I remove the “transcript_length” from the attribute vector, I get the same answer as in the seminar.

**Comment by jafarzadeh91** [comment]
One quick note: 
There is a caveat here: A gene can have multiple "transcription_length" (aka. alternate splicing), so when you add that new column of "transcription_length", you end up with a matrix with different (sample, gene, disease) triples, each one of multiple frequencies depending on the number of transcriptomics discovered for each gene.
In this way, we incorrectly influence the mean count as you have faced in the seminar.
Please use the data without adding the "transcriptom_length" all through the seminar and you will end up with the same results as we depicted.

We have been a little unclear in the seminar description, sorry for that. I am going to modify the seminar description the reflect these changes.
