### ISSUE TITLE
Group project - Allergic asthma inhalation challenge study

### ISSUE THREAD

**Issue by yyolanda** [STAT540-UBC/Discussion#3]
Hi everyone,

I have got a microarray dataset which contains 28 samples and around 22000 genes. In this dataset, 14 participants with mild allergic asthma underwent an allergen inhalation challenge. Their peripheral blood was collected prior to and 2 hours post allergen challenge. Two phenotypes are involved in the study: an individual with only the early allergic response is classified as an early responder (ER) while an individual with both the early allergic response and the late allergic response is classified as a dual responder (DR). Expression profiling was performed using Affymetrix Human Gene 1.0 ST arrays. Demographics including personal information, leukocytes counts etc. of the participants are also available. Since we have already got publications on this dataset, we can get very detailed information regarding this dataset. Differential expression analyses like (pre samples vs. post samples, ER samples vs. DR samples at different stages of challenge etc.) has already been done. We can also look at the dataset with other approaches to further characterize the differences between different phenotypes of asthmatics and different stages of allergen inhalation challenge. In addition, different methods of normalization can be worth to have a try. (Or we can discuss about what we can do later.) 

So far, we have 3 people in our group all coming from bioinformatics: Naman, Hamza and me (Yolanda). We would really like to get some help from statistic people as we don't have strong statistical backgrounds but we are also glad to get anyone who is interested in this dataset! I have already got some R scripts and a shiny app based on this dataset from my STAT545 homework. You are welcome to play with my AsthMA app [here](https://yyolanda0507.shinyapps.io/AsthMA-app/). Further information about the dataset can be found in this paper: ["Th17/Treg ratio derived using DNA methylation analysis is associated with the late phase asthmatic response" (PMCID: PMC4078401)](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4078401/).

This is just a suggestion and I'm also happy with other datasets if available. 
Feel free to leave a comment below or contact me at y.yolanda0507@gmail.com  =)

Yolanda

**Comment by namanpaul** [comment]
Hi Yolanda,
We even have Akiff (Comp Sci), on board with us!

Naman

**Comment by yyolanda** [comment]
@namanpaul Great to know!

**Comment by yyolanda** [comment]
@namanpaul @hamzakhanvit  @amanji  Hey guys, Max @maxala from biomedical engineering is thinking of join us. Do we still have an open spot?

**Comment by amanji** [comment]
Yeah we only have 4 people, so one more would be great

On Mon, Jan 26, 2015 at 9:35 AM, yyolanda <notifications@github.com> wrote:

> @namanpaul <https://github.com/namanpaul> @hamzakhanvit
> <https://github.com/hamzakhanvit> @amanji <https://github.com/amanji> Hey
> guys, Max @maxala <https://github.com/maxala> from biomedical engineering
> is thinking of join us. Do we still have an open spot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAT540-UBC/Discussion/issues/3#issuecomment-71501392>
> .
>



-- 
BSc. Cell Biology and Genetics (UBC)

**Comment by namanpaul** [comment]
Yes! We can definitely give it a shot. Let's talk to her after the class.

-Naman

**Comment by namanpaul** [comment]
What about Olivia's dataset? We should see, if we can find AT LEAST one person from STATS!

**Comment by yyolanda** [comment]
@namanpaul @hamzakhanvit @amanji Let's discuss a little bit after class outside the classroom!

**Comment by yyolanda** [comment]
@basienka Hi, would you like to join our group? =)

**Comment by basienka** [comment]
Yes I would! Do you still have room?

**Comment by yyolanda** [comment]
@basienka That's great! We curretly have 5 people in our group, but we think 6 people is still fine! We will have a brief meeting at 6pm tmr(Thur) outside our seminar classroom. I don't know if you are available at that time? And welcome to join us! =)

**Comment by yyolanda** [comment]
@namanpaul @hamzakhanvit @amanji  @maxala Hey guys, great that Basia is joining us!

**Comment by basienka** [comment]
Yes, I'm available at that time, I'll see you there! We should also ask to make sure that the 6 members would be ok :)

**Comment by maxala** [comment]
Awesome! And btw I think it's going to be more than a brief meeting because we have to finish our proposal to Friday!

**Comment by yyolanda** [comment]
@namanpaul @hamzakhanvit @amanji @maxala @basienka Great! I'll have a draft done before tmr's meeting so that we can save some time =) I just emailed Gaby about the group size and will keep Basia posted.

**Comment by gcohenfr** [comment]
6 members is possible. However, if there is another group with short numbers, I may need to move one of you.

**Comment by yyolanda** [comment]
@gcohenfr Thank you Gaby! @basienka I'm so sorry Basia, it seems that we cannot be in the same group.. :(

**Comment by gcohenfr** [comment]
Given that Basia is the only one from Stat in that group, I would like 
her to stay in the group. If I need to pull somebody, I will need 
another volunteer. Hope not

G

**Comment by yyolanda** [comment]
@gcohenfr Yes, we do value Basia @basienka, who is from stat, as an important member of us..hope that we can have everyone if possible! =)

**Comment by namanpaul** [comment]
@yyolanda @amanji @hamzakhanvit @maxala @basienka 
Please confirm, our discussion location and time for today: Earth Sciences building, at 6?

**Comment by yyolanda** [comment]
@namanpaul Yes, that's right!

**Comment by maxala** [comment]
@namanpaul Yep!
