### ISSUE TITLE
Choosing intercept

### ISSUE THREAD

**Issue by mas29** [STAT540-UBC/Discussion#30]
I think we went over this in class, but I can't recall the answer -- 
How do we choose which group is taken as the intercept for the linear model?

**Comment by kmnip** [comment]
Unless I am missing something, doesn't each group has their own intercept?

alpha<sub>0,wt</sub>
alpha<sub>0,ko</sub> = alpha<sub>0,wt</sub> + tau<sub>0,ko</sub>

**Comment by aliceZhu** [comment]
The intercept is the theta, the reference point on the plot where Gaby drew on the whiteboard during class. So it's your choice to set what it is.

**Comment by wdurnoUBC** [comment]
If you are unsure about what model you are fitting, try using model.matrix() to see your design matrix. For example, if you wanted to fit the model
```
y ~ x1 + x2 
```
your could see the design matrix via the following command
```
model.matrix( ~ x1 + x2 )
```

**Comment by mas29** [comment]
Ok, so I would just write a contrast matrix if I wanted the intercept to be using a different developmental stage, for instance?

**Comment by wdurnoUBC** [comment]
I think we've been answering the wrong question. For factors, R puts the first level in the intercept. You can change which level is first with "relevel". Here's an example which changes "b" to the intercept.

```
# y = rnorm(120) ; x = as.factor( rep( c("a","b","c") , 40 ) )
# summary(lm(y ~ x))
# x = relevel( x , ref=2 )
# summary(lm(y ~ x))

> y = rnorm(120) ; x = as.factor( rep( c("a","b","c") , 40 ) )
> summary(lm(y ~ x))

Call:
lm(formula = y ~ x)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.3284 -0.6325  0.1383  0.6846  2.7796 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)   0.3119     0.1733   1.800   0.0744 .
xb           -0.4673     0.2451  -1.907   0.0590 .
xc           -0.3706     0.2451  -1.512   0.1332  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.096 on 117 degrees of freedom
Multiple R-squared:  0.03347,	Adjusted R-squared:  0.01695 
F-statistic: 2.026 on 2 and 117 DF,  p-value: 0.1365

> x = relevel( x , ref=2 )
> summary(lm(y ~ x))

Call:
lm(formula = y ~ x)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.3284 -0.6325  0.1383  0.6846  2.7796 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept) -0.15539    0.17330  -0.897    0.372  
xa           0.46732    0.24508   1.907    0.059 .
xc           0.09676    0.24508   0.395    0.694  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.096 on 117 degrees of freedom
Multiple R-squared:  0.03347,	Adjusted R-squared:  0.01695 
F-statistic: 2.026 on 2 and 117 DF,  p-value: 0.1365
```

**Comment by mas29** [comment]
Thank you, @wdurnoUBC, that's the answer I was looking for!
