### ISSUE TITLE
Data for Q1-3

### ISSUE THREAD

**Issue by vahidAK** [STAT540-UBC/Discussion#307]
Hi, @wilcas @shamsbhuiyan @jafarzadeh91 @Jwong684 
I was wondering which data we should use for Q1-3. There are several data in the [directory](https://github.com/STAT540-UBC/STAT540-UBC.github.io/tree/master/homework/assignment/data)
Thanks.

**Comment by janxue** [comment]
I looked at those, and didn’t seem to use any of that data. Instead, if you read the md file, the data you use for the assignment seems to be directly linked there?

I’m thinking these are the ones, correct me if im wrong. 

![screen shot 2019-02-24 at 7 56 31 pm](https://user-images.githubusercontent.com/13646557/53313493-6eeb8e80-386e-11e9-9437-4d937d6891c6.png)

**Comment by jafarzadeh91** [comment]
Thanks Jan,
Yes, If you just go through the assignment file you will find out which datasets you need.
