### ISSUE TITLE
HW01 - Why Panels or Facets 

### ISSUE THREAD

**Issue by mas29** [STAT540-UBC/Discussion#31]
I'm wondering why we need to use panels or facets in our plot for homework one. It seems to me that a single plot (with two different colours for treatment) is best for describing Gene Expression vs Time for both cigarette smoke and the control.

**Comment by aliceZhu** [comment]
If you are using color to distinguish them, it's nice to include them in a single plot. The other options are just some choices that you could use to display these 2 treatments. @wdurnoUBC @gcohenfr Please correct me if I'm wrong here.

**Comment by mas29** [comment]
Thanks.

**Comment by gcohenfr** [comment]
Agree, these are just different options. Just draw the plot you think is best to describe the data and interpret it!
