### ISSUE TITLE
Good logFC cutoff to use in topTable() for normalized microarray data 

### ISSUE THREAD

**Issue by ShuxianFan** [STAT540-UBC/Discussion#320]
In our group project, we are dealing with the microarray data that are RMA normalized. In the limma analysis, we are not sure how to set up the cutoff for selecting differentially expressed genes... Here are a few options that we have tried, the adjusted p-value is based on  "fdr"

number of genes differentially expressed = 23758 - only using adjusted p-value 0.05
number of genes differentially expressed = 480 - lfc cutoff = 1.5, adj.p = 0.05 
number of genes differentially expressed = 201 - lfc cutoff = 2, adj.p = 0.05 
 

Can you give some advice on choosing an "optimal" logFC cut-off? Thank you very much!

**Comment by jafarzadeh91** [comment]
Hi Shuxian,

well, in general, there is no such thing as "optimal p-value" when it comes to evaluating the results of a set of hypotheses. p-value has its specific meaning and implies the probability of rejecting a null hypothesis while it was true. 
In your case, when you put an FDR-adjusted p-value of 0.05 you meant that for each gene in your set, there is a 5% chance you incorrectly label your gene significant. It means that out of those 23758 RNAs, you would expect around 23758*0.05  non-significant RNAs who sneaked in just by pure chance.
The same goes for logFC.
Choosing a cut-off threshold depends on your application and purpose. For example, if you want to suggest a few genes to the biologists to experimentally validate, you just would go for genes with very small p-values to make sure you are not wasting your money on "fake genes" (for the lack of a better term!).
When you are comparing methods in terms of their power to recover differentially expressed genes, you may be more relaxed and more accepting of errors to make your comparison more comprehensive.
It is also somehow cultural. You may like to look up papers related to the specific topic you are working on and see what is the p-value the community seems to agree on.
