### ISSUE TITLE
Agent vs. Treatment

### ISSUE THREAD

**Issue by swils6** [STAT540-UBC/Discussion#33]
I'm pretty sure I know the answer but just want to double check I didn't miss anything. The homework questions ask us the breakdown of the samples for "agent", however the experiment uses " treatment", are the homework questions using these terms interchangeably or am I missing a column is the meta-data?

Thanks,
Sam

**Comment by aliceZhu** [comment]
yes, you are right, they are interchangeable. Some of the samples are treated with cigarette, so the agent just refers to the different treatments.

**Comment by AlisonMcAfee** [comment]
Thanks guys, I was just going to ask the same thing. Thought I downloaded the wrong file. Maybe the wording could be edited to eliminate the confusion?

Cheers

**Comment by gcohenfr** [comment]
In question 2 I mentioned explicitly that `agent` is the same as treatment.
