### ISSUE TITLE
4.2 Creating the design matrix

### ISSUE THREAD

**Issue by ychan287** [STAT540-UBC/Discussion#333]
So I have a question about creating the design matrix, specifically for the age variable - do we keep it as 16, 18, 22, 25 or changing it to 1, 2, 3, 4?

**Comment by janxue** [comment]
for the age variable, remember that it is coded as a continuous value ( <dlb> in your dataframe if you take a look) and not a character value. 

For that reason, the value differences between 16, 18, 22, 25 actually mean something. 
for example : 16 days to 18 days is not the same as 1 day to 2 days.

I left age as 16, 18, 22, 25 etc for my analysis. Maybe the TAs can say more?

**Comment by wilcas** [comment]
Jan is right, here we care about how a change in age (measured in days)
corresponds to changes in expression for each gene. So we want to keep age
as the number of days

**Comment by ychan287** [comment]
That makes sense thank you!
