### ISSUE TITLE
Project Groups

### ISSUE THREAD

**Issue by wvictor14** [STAT540-UBC/Discussion#339]
Hi all,

Here are the members of your project groups for this semester. We tried to distribute students such that every group has a spread of skill level / understanding in statistics, R, git, and biology. After that, I tried to accommodate as many requests as possible. 

I suggest you find your group members at class tomorrow, get to know each other, and start thinking about potential group projects. The first project deadline is the initial proposal, **Jan 24th.** 

The deadline to make further requests on switching group members around will be **January 17th (this friday).**

**Last updated Jan 22, 9:37AM**

**Last name**|**First name**|**group**
:-----:|:-----:|:-----:
Hauduc|Axel|1
Stubbins|Ryan|1
Marr|Alex|1
Sunstrum|Frederick|1
Gao|Sihaoyu|2
Wright|Kristina|2
Yang|Jenny|2
YIN|XUE|2
Bjornson|Saelin|3
Nikolic|Vladimir|3
Quesada-Ramirez|Lucia|3
Sicherman|Jordan|3
Luthra|Ishika|4
Zhang|Yichen|4
Miller|Rachel|4
Zhang|Xi|4
Gillis|Sierra|5
Adam|Naila|5
Fernandez Boyano|Icíar|5
Telkar|Nikita|5
Engelbrecht|Hannah-Ruth|6
Liu|Jimmy|6
Tung|Henry|6
Wu|Qinkai|6
Ali|Hassan|7
Li|Jingyiran|7
Samra|Simran|7
Xia|Lily|7
Keung|Martin|8
Vallejos|Jorge|8
Vreugdenhil|Kimberly|8
Mirza|Ali|8
Khan|Almas|9
Lin|Diana|9
Vasileva|Denitsa|9
Elazzabi|Nairuz|9
Chapman|Abigail|10
Coleman|Patrick|10
Huang|Yue|10
Tello|Marco|10

**Comment by dy-lin** [comment]
@wvictor14, can I (group 1) switch (with Ryan or Laura) into group 9?

**Comment by wvictor14** [comment]
I can switch you with @rstubbins, as long as he is OK with that

**Comment by rstubbins** [comment]
That group switch is OK with me, thanks. @dy-lin @wvictor14

**Comment by nikita-telkar** [comment]
Can I be moved to group 5? @wvictor14

**Comment by wvictor14** [comment]
I can switch @nikita-telkar with marco @mtello22, if he is fine with that?

**Comment by lijingyiran** [comment]
Hi @wvictor14, I would still like to switch to group 7 if that's okay. Thanks!

**Comment by wvictor14** [comment]
@lijingyiran  I can switch you with Lily Xia, @LilyYuanXia is that OK with you?

**Comment by lijingyiran** [comment]
> @lijingyiran I can switch you with Lily Xia, @LilyYuanXia is that OK with you?

Hi @wvictor14 , Lily and I would like to be on the same team if that's okay.

**Comment by rachmiller** [comment]
@wvictor14  Can I switch into group 4? I'd like to work with Ishika Luthra and Nicole (Xi) Zhang.

**Comment by mtello22** [comment]
> t

Hi @wvictor14!
I don't mind if you move me to any group.

**Comment by wvictor14** [comment]
@lijingyiran ,@LilyYuanXia,
You two both have good stats experience so we intentionally put you two in separate groups. If we put you two together, then one group will no longer have anyone with a strong stats background. Unfortunately, I don't think we can accommodate this request because it wouldn't be fair to the other members of the group who will have no stats person. I hope you understand!

**Comment by thisisyichenzhang** [comment]
@wvictor14 Can I switch into group 4? I'd like to work with Ishika Luthra and Nicole (Xi) Zhang.

**Comment by hasan-ali** [comment]
@wvictor14  I'm okay with switching groups

**Comment by wvictor14** [comment]
Ok I moved you around @hasan-ali, @thisisyichenzhang, @lijingyiran , @rachmiller @awakenedhaki, @kvreug

Groups 4, 5, 7, 8 have been changed.

**Comment by naila53** [comment]
@wvictor14 can I please switch to group 5 instead of @hasan-ali ?! 
I would like to work with Sierra and Iciar,, thanks!

**Comment by wvictor14** [comment]
@naila53 OK done

**Comment by SSAMRA14** [comment]
@hasan-ali, @LilyYuanXia, @lijingyiran 
what's your email, fellow group 7 members.
Mine is simrankaursamra@gmail.com 
:)

**Comment by hasan-ali** [comment]
@SSAMRA14 @lijingyiran @LilyYuanXia my email is hassan.ali@alumni.ubc.ca

**Comment by rstubbins** [comment]
@marralex @fsunstrum @Axel Hauduc

What are your emails group 1 members? Mine is rstubbins@gmail.com

**Comment by fsunstrum** [comment]
> @marralex @fsunstrum @hauduc
> 
> What are your emails group 1 members? Mine is [rstubbins@gmail.com](mailto:rstubbins@gmail.com)

fr.sunstrum@gmail.com

**Comment by mtello22** [comment]
Hey group 10!
What are your emails?
Mine is mtello.r02@gmail.com

**Comment by abbichapman** [comment]
> Hey group 10!
> What are your emails?
> Mine is [mtello.r02@gmail.com](mailto:mtello.r02@gmail.com)

abbi.a.chapman@gmail.com Let's talk at the seminar!

**Comment by thisisyichenzhang** [comment]
Hi Group 4, 
My email is zhangyichen93@gmail.com.

**Comment by wvictor14** [comment]
Hi group 9, @almas2019 @deni678 @dy-lin

Your 4th member is now Nairuz Elazzabi @Nayrouz109.

**Comment by dy-lin** [comment]
@wvictor14 we will gladly take the extension given the circumstances. Thanks!
