### ISSUE TITLE
HTML Preview for Private Repos

### ISSUE THREAD

**Issue by dchiu911** [STAT540-UBC/Discussion#34]
I think this issue was brought up in STAT 545A but I'd like to resurface it since I saw it being mentioned in the homework submission guidelines for this course. I believe that the [html preview](http://htmlpreview.github.io/) does not work for private repos. Even if we use the "Raw" HTML then the `token` at the end of the URL expires every now and then. Is this still true, @jennybc?

**Comment by jennybc** [comment]
My understanding is that html preview does work but YES the tokens do expire.
