### ISSUE TITLE
Weather Advisory

### ISSUE THREAD

**Issue by willhahah** [STAT540-UBC/Discussion#341]
Jan. 15, 2020 – 6:00 a.m. PST
Snow is forecast throughout the morning of Wednesday, January 15. Due to the current and expected extreme weather conditions, day classes for Wednesday, January 15 at UBC Point Grey are cancelled. This affects classes starting at 8 a.m. onwards throughout the day. Robson Square operations continue as normal. Status of evening classes starting at 5 p.m. onwards will be updated here at 2 p.m. Please note the campus is NOT closed. Essential staff are expected to come to work. Non-essential staff are expected to come to work unless they’ve spoken with, or received direction from, their manager and made alternative arrangements. Managers may contact Human Resources for further information as required. Faculty and staff please consult UBC’s Winter Weather Conditions Protocol. For information on transit, visit Translink Alerts & Advisories. For the latest update and useful FAQs see below.
https://www.ubc.ca/campus-notifications/
@jafarzadeh91 @wvictor14

**Comment by kdkorthauer** [comment]
Thank you for posting, @willhahah. Yes, all classes are cancelled today. 

Stay safe and warm, and see you Monday!

**Comment by willhahah** [comment]
Thanks a lot for the notification, see you on Monday : )
