### ISSUE TITLE
Issue with markdowns and pushing to GitHub

### ISSUE THREAD

**Issue by HEngelbrecht** [STAT540-UBC/Discussion#342]
Hi @wvictor14 @jafarzadeh91

I can knit my htmls in RStudio with no problem, but no interim md is generated. If I create a github markdown file myself (see output extension below), that seems to work on github (to see the "pretty" version rather than just html code). 

Any chance either of you might be available this afternoon or tomorrow for some help? Or would uploading this github markdown (which does work), along with the rmd and html (which just appear as html code) be sufficient?

`output:
  md_document:
    variant: markdown_github`

Thanks!

Hannah-Ruth

**Comment by jafarzadeh91** [comment]
hi,
what do you mean by creating the MD yourself? if you have an MD file that is created by rmd file and is readable, it is enough. no need for an HTML file.
what we want: one **rmd** + one **md** that is generated by kitting the rmd file.
HTML is not required.

**Comment by HEngelbrecht** [comment]
I created an md file using the YAML instruction above. When I just use the Rmd (with the YAML output set to html), no MD is created, and no graphics folder is created.

**Comment by jafarzadeh91** [comment]
why do you set the output to HTML? just keep the instruction above. we just need an rmd and an MD file. everything else optional. **if** you have images in your md file you should accommodate them in your repository so we could see them. that is what I mean by the graphics folder.

**Comment by HEngelbrecht** [comment]
My bad - thought we had to!

**Comment by dy-lin** [comment]
@HEngelbrecht FYI for future reference
here is the YAML to get the intermediate MD file and the HTML file (along with folder with graphics/figures)
```
output:
  html_document:
    keep_md: true
```

**Comment by HEngelbrecht** [comment]
Thanks @dy-lin!
