### ISSUE TITLE
[Please Watch] Snowday Lecture Screencast

### ISSUE THREAD

**Issue by kdkorthauer** [STAT540-UBC/Discussion#343]
Hi class,

I have recorded and uploaded a screencast recording of Lecture 4 (Today's lecture that was cancelled due to the winter weather). Here is the link:

https://youtu.be/w6bi9PVmzEU

Please view the lecture before coming to class on Monday. We will continue with Lecture 5 as planned on Monday. 

Thanks, and stay warm!

Best,
Keegan

**Comment by dy-lin** [comment]
@kdkorthauer are there any suggested readings etc for those without the intro stats background, or if the review material is still fuzzy?

**Comment by kdkorthauer** [comment]
Hi @dy-lin,

Yes - [here](https://stat540-ubc.github.io/lectures/lectures_2020/lect05_TwoGroupComp.html#3) is a list of some great reference material that might be helpful over the next several lectures (from Monday's lecture notes).

Pertaining to Lecture 4 specifically, I'd recommend checking out Chapter 1 of [Data Analysis for the Life Sciences](http://genomicsclass.github.io/book/) by Rafael Irizarry and Michael Love, 2015 (free online book). 

Best,
Keegan
