### ISSUE TITLE
Push error?

### ISSUE THREAD

**Issue by marralex** [STAT540-UBC/Discussion#345]
Hello,

I tried to submit my seminar 2 work yesterday and my rmd and md files for seminar 2b failed to push. When I tried, I received this message:

To https://github.com/STAT540-UBC/zz_Marr-Alex_STAT540_2020
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/STAT540-UBC/zz_Marr-Alex_STAT540_2020'

What do I do now?

**Comment by schutzekatze** [comment]
Try `git pull` and then `git push`. You've possibly made changes to your remote repo that aren't in sync with local.

**Comment by jafarzadeh91** [comment]
Did you try the suggestion above? it is very likely to work out. if not, please send some screenshots of the whole message you get.
thanks

**Comment by marralex** [comment]
Yes, I did thank you. The problem has been resolved.
