### ISSUE TITLE
Group project repo

### ISSUE THREAD

**Issue by schutzekatze** [STAT540-UBC/Discussion#350]
The invitation for the group (https://github.com/STAT540-UBC/Discussion/issues/346#issuecomment-577967100) project repo seems not to be working - can you please re-invite me to it?

Cheers

@wvictor14 @jafarzadeh91

**Comment by jafarzadeh91** [comment]
Hi there,
I re-sent the invitation. Can you check if it works now? If not, can you explain why you mean by 'not working'?
alternatively, you can see the invitations here as well:
https://github.com/STAT540-UBC/Repo_team_RNAseekers_W2020/invitations

**Comment by schutzekatze** [comment]
It worked, thanks!

**Comment by rstubbins** [comment]
@wvictor14 @jafarzadeh91 

Hi! I don't think I was added to my group repo, I don't see it anywhere? I'm in group 1. Thanks.

**Comment by wvictor14** [comment]
@rstubbins I re-invited you, check your notifications

**Comment by wvictor14** [comment]
Check here as well: https://github.com/STAT540-UBC/Repo_team_40-Degrees-to-Freedom_W2020/settings/access

**Comment by rstubbins** [comment]
I'm in now, thanks! @wvictor14 @jafarzadeh91

**Comment by SSAMRA14** [comment]
Hello @wvictor14 @jafarzadeh91 

I'm part of Group 7 - Genome Surfers. I have not gotten an invitation for my group's repo. Thanks!
Simran

**Comment by IshikaLuthra** [comment]
Hi @wvictor14 @jafarzadeh91,

None of our groups members got added either (CRISPR Bacon)!

Ishika

**Comment by LilyYuanXia** [comment]
Hi TA @wvictor14 @jafarzadeh91 

Could you please re-invite me to STAT540-UBC/Repo_team_-Genome-Surfers_W2020? The old link links to a 404 page.

**Comment by wvictor14** [comment]
Hi all,

please check your group repos invitations page at this link:

https://github.com/STAT540-UBC/YOUR_GROUP_PROJECT_REPO/invitations

you should be able to see your pending invitations there

**Comment by wvictor14** [comment]
https://github.com/STAT540-UBC/Repo_team_Genome-Surfers_W2020/invitations

**Comment by wvictor14** [comment]
@SSAMRA14 @LilyYuanXia have been re-invited

**Comment by rachmiller** [comment]
> Hi @wvictor14 @jafarzadeh91,
> 
> None of our groups members got added either (CRISPR Bacon)!
> 
> Ishika

I'm in now. Thanks!

**Comment by mksm1228** [comment]
@wvictor14 @jafarzadeh91 

I tried typing my team name into the link but got a 404. Could you please resend the invitation?

https://github.com/STAT540-UBC/Repo_team_The-Gut's-brain-feeling_W2020/invitations

**Comment by wvictor14** [comment]
There's no apostrophe

can you try this:

https://github.com/STAT540-UBC/Repo_team_The-Guts-brain-feeling_W2020/invitations

**Comment by wvictor14** [comment]
If you cannot accept the invitation to your group repository, try visiting your team repo invitations page via the associated link below:


Group_Repository_URL
--
https://github.com/STAT540-UBC/Repo_team_40-Degrees-to-Freedom_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_Fantastic-Yeasts_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_RNAseekers_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_CRISPR-bacon_W2020/invitations
https://github.com/STAT540-UBC/Repo_team-The-GINNS_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_Brainiacs_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_Genome-Surfers_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_The-Guts-brain-feeling_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_The-Splice-Girls_W2020/invitations
https://github.com/STAT540-UBC/Repo_team_Go-with-the-Flow_W2020/invitations
