### ISSUE TITLE
Group repos have been created — If you didn’t get the invitation link let me know

### ISSUE THREAD

**Issue by jafarzadeh91** [STAT540-UBC/Discussion#351]
Hi Everyone, 

We already created the repos for each group and sent each member an invitation link. Please click on the invitation link in your email and let me know if there is any issue.

Thanks

**Comment by thisisyichenzhang** [comment]
@jafarzadeh91 I did not receive the invitation link. Can you resend the link?

**Comment by jafarzadeh91** [comment]
Hi @thisisyichenzhang ,
can you go to this page and accept the invitation?
https://github.com/STAT540-UBC/Repo_team_CRISPR-bacon_W2020/invitations

**Comment by thisisyichenzhang** [comment]
The link is broken on my side. “The page is not found”

Best
Yichen

**Comment by wvictor14** [comment]
@thisisyichenzhang I resent you the link
