### ISSUE TITLE
The Deadline for The Seminar 6 - Important

### ISSUE THREAD

**Issue by jafarzadeh91** [STAT540-UBC/Discussion#356]
Hi Everyone, 

The deadline for **seminar 6** is on **Friday, Feb. 28th**. The previous deadline on the website was due to error. 
Also, the seminar session next week would be an office hour to discuss your project and help you with your progress. Seminar 7 (and the others after that) will shift by one week.

Thanks

**Comment by HEngelbrecht** [comment]
Seminars 7-10 currently do not have any due dates on the course website. Does this still stand, or do they all have to be submitted by a certain date?

**Comment by dy-lin** [comment]
As far as I know, there are only 5 seminars that are for marks/have deliverables: Seminar 1, 2, 3, 4, and 6, as listed on the [syllabus](https://stat540-ubc.github.io/subpages/syllabus.html) and the [coursework](https://stat540-ubc.github.io/subpages/assignments.html) page.

**Comment by jafarzadeh91** [comment]
Yes, Diana is right. Other seminars will not be marked although highly encouraged to be done in the seminar class or by yourself.

**Comment by HEngelbrecht** [comment]
Perfect, just wanted to check. Thanks!
