### ISSUE TITLE
Deliverable submission guide

### ISSUE THREAD

**Issue by jafarzadeh91** [STAT540-UBC/Discussion#357]
Hi everyone,

Since I see this problem in lots of the seminar and homework submissions: please make sure we get right inside the folder of your specific submission by clicking on the link you mention in your issue. Some of the current submissions need a lot of guesswork on our side to finally find the folder that contains the actual .md./rmd files we are looking for to grade!

Thanks for your cooperation,
Sina

**Comment by wvictor14** [comment]
+1

But really your repository should be easy enough to navigate, that even if you do just submit a commit, it is unambiguous on what file / directory is the relevant submission.
