### ISSUE TITLE
Seminar06 dendrogram

### ISSUE THREAD

**Issue by dy-lin** [STAT540-UBC/Discussion#358]
for the second item of the seminar06 deliverable:
> Regenerate the dendrogram (clustering distance: correlation; clustering method: mcquitty) on the samples of this heatmap using the `hclust` and `dist` functions.

the `dist()` function's  'method' parameter does not have an option for 'correlation'.

According to `help(dist)`, there are only 6 options:

```
"euclidean", "maximum", "manhattan", "canberra", "binary" or "minkowski"
```

Which are we to use?

**Comment by jafarzadeh91** [comment]
Hi Diana,

If you go through the examples in the ? dist,  there are some examples for this purpose. for instance, this code snippet:

> ## Use correlations between variables "as distance"
> dd <- as.dist((1 - cor(USJudgeRatings))/2)
> round(1000 * dd) # (prints more nicely)
> plot(hclust(dd)) # to see a dendrogram of clustered variables
>

**Comment by wvictor14** [comment]
See relevant lines from the pheatmap source code

https://github.com/raivokolde/pheatmap/blob/master/R/pheatmap.r#L543

```
d = as.dist(1 - cor(t(mat)))
```
