### ISSUE TITLE
Seminar 6 Deliverable 3 which dataset

### ISSUE THREAD

**Issue by gillissierra** [STAT540-UBC/Discussion#359]
Hi. In the third deliverable it mentions plotting the data for "this analyses". Does that refer to the entire data set or just the top genes. Sorry if the answer is obvious, but the wording is ambiguous to me.

**Comment by jafarzadeh91** [comment]
Hi Gillis,
Yeah, I agree wording could be improved here. It refers to the analyses in the _seminar document -  PCA plots_ which had been plotted by the `plot` function.

**Comment by gillissierra** [comment]
Okay. Thank you!
