### ISSUE TITLE
Commits in RStudio not reflecting on GitHub

### ISSUE THREAD

**Issue by HEngelbrecht** [STAT540-UBC/Discussion#360]
Hello @jafarzadeh91 and @wvictor14 

My latest commits from RStudio are not reflecting in GitHub, and I'm not quite sure how to fix it. I'm not sure how to re-establish any connection without losing anything?

Thanks!

Hannah-Ruth

**Comment by jafarzadeh91** [comment]
Can you please provide more details? It is hard to tell with this information. What error did you get when you were trying to push?

**Comment by HEngelbrecht** [comment]
The strange thing is that no error appears.

I just tried shutting down R and opening it again and that seemed to work!
