### ISSUE TITLE
Take home problems in seminar6

### ISSUE THREAD

**Issue by willhahah** [STAT540-UBC/Discussion#362]
Hi~
I've noticed that there were 2 take-home problems in the middle part of seminar 6, so I am wondering should we include answers for those 2 problems in our repo as well? Or just answers for the 3 deliverables are enough for the repo?
Thanks!
@wvictor14 @jafarzadeh91

**Comment by jafarzadeh91** [comment]
Hi 
Only the deliverables at the end of the seminar instructions are required.
Thanks
