### ISSUE TITLE
Analysis Assignment reading in raw data

### ISSUE THREAD

**Issue by kvreug** [STAT540-UBC/Discussion#364]
I'm attempting to read in the raw RNA-Seq data for the analysis assignment, but I keep getting errors. I can read in the metadata and expression matrix files just fine with readRDS(), but when I try to do the same thing with the seq data, it throws an error "unknown input format" at the readRDS().

`geo_obj <- getGEO("GSE60019", GSEMatrix = TRUE)`
`save(geo_obj, file="GSE60019.RDS")`
`seqdata <- readRDS("GSE60019.RDS")`

I also tried going directly off of seminar 6, and used the same file loading approach, loaded it as .Rdata (like the seminar does), and then used exprs(). That throws an error: " unable to find an inherited method for function ‘exprs’ for signature ‘"list"’ "

I have all of the same packages loaded as seminar 6 does. Is there something I'm missing?

**Comment by wvictor14** [comment]
Try using `saveRDS(geo_obj, file="GSE60019.RDS")` instead of `save`. 

When you use `save` the filename should end have the extension `.Rdata`

**Comment by kvreug** [comment]
Thank you!
