### ISSUE TITLE
Analysis Assignment Q2.2: pheamap() throwing error

### ISSUE THREAD

**Issue by gillissierra** [STAT540-UBC/Discussion#365]
When I run pheatmap() exactly as in seminar, I get: 

> Error in cut.default(a, breaks = 100) : 'x' must be numeric

At first I thought this was because my data object for input was a data frame, but if I do `as.matrix(data)` I still get this error. Doing `str(data)` after applying as.matrix() shows it's a matrix of type `numeric` with two attributes of characters (one for genes, the other for samples). 

Do you know why this is and how to fix it? I noticed in seminar that we scaled the data frame, but the assignment only says to log2 transform it.

Your help is appreciated.

**Comment by wvictor14** [comment]
It's hard to help without seeing the code in question. Can you post it

**Comment by gillissierra** [comment]
That's going to have to be a lot in order to explain, but okay.

> head(exp_log2)

GSM1463874 GSM1463872 GSM1463880 GSM1463879 GSM1463876 GSM1463877 GSM1463884 GSM1463882 GSM1463888 GSM1463886
0610005C13Rik 0.07343388  0.6112603   1.294881   2.158420   0.848114   1.308883   0.827053  0.7281467  0.8501695  0.7755348
0610009B22Rik 3.91799621  3.8763825   5.087336   4.983121   5.254668   5.018257   4.594821  4.6622932  4.5463519  5.2989218
0610009E02Rik 6.75708325  4.1081021   2.261646   2.506232   4.237948   4.018360   2.469552  4.1682234  2.9373318  2.3086754
0610009L18Rik 0.58207568  0.5249549   2.353427   2.062651   1.982167   1.386869   2.959804  1.9563929  2.4120103  2.2740696
0610009O20Rik 1.52323025  1.3137902   2.148607   2.934352   1.909839   1.854354   2.258971  1.8087984  1.8067902  1.9751192
0610010B08Rik 4.92208186  5.7539028   3.129353   5.043142   5.977206   5.536718   4.329246  4.8108823  5.6270444  4.2066403
              GSM1463873 GSM1463871 GSM1463878 GSM1463875 GSM1463883 GSM1463881 GSM1463887 GSM1463885
0610005C13Rik  0.7769801  0.2309298  0.9363952 0.06541261  0.4964689  1.1126519  0.3754461  0.6075683
0610009B22Rik  3.8664693  3.8734456  4.2270630 3.71073358  3.1599545  3.4057230  4.6883166  3.4793141
0610009E02Rik  4.7273568  4.9249607  5.2706962 6.06463481  5.3354322  4.8043221  4.2847039  4.3830773
0610009L18Rik  0.9337165  0.5764295  0.7797094 0.06541261  1.2205632  0.6354638  0.8021009  1.5720347
0610009O20Rik  1.3484975  1.3635066  2.4823849 1.89845055  1.8627965  1.5268365  1.0285658  1.2065302
0610010B08Rik  4.7129015  5.1140799  5.0691039 5.10419572  5.4655215  5.0940145  4.9241405  4.6822183

> str(exp_log2)

'data.frame':	14479 obs. of  18 variables:
 $ GSM1463874: num  0.0734 3.918 6.7571 0.5821 1.5232 ...
 $ GSM1463872: num  0.611 3.876 4.108 0.525 1.314 ...
 $ GSM1463880: num  1.29 5.09 2.26 2.35 2.15 ...
 $ GSM1463879: num  2.16 4.98 2.51 2.06 2.93 ...
 $ GSM1463876: num  0.848 5.255 4.238 1.982 1.91 ...
 $ GSM1463877: num  1.31 5.02 4.02 1.39 1.85 ...
 $ GSM1463884: num  0.827 4.595 2.47 2.96 2.259 ...
 $ GSM1463882: num  0.728 4.662 4.168 1.956 1.809 ...
 $ GSM1463888: num  0.85 4.55 2.94 2.41 1.81 ...
 $ GSM1463886: num  0.776 5.299 2.309 2.274 1.975 ...
 $ GSM1463873: num  0.777 3.866 4.727 0.934 1.348 ...
 $ GSM1463871: num  0.231 3.873 4.925 0.576 1.364 ...
 $ GSM1463878: num  0.936 4.227 5.271 0.78 2.482 ...
 $ GSM1463875: num  0.0654 3.7107 6.0646 0.0654 1.8985 ...
 $ GSM1463883: num  0.496 3.16 5.335 1.221 1.863 ...
 $ GSM1463881: num  1.113 3.406 4.804 0.635 1.527 ...
 $ GSM1463887: num  0.375 4.688 4.285 0.802 1.029 ...
 $ GSM1463885: num  0.608 3.479 4.383 1.572 1.207 ...

> data_to_plot <- as.matrix(exp_log2)
head(data_to_plot)

GSM1463874 GSM1463872 GSM1463880 GSM1463879 GSM1463876 GSM1463877 GSM1463884 GSM1463882 GSM1463888 GSM1463886
0610005C13Rik 0.07343388  0.6112603   1.294881   2.158420   0.848114   1.308883   0.827053  0.7281467  0.8501695  0.7755348
0610009B22Rik 3.91799621  3.8763825   5.087336   4.983121   5.254668   5.018257   4.594821  4.6622932  4.5463519  5.2989218
0610009E02Rik 6.75708325  4.1081021   2.261646   2.506232   4.237948   4.018360   2.469552  4.1682234  2.9373318  2.3086754
0610009L18Rik 0.58207568  0.5249549   2.353427   2.062651   1.982167   1.386869   2.959804  1.9563929  2.4120103  2.2740696
0610009O20Rik 1.52323025  1.3137902   2.148607   2.934352   1.909839   1.854354   2.258971  1.8087984  1.8067902  1.9751192
0610010B08Rik 4.92208186  5.7539028   3.129353   5.043142   5.977206   5.536718   4.329246  4.8108823  5.6270444  4.2066403
              GSM1463873 GSM1463871 GSM1463878 GSM1463875 GSM1463883 GSM1463881 GSM1463887 GSM1463885
0610005C13Rik  0.7769801  0.2309298  0.9363952 0.06541261  0.4964689  1.1126519  0.3754461  0.6075683
0610009B22Rik  3.8664693  3.8734456  4.2270630 3.71073358  3.1599545  3.4057230  4.6883166  3.4793141
0610009E02Rik  4.7273568  4.9249607  5.2706962 6.06463481  5.3354322  4.8043221  4.2847039  4.3830773
0610009L18Rik  0.9337165  0.5764295  0.7797094 0.06541261  1.2205632  0.6354638  0.8021009  1.5720347
0610009O20Rik  1.3484975  1.3635066  2.4823849 1.89845055  1.8627965  1.5268365  1.0285658  1.2065302
0610010B08Rik  4.7129015  5.1140799  5.0691039 5.10419572  5.4655215  5.0940145  4.9241405  4.6822183

> str(data_to_plot)

 num [1:14479, 1:18] 0.0734 3.918 6.7571 0.5821 1.5232 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:14479] "0610005C13Rik" "0610009B22Rik" "0610009E02Rik" "0610009L18Rik" ...
  ..$ : chr [1:18] "GSM1463874" "GSM1463872" "GSM1463880" "GSM1463879" ...

> set pheatmap clustering parameters
clust_dist_col = "euclidean"
clust_method = "ward.D2"
clust_scale = "none"
set heatmap aesthetic parameters
var1 = c("orange1", "darkred")
names(var1) = levels(meta$organism_part)
var2 = c("grey", "black")
names(var2) = levels(meta$cell_type)
var3 = c("hotpink1", "hotpink2", "hotpink3", "hotpink4")
names(var3) = levels(meta$time_point)
var4 = c("dodgerblue1", "deepskyblue1", "lightskyblue1")
names(var4) = levels(meta$batch)
covar_color = list(organism_part = var1, cell_type = var2, time_point = var3, batch = var4)
pheatmap(data_to_plot, cluster_rows = FALSE, scale = clust_scale, 
            clustering_method = clust_method, clustering_distance_cols = clust_dist_col, 
            show_colnames = T, show_rownames = FALSE, main = "Clustering heatmap for GSE60019", 
            annotation = meta[, c("organism_part", "cell_type", "time_point", "batch")], annotation_colors = covar_color)

**Comment by jsicherman** [comment]
Are you log2 transforming, or log2 + 1 transforming? My guess is that you're doing the prior, and 0 entries are becoming NAs.

Check by calling `any(is.na(data_to_plot))`. If there's any NA entries, the heatmap will probably be upset.

**Comment by gillissierra** [comment]
I am definitely doing log2 + 1. 
> any(is.na(data_to_plot))
[1] FALSE

**Comment by jsicherman** [comment]
Googled the error and it sounds like it's caused by breaks not spanning the data range. You're not specifying breaks... Maybe it's to do with annotation colors not being valid/spanning all levels? I typically don't specify `annotation_colors` and let it generate them automatically. Maybe removing it will be a bandage fix? It's also possible, I guess, that pheatmap uses the `annotation` parameter to apply both row and column annotations, and you only want column annotations? Sorry, I'm just speculating now and I'm on mobile so I can't check properly.

Also, if this is for the analysis assignment, I believe the question is asking for a heatmap of the sample-sample correlations (ie. not the expression values), so you might not want to generate this heatmap anyways.

**Comment by gillissierra** [comment]
Okay. I'll look in to the metadata more.

I did do that heatmap already as well. I'll change the distance metric for this one and see if it changes anything.

**Comment by gillissierra** [comment]
Never mind. I figured out the issue. It's in the class of the metadata.

**Comment by dy-lin** [comment]
@jafarzadeh91 @wvictor14, are we supposed to log2+1 transform, or log2?

**Comment by jafarzadeh91** [comment]
log2

**Comment by dy-lin** [comment]
Are we to do log2(data +1) transformation as was done in seminar 6? @jafarzadeh91

**Comment by jafarzadeh91** [comment]
Hi Diana,
I think I already answered your question. Please use log2

**Comment by almas2019** [comment]
@wvictor14 @jafarzadeh91 I've been getting the same error with annotation, it wasn't really given what the solution was here. I was also wondering if we run the dist function or run the cor function before creating the pheatmap? 
my code:
`dist(t(ematrix_log2))<-dist_ematrix`
`pheatmap(dist_matrix,...( annotation(metadata[,c(...))`

**Comment by wvictor14** [comment]
yes many people are running into this issue

annotation input needs to be data frame with rownames that match the rownames of the data matrix
