### ISSUE TITLE
practice assignment Q1.2

### ISSUE THREAD

**Issue by lijingyiran** [STAT540-UBC/Discussion#366]
@wvictor14 @jafarzadeh91 
What's the time relationship among E16, P0, P4, and P7?

**Comment by jafarzadeh91** [comment]
Hi,
You can read here:
https://embryology.med.unsw.edu.au/embryology/index.php/Mouse_Timeline_Detailed

**Comment by dy-lin** [comment]
Do we assume that the gestation period is 18 days (i.e. E18 -> P0) as stated in the assignment, or 20 days (i.e. E20 -> P0) in the link?

**Comment by jafarzadeh91** [comment]
Hi Diana,

in order to have consistent answers, please follow the reference in the assignment file:

>  (Assume that the mouse gestation length is 18 days (ie. P0 = 18).). 

adjust the other days based on this reference point.
