### ISSUE TITLE
Q3.2 and 3.3

### ISSUE THREAD

**Issue by nikita-telkar** [STAT540-UBC/Discussion#367]
I'm not clear on the wording of the following two questions.

Q.3.2
`Use limma to fit a linear model with cell type, organism part, age and the interaction between age and cell type as covariates (hint: use lmFit and eBayes).`

Does this mean to control for both cell type and age (__+__+__), or control for one of them and then assess interaction (__ +__*__)? Or to get interaction for both?

Q3.3
`For the gene Eva1a, what is the numeric value of the coeffcient of the age term?` 
In either of the models above, age is not going to be a single coefficient since there are 4 different age groups, and hence three age columns in the model matrix? Which one do we have to select for then?

**Comment by jafarzadeh91** [comment]
Hi Nikita, make a linear model with all the variables (basically 4 variables in this case).

You should look at age as a continuous variable, not as a factor. therefore there is only on age variable and different samples have different ages...

>
