### ISSUE TITLE
heatmap.2

### ISSUE THREAD

**Issue by swils6** [STAT540-UBC/Discussion#37]
Is there a way to scale the heatmap so that the sample names are not cut off? I've already tried reducing the size of the font as well as the size of the margins. Any help is appreciated!
Thanks

**Comment by wdurnoUBC** [comment]
Try using the "margins" argument. Here's an example.
```
r = rWishart(1,12,diag(rep(1,10)))[,,1]
rownames(r) = paste("superlongname",1:10)
colnames(r) = paste("superlongname",1:10)
heatmap.2(r,trace="none",margins=c(10,10))
```

**Comment by gcohenfr** [comment]
You may also want to reconsider the names given to the samples and create an alternative sample label. Your label can convey more information about the groups `treatment` and `time`. Don't do this by hand though!!
