### ISSUE TITLE
STAT540 Lecture 19 Monday March 16 9:30AM

### ISSUE THREAD

**Issue by ppavlidis** [STAT540-UBC/Discussion#371]
As announced, we will be conducting the remaining STAT540 lectures on-line. I'm going to give the lecture at the **usual time**, but using the screencasting tools provided by UBC via Canvas.

To participate visit:
https://ca.bbcollab.com/guest/ab74f0f98c7b414c8bff4ad8fbaaf892

If you need to connect by phone instead:
+1-571-392-7651 PIN: 157 270 0009

**Comment by dy-lin** [comment]
@ppavlidis I am unfamiliar with the Canvas screen casting feature-- will the lecture only be available for viewing live, or will be available for (re-)viewing afterwards as a video on Canvas?

**Comment by ppavlidis** [comment]
I hope you can attend live, but it will be available off-line.

**Comment by ppavlidis** [comment]
Unfortunately there were problems doing the recording, it seemed to cause the connection to be lost, maybe just too much bandwidth for my home internet connection. There should be a partial recording.

Plus I forgot to start the recording for the first ten slides! (the end of lecture 18 that I was continuing today)

If anybody missed the lecture, and the recording isn't useful, please read the lecture notes (slides) and I welcome questions about anything you need help with.
