### ISSUE TITLE
Virtual TA sessions

### ISSUE THREAD

**Issue by jafarzadeh91** [STAT540-UBC/Discussion#372]
Hi Everyone,

In response to the CODVID-19 pandemic, we started to move our TA sessions online. So, we are available online on Google Hangout here at the same time as our previous seminar classes -- Mondays, 12-13:
https://hangouts.google.com/call/qRLOuUdq-LybGjVnODfMAEEE?no_rd

our ids:
jafarzadeh91@gmail.com
victor.2wy@gmail.com

Come and join to ask any questions, discuss the seminars, your group project, etc. It also provides private screen sharing features so we can address your specific question or troubleshoot your code.

Thanks

**Comment by wvictor14** [comment]
hey guys the link is 

https://hangouts.google.com/call/Rg1lBfuqAYGg9Gm0t-EhAEEE
