### ISSUE TITLE
Request for Online Lecture Format

### ISSUE THREAD

**Issue by gillissierra** [STAT540-UBC/Discussion#373]
After this morning's lecture, I'm wondering if we could have the online lectures in the format Dr. Korthauer gave Lec 4, where it was recorded due to the snow day.

I realise this gets rid of the "live" component, but Canvas doesn't seem to allow the lecturer to be both lecturing and view when we chat or raise our hands anyways, so it doesn't seem worth the technical difficulties/distractions. 

I understand we are all trying to figure this out as we go, so I'm just giving feedback and making a request in order to try to make things go more smoothly.

**Comment by ppavlidis** [comment]
Yes, that didn't go as smoothly as I'd have liked!

**Comment by abbichapman** [comment]
I think it still went reasonably well though considering this is the first time we've all had to do this!
