### ISSUE TITLE
Q3.2 cant produce Eva1

### ISSUE THREAD

**Issue by mksm1228** [STAT540-UBC/Discussion#374]
Hi,

```r 
Age_Matrix <- model.matrix(cell_type ~ organism_part + age + age*cell_type, Exp_Design_Age)


Filtered_Matrix <- Exp_Matrix %>%
                      melt(id = 'gene') %>%
                      filter(value > 1.0) %>%
                      mutate(log_cpm = log2(value))


Wide_Filtered_Matrix <- Filtered_Matrix %>%
                          pivot_wider(id_cols = gene,
                                      names_from = variable,
                                      values_from = log_cpm)

Wide_Filtered_Matrix <- na.omit(Wide_Filtered_Matrix)

Log_Matrix_Age_Fit <- lmFit(Wide_Filtered_Matrix[2:19], Age_Matrix)


Log_Matrix_Age_Fit_Eb <- eBayes(Log_Matrix_Age_fit)

topTenGenes <- topTable(Log_Matrix_Age_Fit_Eb)

topGenes <- rownames(topTenGenes)[1:10]


Wide_Filtered_Matrix %>%
  rownames_to_column("Gene") %>%
  filter(Gene %in% topGenes)
``` 

I cant produce the gene Eva1 after performing lmfit and Ebayes. Not sure where I am going wrong with the matrix design and the 4 variables. I used the Log2 values and still am having trouble producing Eva1. Any ideas?

**Comment by wvictor14** [comment]
What do you mean by "produce" eva1? I assume you mean find it statistically significantly differentially expressed, but why specifically eva1?

**Comment by mksm1228** [comment]
Question 3.3 asks specifically about eva1 so I was assuming that in section 3.2 we should find eva1 as a significantly expressed gene.

**Comment by wvictor14** [comment]
Nope, it is not required for eva1 to be significant or not, it will have a coefficient either way that you can pull out and use for answering the question.

**Comment by mksm1228** [comment]
Oh okay thanks for the clarification. I just assumed that eva1 would be a significantly expressed gene.

**Comment by mksm1228** [comment]
Hey @wvictor14, 

So I tried setting coef = 3 to specify that the topTable should be generated using the "age" contrast but having no luck. I also tried if not removing the NAs would do it but no luck there either. In my mind, I think the next logical step after using lmfit and eBayes is to use topTable() but I just can't pull out eva1. Any advice?

```{r}
Age_Matrix <- model.matrix(~cell_type + organism_part + age + age*cell_type, Exp_Design_Age)

Log_Filtered_Matrix <- Exp_Matrix %>%
                        melt(id = 'gene') %>%
                        filter(value > 1.0) %>%
                        mutate(log_cpm = log2(value+1))

Wide_Filtered_Matrix <- Log_Filtered_Matrix %>%
                          pivot_wider(id_cols = gene,
                                      names_from = variable,
                                      values_from = log_cpm)

any(is.na(Wide_Filtered_Matrix))

Wide_Filtered_Matrix <- na.omit(Wide_Filtered_Matrix)

Log_Matrix_Age_Fit <- lmFit(Wide_Filtered_Matrix[2:19], Age_Matrix) %>%
                          eBayes()

top_Ten_Genes_Age <- topTable(Log_Matrix_Age_Fit, coef=3)

topGenes <- rownames(top_Ten_Genes_Age)

Wide_Filtered_Matrix %>%
  rownames_to_column("Gene") %>%
  filter(Gene %in% topGenes)
```

**Comment by almas2019** [comment]
Hey, just letting you know that age*cell type is the same as age+cell_type+age:cell_type, in your case write either age*cell_type or age+cell_type+age:cell_type, but I don't think it makes sense to write a combo of both (since you seem to be including the additive model twice)

**Comment by kdkorthauer** [comment]
@mksm1228 - Are you sure the `age` coefficient is represented by `coef=3` in your model? Remember that the intercept also has a coefficient!

@almas2019 - You are correct that `~age*cell_type` yields the same design matrix as `~age+cell_type+age:cell_type`. However`~age+cell_type+age*cell_type` also gives the same design matrix. The `model.matrix` function is smart enough to not "include the additive model twice". Note however that `~age:cell_type` alone yields a different model (without main effects of age and cell type).

**Comment by wvictor14** [comment]
+1 to using the coefficient name instead of the column number, for reproducibility / transparency

**Comment by lijingyiran** [comment]
Hi @kdkorthauer and @wvictor14 ,

When we are trying to get the coefficient estimate for Eva1a, can we first find the row number of Eva1a in the filtered dataset and then access the coefficient estimate in the limma output of the estimate with the same row number? If not, do you know how I can access the coefficient by gene name because I don't think the limma output has a gene name column thus I'm not quite sure how to do that.

**Comment by wvictor14** [comment]
hey did you try what we talked about in office hours? your results should have gene names, if they don't check the input of your data into lmfit and ensure they have gene names as rownames

**Comment by mksm1228** [comment]
@almas2019 I'm not sure this is entirely true. I just tested this out and the matrix won't produce the cell_type column. @wvictor14 could you please confirm if writing ```age*cell_type``` is the same as ```age+cell_type+age:cell_type```?

**Comment by wvictor14** [comment]
yeah it does, see keegan's comment

**Comment by mksm1228** [comment]
> @mksm1228 - Are you sure the `age` coefficient is represented by `coef=3` in your model? Remember that the intercept also has a coefficient! It's generally safer practice to name the coefficient as the argument to `coef`, instead of specifying it's column number in the design matrix.
> 
> @almas2019 - You are correct that `~age*cell_type` yields the same design matrix as `~age+cell_type+age:cell_type`. However`~age+cell_type+age*cell_type` also gives the same design matrix. The `model.matrix` function is smart enough to not "include the additive model twice". Note however that `~age:cell_type` alone yields a different model (without main effects of age and cell type).

Thanks Keegan! Also, is my interpretation that the intercept is the mean Y value where all the x variables (cell_type, organism_part, age) are "0" (Surrounding cell, E16 etc) correct? And so, to find the R squared value for a particular gene for a particular coefficient, I would add the intercept with the rest of the corresponding coefficients? For example intercept + coef age 18, 22, and 27?
