### ISSUE TITLE
Analysis Assignment; No DEGs?

### ISSUE THREAD

**Issue by jsicherman** [STAT540-UBC/Discussion#375]
Hi,

When I do my model fit and subsequently call `topTable`, I get 0 DEGs at `fdr < 0.05`... This seems less than ideal, and even the ranks of the genes in my analysis (ordered by fdr) are significantly different than the ranks of the top 100 genes from the original paper (ie. not even the most significantly DEG in my analysis is near the top of the paper's DEGs).

Interestingly, when I build the model using age as a factor value (of timepoints), I get around 600 DEGs that correspond quite well with the original paper. I also get a handful of DEGs if I use `log2(1+ CPM)` normalized counts (instead of `log2(CPM)`).

I guess I'm not really asking "is 0 DEGs what we're supposed to get", but it's a little worrying to me to get this result.

**Comment by wvictor14** [comment]
It doesn't really matter how many degs you get, it's more about if what you did to get there is correct or not. it depends on the experiments and specific phenotypes of interest, but finding nothing significant often happens.

**Comment by jafarzadeh91** [comment]
Hi Jordan,

You brought up good points. I suggest you talk about them in your last point. As far as the assignment goes, I suggest everyone just stick to the assignment description. Now that you point out, I think maybe considering age as a factor might be a better decision as prenatal and postnatal stages of life are inherently different...However, it is a bit hard to say which way is better than the other in general without spending some time to think more deeply about our goal in the analysis

**Comment by naila53** [comment]
@wvictor14 @jafarzadeh91 this motivated a question i have which is how to asses goodness of fit of linear models in limma?  In lecture7 by @kdkorthauer we touched briefly on nested models and the concept of "goodness of fit" by the end of the slides( we were focusing on one gene). I'm not sure I understand how to interpret those F tests when we compare different models, a bunch of outputs were listed in those lecture final slides but what are the conclusive remarks? and how do we assess different  linear models in limma? eBayes outputs a bunch of things including F.p.values, what can i make of these?
in theory, my understanding is when the number of data points is large, an F-statistic that is only a little bit larger than 1 is already sufficient to reject the null hypothesis.So how is helpful in comparing different models?
sorry I'm just a bit confused trying to synthesize all the course material here but I just want to link these concepts..
thanks!

**Comment by jafarzadeh91** [comment]
Hi Naila,
F-test can be used as a statistic comparing the fitness of a linear regression model with some variables (age, genotype, etc) compared to a baseline with just an intercept. The F-statistic is a measure comparing the fitness of these two models. The p-value for the F-statistic tells you if the model is a significantly better estimator for the response compared to the baseline. 
For the nested case, you not comparing your linear model (age, genotype) with the intercept baseline but rather with a nested model that has some of the variables (e.g. only age). P-values can be interpreted similarly, smaller p-value means evidence for the informativeness of extra variables in the model is statistically significant.
Thanks

**Comment by almas2019** [comment]
@wvictor14 @jafarzadeh91 I realized that different ways to specify age yield different results here(either 0 or something else), so can we assume that E16 is 16 and P0 is 18 or is it like the lectures using negatives?

**Comment by jafarzadeh91** [comment]
Please follow as mentioned in the assignment instruction (P0=18).

> Create a new column in the samples metadata tibble. Call it "age" and populate it with the appropriate numeric values. Hint: Assume that the mouse gestation length is 18 days (ie. P0 = 18).

**Comment by almas2019** [comment]
Okay thanks!
