### ISSUE TITLE
computational resources

### ISSUE THREAD

**Issue by dy-lin** [STAT540-UBC/Discussion#377]
Given my group's large dataset, we are finding it difficult to run our analysis on our personal laptops (RStudio crashes a lot).

Is it possible to setup [ORCA](https://academic.oup.com/bioinformatics/article/35/21/4448/5475597) (from [GSC](https://www.bcgsc.ca/resources/orca-omics-research-container-architecture)) for us to run our Rscripts on? 

I see that it has been done in the past as it was seen in [seminar05](https://github.com/STAT540-UBC/STAT540-UBC.github.io/tree/master//seminars/seminars_winter_2020/seminar5/sm5.md):

> To login to the account, open a command line program (i.e Terminal) and type in:
> ```
> ssh -X your_username@orca-wg.bcgsc.ca
> ```

I can contact Systems at GSC, but I believe they will require your approval before doing so.

**Comment by wvictor14** [comment]
I don't believe we have access to this this year, hence the modification we made in that seminar. @jafarzadeh91 can comment on that.

What parts of your analysis (and what kind of data) are difficult to run? Maybe we can help you figure of a less-computationally-demanding approach to your analysis?

**Comment by jafarzadeh91** [comment]
Hi Diana,

I don't think it is possible based on the authority of TAs. I can think of a few alternatives like Google cloud, Amazon, etc which offer free cloud server under some conditions (and also if you are allowed to put your data online). If you think you absolutely need more resources maybe you can directly ask the instructors and see if it is possible.

All being said, If I were you, I would try to get around the issue by using computational tricks. The easiest case is to just focus one only or just a few chromosomes but there are more sophisticated ideas as well. for example, one is limiting yourself to the ~22K probes from the previous Illumina assays (which presumably are more important). There are also algorithms designed to reduce the number of CpG sites in your data by removing the redundancy in data (look up Aclust algorithm for example).
