### ISSUE TITLE
Treating NAs

### ISSUE THREAD

**Issue by lijingyiran** [STAT540-UBC/Discussion#378]
Can we use imputation methods to impute the NAs or do you want us to directly omit them? The coefficient estimates would be different depending on whichever method is used, so our answers could deviate from the solution scheme.

I just realized that if we use na.omit() to treat the unmelted data before fitting limma then the gene "Eva1a" would be eliminated from the dataset hence won't be able to obtain a coefficient estimate for this gene (needed for Q3.3). I am just wondering that could I use MICE to impute the missing values and fit limma to get the coefficient estimate for Eva1a afterwards?

@jafarzadeh91 @wvictor14

**Comment by jafarzadeh91** [comment]
Hi there,
Please don't use external libraries for this assignment. 
I cannot find any NA element in the gene expression matrix. To be sure, Are you using the data located here:
https://github.com/STAT540-UBC/STAT540-UBC.github.io/tree/master/homework/assignment/data

the file gse60019_expression_matrix.RDS?

**Comment by lijingyiran** [comment]
Hi @jafarzadeh91,

The original dataset does not have NAs, but after I unmelted the melted data (using pivot_wider()) from question 2 in question 3.2, I got a dataset with NAs looking like this:

<img width="862" alt="Screen Shot 2020-03-18 at 3 37 31 PM" src="https://user-images.githubusercontent.com/54858664/77013958-70cb3880-692e-11ea-8aba-1d539e14fdb0.png">

Do you have any idea on how to deal with this? Thanks!

**Comment by wvictor14** [comment]
Hi @lijingyiran ,

If the original data did not have NAs, and then you did something to it (e.g. with pivot_ functions) then likely there is some error in your code or approach. I suggest you try to pinpoint the exact lines where NAs are introduced and post that here, if you still need help.

**Comment by lijingyiran** [comment]
Hi @wvictor14 ,

Here's my code:
<img width="758" alt="Screen Shot 2020-03-19 at 12 23 34 PM" src="https://user-images.githubusercontent.com/54858664/77106577-8d25ae80-69dc-11ea-850c-f80940b07e59.png">
<img width="858" alt="Screen Shot 2020-03-19 at 12 23 49 PM" src="https://user-images.githubusercontent.com/54858664/77106578-8d25ae80-69dc-11ea-8280-2b96493300e0.png">

<img width="772" alt="Screen Shot 2020-03-19 at 12 22 59 PM" src="https://user-images.githubusercontent.com/54858664/77106568-8ac35480-69dc-11ea-9731-5324a8abc83b.png">
<img width="648" alt="Screen Shot 2020-03-19 at 12 23 15 PM" src="https://user-images.githubusercontent.com/54858664/77106574-8c8d1800-69dc-11ea-8ce5-e4f09fcab384.png">

So after I unmelt using pivot_wider(), the NAs appeared.

Thanks for the help!

**Comment by wvictor14** [comment]
NAs are occurring because you are filtering out specific entries of gene x sample that are < 1 in the "melted" (this is not quite the right terminology but you know what i mean) data

so when in your pivot_wider'd data, the NAs correspond to the rows that were filtered out in the "melted" data. 

This is not quite what the assignment asks for in the filtering instruction. I suggest you reread the instruction carefully, and maybe refer to #379
