### ISSUE TITLE
Analysis Assignment - Filtering condition clarification.

### ISSUE THREAD

**Issue by mtello22** [STAT540-UBC/Discussion#379]
Hi, 
I followed the indications for removing lowly expressed genes, however, doing so removes the gene _Eva1a_ that you mention later. I suppose the filtering should not remove it, because you are asking about that gene in question 3.3.
I followed these indications:

>Remove lowly expressed genes by retaining genes that have CPM > 1 in at least as many samples as the smallest group size (i.e use table() to identify the number of samples belonging to **each treatment group**. The smallest group size is the smallest number in that table). **Each treatment group** consists of subjects belong to a unique combination of cell type and organism part.

Then the smaller treatment groups are 
epithelium_of_utricle & surrounding_cell: 4 samples 
sensory_epithelium_of_spiral & organ_surrounding_cell: 4 samples 

So my question is, should I redefine the criteria for filtering? or do I just pick another gene and interpret the coefficient of the age term?
Best

**Comment by wvictor14** [comment]
The filtering will not remove eva1a

**Comment by wvictor14** [comment]
maybe you are interpreting the filtering criteria differently than what is meant

**Comment by mtello22** [comment]
Then could you please help me to review the steps I'm doing?
1. Add a new column to the metadata stating which one of the four combinations that sample belongs to.
2. Using that column, select the samples corresponding to the two groups with fewer samples: 
-epithelium_of_utricle & surrounding_cell (4 samples)
-sensory_epithelium_of_spiral & organ_surrounding_cell) (4 samples) 
3. Check that all genes in those samples have valid entries (CPM>1), those that have at least one invalid entry are removed.
This is the step where Eva1a is removed because it has invalid entries:

GSM1463871 5.6359463
GSM1463873 1.7096091
GSM1463875 2.4030179
GSM1463878 2.8938840
GSM1463881 1.5843466
GSM1463883 **0.4776444**
GSM1463885 1.2884642
GSM1463887 **0.8188629**

Since those are the smaller groups they must have valid entries for all their genes, right? 
Best,

**Comment by wvictor14** [comment]
Not quite,

so the instruction "filter genes with >1 cpm in at least as many samples as the smallest group"

means that for each gene you will need to calculate the number of expression values is > 1 cpm.

then, you need to filter out any genes where this occurs less than (sample size for smallest group)

an example:

| | sample1| s2| s3| s4| s5| s6|
| --- | --- | ---  | ---  | ---  | ---  | --- |
| gene1 | 2 | 2 | 3 | 0 | 7 | 0 |
| gene2 | 0 | 0 | 0 | 0 | 3 | 0 |


gene1 has 2 values of <1 cpm
gene2 has 5 values of <1 cpm

lets's say the sample size for smallest group is 2

gene 2 should be removed, gene1 should be kept

**Comment by mksm1228** [comment]
Oh, @wvictor14 thanks for the clarification. The wording was quite difficult for me to understand but your explanation was very helpful.

**Comment by mtello22** [comment]
Thank you @wvictor14 for your explanation!
Yes, that is what I am doing, then maybe my definition of groups is wrong. 
I understood that each treatment group was a unique combination of organism_part and cell_type, under those conditions one group would be:

organism_part: epithelium_of_utricle
cell_type: surrounding_cell

This combination has four samples:
| sample | organism_part | cell_type | CPM |
| ------------- | ------------- | ------------- | ------------- |
| GSM1463873 | epithelium_of_utricle  | surrounding_cell | 1.7096091 |
| GSM1463873  | epithelium_of_utricle | surrounding_cell | 2.8938840 |
| GSM1463878 | epithelium_of_utricle | surrounding_cell | 0.4776444 |
| GSM1463883 | epithelium_of_utricle  | surrounding_cell | 0.8188629 |               
 
Since the smallest group size is 4, Eva1a should be removed according to my grouping. 
How should I interpret the criteria for making the groups?

**Comment by wvictor14** [comment]
@mtello22 from your description above, step 2. is not necessary / not correct. You are supposed to be filtering on the entire data, not a subset of the smallest group (which you seem to be doing but i'm not 100% sure).

I suggest you pull out EVA1A and print it according to how i have it displayed above (1 row for eva1a and all values across samples in columns), then work with that. You will see that it does not fail this filtering criteria.

FYI for anyone else reading this. This is the common way to describe filtering in most genomic studies (dna methylation, expression, genotype). So it's good to have an understanding of what this means.

**Comment by mtello22** [comment]
Hi,
Thank you for the feedback, I think I did not explain myself correctly. 

I am not partially filtering the dataset and considering each treatment group separately. If a gene fails to meet the criteria for any treatment group then I remove it from the whole dataset.

The idea I had about filtering was to make sure all the treatment groups had at least _n_ valid entries for all genes. If I were just to check that a given gene has _n_ valid entries in total (regardless of how these entries are distributed), that could potentially leave groups with all entries invalid (or a higher proportion than the threshold).

**Comment by wvictor14** [comment]
yes the instruction means to check over all samples, not in each treatment group separately

it may not be the best approach, but it is definitely a common one

**Comment by mtello22** [comment]
Got it!
Thank you very much for the clarification. 
I really wasn't sure about how to do differently the filtering.

**Comment by almas2019** [comment]
Hi @wvictor14 so in this case we're using the CPM and not the log2CPMs to filter for at least 4 or more genes that have values >1? Then I assume we log transform this filtered dataset?

**Comment by wvictor14** [comment]
yes, cpm >1
