### ISSUE TITLE
Seminar 04b - Can't get the right answer in a pipe?

### ISSUE THREAD

**Issue by tshalev** [STAT540-UBC/Discussion#38]
Hi all,
For some reason when doing seminar 04b I can't seem to get the right answer using the dplyr pipe. I've attached the markdown file, if anyone know the answer it would be much appreciated. I've noticed that many people have gotten different answers for this question and most are wrong.

Thanks,
Tal
https://github.com/STAT540-UBC/zz_shalev-tal_STAT540_2015/blob/master/Seminar%2004/Seminar_04b_assignment_Tal_RMD.md

**Comment by AlisonMcAfee** [comment]
It might be because you're looking using the un-normalized GDPs, rather than normalizing to Canada's?

**Comment by kmnip** [comment]
Normalizing to Canada shouldn't change the answer.

Max growth in **GDP per capita**: Kuwait between 1967~1972
Max growth in **GDP**: China between 2002~2007

The question asks about GDP, not GDP per capita, ie.

>Can you modify the code above to answer this questions: which country gains the most growth in GDP in a 5-year interval? Between which 2 years?

So, I think Tal's answer is correct.

Tal, I actually used 2 separate piped commands: first to select the country and the max delta GDP value, and second to select the years. Technically, the two could have been nested.

Ka Ming

**Comment by tshalev** [comment]
OK, thanks Ka Ming, that looks right. Yes, when people looked at GDP per capita they were right to say Kuwait; but I was seeing some other answers as well.
