### ISSUE TITLE
Getting coefficient estimate for Eva1a

### ISSUE THREAD

**Issue by lijingyiran** [STAT540-UBC/Discussion#381]
Hi @wvictor14 , @jafarzadeh91 ,

When we are trying to get the coefficient estimate for Eva1a, can we first find the row number of Eva1a in the filtered dataset and then access the coefficient estimate in the limma output of the estimate with the same row number?

Thanks in advance!

**Comment by jafarzadeh91** [comment]
Can you provide some code? It depends on how you formulate your limma I think.

**Comment by lijingyiran** [comment]
Hi @jafarzadeh91 ,

Here's my code for limma and accessing the coefficient:

<img width="564" alt="Screen Shot 2020-03-19 at 8 09 14 PM" src="https://user-images.githubusercontent.com/54858664/77132727-997e2b80-6a1d-11ea-9804-42592546f2e0.png">
