### ISSUE TITLE
logCPM? 

### ISSUE THREAD

**Issue by abbichapman** [STAT540-UBC/Discussion#382]
In question 2 it specifies to log2 transform the data, but in question 3.2 it just says to use logCPM. As someone coming from a bio background, I was always taught to assume log means base 10, so should we be using log10(CPM) here, or should we assume that we should use log2(CPM) again?

**Comment by jafarzadeh91** [comment]
Please go forward with the same transformation (use log2).
Thanks

**Comment by almas2019** [comment]
@jafarzadeh91 are we doing any scaling on the log values like the seminar, as I didn't but it seems to be the case in the seminar?

**Comment by dy-lin** [comment]
(i.e. the scaling before calculating correlation, for building the heatmap)

**Comment by jafarzadeh91** [comment]
If by "Scaling" you meant normalizing the data like what we did for performing PCA, no. Performing Log on the data is scaling in a sense though.
