### ISSUE TITLE
topTable() coefficients

### ISSUE THREAD

**Issue by SaelinB** [STAT540-UBC/Discussion#384]
I've noticed that when you specify two coefficients separately in topTable(), and then specify them together in a vector, the resulting number of genes is higher than the sum of the two separately.

for example, (without changing any other code):
* coef="cell_typesensory_hair_cell" gives 0 genes
* coef="organism_partsensory_epithelium_of_spiral_organ" gives 123 genes
* coef=c(""cell_typesensory_hair_cell", "organism_partsensory_epithelium_of_spiral_organ") gives 180 genes. 

My guess is that specifying one will give genes that are deferentially expressed **only**  in that coefficient, whereas specifying two would include DEGs in both? 
i.e. there are 57 DEGs in both, but only 123 specific to organism part and 0 specific to cell type. Is this right or am I just doing something wrong?

**Comment by wvictor14** [comment]
I'm not sure what toptable gives you when you put in 2 coefficients. I would just use toptable with 1 coefficient at a time

**Comment by SaelinB** [comment]
I will for the assignment, but two coefficients were used in one of the lectures - @kdkorthauer could you clarify what this does?

![top_table](https://user-images.githubusercontent.com/50117827/77259633-0f61dd00-6c40-11ea-964a-820c4668669b.png)

**Comment by kdkorthauer** [comment]
Specifying more than one coefficient provides the result of the joint hypothesis test that they are all equal to zero.
