### ISSUE TITLE
topTable() Error in fit$coefficients[, coef] : subscript out of bounds

### ISSUE THREAD

**Issue by Deni678** [STAT540-UBC/Discussion#385]
I am wondering if someone can help me with the error I get whenever I try to run topTable() with age as a coefficient.
I keep getting: Error in fit$coefficients[, coef] : subscript out of bounds

My code is:

design<-model.matrix(~samples_meta$cell_type +samples_meta$organism_part+ samples_meta$age+samples_meta$organism_part:samples_meta$age)
a<-lmFit(expression_matrix_filtered,design)
ebFit <- eBayes(a)
t<-topTable(ebFit, coef="age", n=Inf)

@wvictor14 @jafarzadeh91

**Comment by kdkorthauer** [comment]
The name specified for `coef` in `topTable` must match exactly the name of the column in your design matrix. check `head(design)` of your design matrix to see these column names. Note that you can use the `data` argument in `model.matrix` to tell it where to find the variables (and avoid having to type `samples_meta$` before every coefficient.

**Comment by Deni678** [comment]
@kdkorthauer I followed your suggestion and fixed it. Thanks so much! I had been stuck on it for a while.
