### ISSUE TITLE
Outliers

### ISSUE THREAD

**Issue by swils6** [STAT540-UBC/Discussion#39]
In lecture 5 it says to define what you would call an outier and be consistent throughout the analysis. In terms of analysis (and the homework question), I'm struggling with what thresholds to use to decide if a sample is an outlier. For instance, if 5% of a sample's probes are outliers compared to the mean expression value of that probe is this enough to consider it an outlier? and what really is the different in determining that 5% over 10% is considered an outlier. 
I understand that utilizing other methods both quantitative and qualitative to determine outliers, but when it is not clear (i.e correlation is all quite high), and for a small sample size, it's hard to determine whether we are seeing a outlier or if it is actually biologically interesting and we just don't have the sample size to really observe what is going on.

**Comment by aliceZhu** [comment]
I think it's a good question to ask the Profs during lectures.  
The following is just what I would do: if I have a sample that seems like an outlier, I will get other samples that have the same experimental condition as this putative outlier, such as the same time and treatment in this homework. Thus, they are supposed to be similar in terms of all the probe reading. Then I will scrutinize the pairwise scatterplots and correlation, and if the putative outlier deviates significantly from the other samples of the same group, I would call it a outlier. If all of them are consistent, it should be something pertaining to this experimental group (and they should be clustered together if you allow dendrogram in heat map, but please note that, if you allow dendrogram, the orders of samples will be rearranged compared to your input correlation matrix).

**Comment by mas29** [comment]
So what you're saying, Alice, is that for this question, "quantify for each sample, whether it “sticks out” compared to the other samples", we should look at correlations and scatterplots for each group of samples with similar time/treatment? If we get a low correlation in this scenario, it's an outlier?

**Comment by swils6** [comment]
This is related to my question. Biologically speaking, especially in gene expression studies, I would expect parameters such as SNPs, ethinicity, etc to affect gene expression. Therefore if you have a lower correlation (lower being ~0.8-0.89), I would want to look at these parameters. Currently, we do not have that data and the r values are what I would expect between human samples. So I would really hesitate to remove a sample only on correlation or if it happens to stick out in 1 out of 5 plots. If a sample consistently sticks out, I can say with more confidence that it may be an outlier, but in the case of our assignment I feel like it's ambiguous, unless I have done something wrong?

**Comment by aliceZhu** [comment]
@mas29 , for the "quantify for each sample" purpose, a heat map for the samples and a box plot for the correlations of each sample (samples on the x axis, and the 23 correlation values for each sample on the y axis ) would be useful to pinpoint any putative outlier if there is any. And these plots are just some examples, so we encourage you to use any plots you think useful. But the putative outlier may not be a true outlier, which can be tested by examining it against the other samples with the same time and treatment conditions (such as via a pairwise scatterplot). If the putative sample agrees well with the samples in the same time+treatment experimental group, I won't treat it as an outlier. For instance, Sam @swils6  brought up a good point above, other parameters such as SNP can also contribute to the correlation and such parameters are not controlled in the experimental design. After such comparison, you can judge whether it's a true outlier or not. Unless you are sure it's a true outlier, it's better not to remove it. I highly recommend you  ask this question during lecture,  the Profs @gcohenfr will have a more systematic and comprehensive approach for such problem.

**Comment by gcohenfr** [comment]
I agree with all the discussion here. @swils6 you are doing an excellent exploration of the data, which is what we want you to do in this point. You are also thinking beyond the data given and what should be done before removing a sample from a study. Add all those thoughts to your solution. 

Just as a minor comment, you mentioned in your first comment that you observed "5% of a sample's probes are outliers compared to the mean expression value of that probe". I am not sure how you are declaring a probe an "outlying probe". In any case, all samples may contain outlying probes and these may be *the* interesting genes we are looking for!! so, no, we won't call a sample an outlier based on a percentage number of outlying probes. We are not looking for outlying probes but outlying *samples* (I know we can go in circles here). In this question, we want you to study all probes' expression together. @aliceZhu mentioned some ways of doing this. In any case, this is just an exploratory analysis, not an exhaustive search.
