### ISSUE TITLE
Presentations 

### ISSUE THREAD

**Issue by SSAMRA14** [STAT540-UBC/Discussion#390]
Hello,

I was wondering if we could get an update on the presentations. Since classes are now online, do we still prepare and submit slides by March 31st?

Thanks for your time!

**Comment by saramostafavi** [comment]
Hi @SSAMRA14 

We announced the plan in lecture last week and repeated in the lecture this week. There was also an earlier email (about ten days ago) to all students about this. Please let us know if you are somehow not receiving these information, or can't join the lectures.

As for the oral presentation: yes each group needs to submit a pptx file AND a text document describing each slides (could be in bullet form). As before, presentations should be made for a 15 oral talk. We will use the same rubric previously provided (on course website) to grade your files. Website should be updated today to reflect this information.

**Comment by SSAMRA14** [comment]
Thank you
