### ISSUE TITLE
Presentation in repo?

### ISSUE THREAD

**Issue by kvreug** [STAT540-UBC/Discussion#396]
Two quick questions about the presentation. 
1. Should we make the presentations as an rmarkdown?
2. Should we put the presentation and our document of what we would say in our repos?

**Comment by wvictor14** [comment]
https://stat540-ubc.github.io/subpages/group_project_rubrics.html#oral-presentation-20-pts

Follow the posted instructions, a pptx of slides and docx of what would be said about each slide

**Comment by wvictor14** [comment]
It doesn't really matter how you create it. Only the pptx content and docx will be used for marking.

**Comment by jafarzadeh91** [comment]
Hi there,

Group works should be out in your group Github repository.
