### ISSUE TITLE
technical report for group repo?

### ISSUE THREAD

**Issue by mksm1228** [STAT540-UBC/Discussion#398]
@wvictor14 @jafarzadeh91 

For the group project, there is a deliverable titled "Analysis and Results" and we were wondering do we need to synthesize our analyses into one technical report?

**Comment by jafarzadeh91** [comment]
Hi there,

You don't need to have a single file including all the analysis. However, in each folder, you should create a readme file to help the reader navigate and learn about different results. The main readme file of your repo also should provide a summary of your project and link to various results.

**Comment by mksm1228** [comment]
Ok thanks!
