### ISSUE TITLE
Max group size?

### ISSUE THREAD

**Issue by kmnip** [STAT540-UBC/Discussion#4]
@gcohenfr

What is the maximum number of people per group? Paul said we may have 5 due to the class size, but I remember you said 3~4. Has it been finalized, yet?

Thanks!
Ka Ming

**Comment by kmnip** [comment]
It's 5.
Thanks for addressing this in today's lecture!

**Comment by aliceZhu** [comment]
I remember Gaby also said if you really cannot find 5 people, 4 is ok too. But 5 is definitely the idea group number.
