### ISSUE TITLE
Question2

### ISSUE THREAD

**Issue by AlisonMcAfee** [STAT540-UBC/Discussion#40]
Hello,

I'm not sure I understand what question 2 is asking.. are we to make a heatmap where one axis is the samples sorted one way, and the y axis is the samples sorted the other? Using the 'cor' function and two different data frames?

Thanks

**Comment by AlisonMcAfee** [comment]
@swils6, maybe you could help?

**Comment by aliceZhu** [comment]
Hi Ali, you will make 2 heat maps. In each heat map, the samples on both x and y axis are sorted in the SAME order. For instance, in one heat map, samples are sorted by time first and then treatment, so you need to rearrange the sample columns of your data in such order. Then you will make use cor to make the correlation matrix. Your heat map will be built based on this correlation matrix

**Comment by aliceZhu** [comment]
When you call heat map function to plot this correlation matrix, the order of the samples on the plot (on both x and y axis) will stay the same as your correlation matrix, unless you specifically ask for a dendrogram on the heat map. Thus, you will plot 2 heat maps for this question, one for each order. If you are using heatmap.2, you could consider using RowSideCol and ColSideCol to assign different color labels to samples in terms of time or treatment levels. The purpose of this question is to exam whether treatment or time have an obvious effect on the samples, so you could eyeball on it to guess whether there is an outlier.

**Comment by AlisonMcAfee** [comment]
thanks for the help, Alice! I am still a little confused on how the data should look going into cor, though. It should be the complete dataset (NOT the single gene), where rows are genes and columns are something like "control_1_sampleID"?

**Comment by swils6** [comment]
The correlation matrix should be 23X23; both the row.names and colnames could be the samples, and the correlation coefficients (r) should fill in the matrix. The probes will not actually be part of the matrix at all.

**Comment by AlisonMcAfee** [comment]
sorry, I mean the structure of the data frame that cor is executed on

**Comment by swils6** [comment]
Oh the sample names are the colnames and the probes are the row.names with gene expression filling in the matrix.

**Comment by aliceZhu** [comment]
Yep, exactly the same as Sam described above. In case it helps, you could use the design info retrieved from design.txt to sort the order of samples based on the specified ranking criteria. Then you could use this sorted order of samples (obtained from design info) to arrange the columns (one = 1 sample) of your probe data file (read from data.design). Thus, your input file into cor will have probes on the rows, samples on the columns that are sorted in the order of time + treatment or the other way.

**Comment by AlisonMcAfee** [comment]
ok, I think I know how to go about doing it now. Thanks guys!

**Comment by AlisonMcAfee** [comment]
One more thing.. I have made a data frame with the samples as columns, and genes as rows, but I cannot use it in cor because it says it is not numeric.. even though the help says cor can take a data frame. How do I fix this?

**Comment by AlisonMcAfee** [comment]
oh by golly...got it using data.matrix

**Comment by aliceZhu** [comment]
yep, or as.matrix(your data frame)
