### ISSUE TITLE
Individual Report

### ISSUE THREAD

**Issue by lijingyiran** [STAT540-UBC/Discussion#401]
Hi @wvictor14 @jafarzadeh91 , I think that I read an announcement at some point saying that each group member will be assigned to answer a specific question in his/her individual report? I can't find the announcement now so I just wanted to ask to make sure. If this is the case, do you know when the questions will be posted? Thanks.

**Comment by saramostafavi** [comment]
Hi @lijingyiran 
We will send your group one question (ie., each group gets 1 question). We will give you the question within ~30hrs of getting your documents (pptx + text that goes with it). Each group member needs to answer the question in their individual report. Please read wesbite https://stat540-ubc.github.io/subpages/group_project_rubrics.html
Information has been updated.
