### ISSUE TITLE
question on GitHub repository

### ISSUE THREAD

**Issue by willhahah** [STAT540-UBC/Discussion#403]
Hi,

I had a minor question on GitHub repository:

"**Analysis and results (5 pts)**

1. Think of it as a technical report of your presentation. Add brief comments and text throughout explaining the aim and conclusions of each part. You do not need to talk about all the analysis you have done but make sure you are addressing the important files, such as “inputs” (e.g. the dataset(s) you analyzed) and “outputs” (e.g. plain text files of your key statistical results or PDFs of your main figures)

2. Make sure your code is readable and could be run by instructors. So, it is necessary to provide valid addresses for the files you use in your scripts. Add comments for different chunks of your code and document it."
 
I am a little confused by the first requirement above, should this part be included in different files, or do we need a separate file to explain analysis and results, or the doc file we submitted for the presentation was already enough...

Thanks for clarification in advance~

@wvictor14  @jafarzadeh91  @saramostafavi

**Comment by jafarzadeh91** [comment]
Hi,

You can have your analysis across different rmd files. make sure each folder has an appropriate readme to help us navigate through different analyses and files.
In general, your Analyses should be understandable/reproducible for a person seeing your repo outside your team.

Thanks

**Comment by willhahah** [comment]
I see, thank you~
