### ISSUE TITLE
Let us know of any unmarked submissions

### ISSUE THREAD

**Issue by wvictor14** [STAT540-UBC/Discussion#404]
Hi students,

Let us know by commenting on this thread if you have not received a grade for any submission (seminars, assignment, paper review, individual report). We are done marking and have released all grades, except for the oral presentation.

Victor and Sina

**Comment by jimmyliu1326** [comment]
Didn't get a grade for Seminar 2c: https://github.com/STAT540-UBC/zz_Liu-Jimmy_STAT540_2020/issues/3

**Comment by LilyYuanXia** [comment]
Hi TAs,

Thanks for your great work. Just want to know where to check the grades for group Github repository?

Sincerely,
Lily

________________________________

**Comment by rstubbins** [comment]
Hi @wvictor14 and @jafarzadeh91 

My seminar 3 does not appear to have been marked. Thanks.

**Comment by dy-lin** [comment]
I did not receive a grade for seminar06. Are we supposed to also already have a mark for our group project GitHub Repository (10 points)?

**Comment by mksm1228** [comment]
Hello,

Could you please see my request for a remark of the analysis assignment?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by awakenedhaki** [comment]
I started making the API wrapper. Will have it done by tomorrow, plus updating the data I have scraped with what they have posted since then. 

 

Have to catch up on some other work, since I have a meeting on Tuesday.

**Comment by SaelinB** [comment]
Hello, 

I don't have a grade for my analysis assignment yet

**Comment by rachmiller** [comment]
Hi, 
I appear to be missing a grade for seminar 4

**Comment by wvictor14** [comment]
The group grade have not been released yet. We'll get to your seminars and assignment grades this week

**Comment by nikita-telkar** [comment]
Hi, my Seminar 1 assignment hasn't been marked

**Comment by jafarzadeh91** [comment]
@nikita-telkar 
please check your repo. Thanks

**Comment by jafarzadeh91** [comment]
@rachmiller 
please check your repo. Thanks

**Comment by jafarzadeh91** [comment]
@jimmyliu1326 
please check your repo. Thanks

**Comment by jafarzadeh91** [comment]
@rstubbins 
please check your repo. Thanks

**Comment by jafarzadeh91** [comment]
@dy-lin 
please check your repo. Thanks

**Comment by jafarzadeh91** [comment]
@mksm1228 
please check your repo. Thanks
@SaelinB 
please check your repo. Thanks

**Comment by SSAMRA14** [comment]
Hello, I don't see a mark for seminar 1.

**Comment by Sihaoyu1220** [comment]
Hi TAs, please check my request for a remark of the analysis assignment. Thanks!

**Comment by wvictor14** [comment]
@SSAMRA14 I posted your grade in your repo

**Comment by mksm1228** [comment]
Hello, @jafarzadeh91, just one more minor concern... could you please check my repo?
