### ISSUE TITLE
Seminar 6, plotting developmental stage t-statistic

### ISSUE THREAD

**Issue by mas29** [STAT540-UBC/Discussion#41]
For this part of the seminar, 

"Consider the effects associated with developmental stages P2 and P10. Scatterplot the t statistics for the test that the P2 effect is zero against that for P10.",

I'm writing the following code, and plotting it, but it turns out to be a weird X-shaped scatterplot.

x <- topTable(wtEbFit, coef = grep("devStageP2", colnames(coef(wtEbFit))), number = Inf, adjust.method="BH")$t
y <- topTable(wtEbFit, coef = grep("devStageP10", colnames(coef(wtEbFit))), number = Inf, adjust.method="BH")$t
plot(x,y)

Am I doing something wrong?

**Comment by aliceZhu** [comment]
Did you get the same result for the 63rd probe and number of hits in the previous sections? If yes, try use xyplot: xyplot(x~y), and see how it goes.

Here is the sample code for this part
P2Hits <- topTable(wtEbFit, coef = "devStageP2", n = Inf, sort = "none")
P10Hits <- topTable(wtEbFit, coef = "devStageP10", n = Inf, sort = "none")
xyplot(P10Hits$t ~ P2Hits$t, aspect = 1,
       xlab = "t-statistic for P2 effect",
       ylab = "t-statistic for P10 effect",
       xlim = c(-20, 16), ylim = c(-20, 16),
       panel = function(x, y, ...) {
         panel.smoothScatter(x, y, nbin = 100, ...)
         panel.abline(a = 0, b = 1, col = "orange")
         })


the diagonal line is added in the panel part. Hope that helps

**Comment by mas29** [comment]
Thanks, all I had to do was add the "sort = "none"". Why does that make a difference?

**Comment by gcohenfr** [comment]
Not sure if you now understand why you need “sort=“none””. If you don’t specify “none”, the results within each analysis are ordered by p-value. A gene with a significant effect in one analysis may not have the same significance in the other analysis. Thus, if genes are re-ordered, you are plotting the t-stat of one gene against the t-stat on another gene, hence the strange shape! You can always peek at the results of topTable before plotting, e.g., head(x) and head(y) in your code should have different row names. G

**Comment by mas29** [comment]
Thanks, Gaby, I understand.
