### ISSUE TITLE
Q3

### ISSUE THREAD

**Issue by AlisonMcAfee** [STAT540-UBC/Discussion#42]
Hello, 

I would like to clarify something in question 3. The question says "Fit a linear model, modeling expression level of each probe using treatment as a single covariate." 

To me, this is asking for something like this: lm(gExp ~ gene + Treatment, data); however, this is too much for my computer to handle. Am I interpreting this wrong?

Thanks

**Comment by wdurnoUBC** [comment]
That does look like too much work! You're right, you should interpret the question differently. You need to  use the "limma" library to run a batch of f-tests, one per each gene. Any students with this interpretation should check out seminar 6 for an introduction.
http://stat540-ubc.github.io/sm06_highVolumeLinearModelling.html

**Comment by AlisonMcAfee** [comment]
Ahh of course.. thank you

**Comment by AlisonMcAfee** [comment]
Another question... I have written the following code to extract the top 3 most differentially expressed genes between Treatment and Control (below). When I plot the topGenes (should be the three most differentially expressed), they are all just very highly expressed genes with no difference between the treatment and control. I am thinking this means there's something fishy about my contrast matrix, but I don't know what? Thanks.

data <- read.table("data.txt")
des <- read.table("design.txt")
library(limma)
suppressPackageStartupMessages(library(dplyr))

desMat <- model.matrix(~ Treatment + 0, des)
desMat
Fit <- lmFit(data, desMat)
cutoff <- 0.05
colnames(coef(Fit))
cont.matrix <- makeContrasts(treat = Treatmentcigarette_smoke - Treatmentcontrol, levels = desMat)
kFitCont <- contrasts.fit(Fit, cont.matrix)
kebFit <- eBayes(kFitCont)
EB <- topTable(kebFit, p.value = cutoff, n = Inf)
topGenes <- rownames(EB[1:3,])

**Comment by AlisonMcAfee** [comment]
Actually, I shouldn't need a contrast matrix at all for such a simple comparison.. but using the code below I run into the same problem.

desMat <- model.matrix(~ Treatment, des)
Fit <- lmFit(data, desMat)
cutoff <- 0.05
ebFit <- eBayes(Fit)
EB <- topTable(ebFit, p.value = cutoff, n = Inf)
topGenes <- rownames(EB[1:3,])

**Comment by aliceZhu** [comment]
Hi Ali, try specify which coef you are testing:
add  coef = grep("Treatment", colnames(coef(ebFit))) to your topTable 

If you do str(ebFit), you will see that you have both "(Intercept)" "Treatmentcontrol". If you don't specify the coef when you call topTable, both will be taken for the calculation. Seminar 6 touches upon this difference as well.

**Comment by AlisonMcAfee** [comment]
Ah, ok thanks. I thought that was just for the older version: 

"If you are using the older version, let's take more care and specify explicitly the coefficients we want to test for equality with zero. Recall that one can specify these by number but I recommend doing this by name" etc.

**Comment by AlisonMcAfee** [comment]
Sorry.. I hate to be a broken record, but changing the last two lines of the above code snippet to
"
hits <- topTable(ebFit, coef = grep("Treatmentcontrol", colnames(coef(ebFit))))
topGenes <- rownames(hits[1:3,])
" 

doesn't solve the problem :(
I don't know what I'm doing wrong! 

Thanks.. Sorry for asking so many questions. I know it is probably something really simple that I have missed.

**Comment by aliceZhu** [comment]
Can you give me the number of hits you have for p value cutoff of 1e-3, and the probe names of your top 6 hits?   so I can compare to mine to see if we are on the same track

**Comment by AlisonMcAfee** [comment]
For p.value (uncorrected) I have 805 and the top 6 hits are:
200779_at 
202912_at 
214696_at 
223394_at 
223774_at 
209020_at

**Comment by aliceZhu** [comment]
actually that's the same as what I and the other TA @wdurnoUBC got. Maybe it's something with your plotting rather than the probes themselves. Did you make a tall matrix merging the design and data? Just like seminar 6, with such tall matrix, each row has the sample info (time, treatment) and probe and expression value. Thus, you can call expression~Treatment when you use stripplot. Maybe you could bring your code and figures to the seminar next Wed?

**Comment by AlisonMcAfee** [comment]
Hmm... interesting. My plots can be found in hw1 on my repo (https://github.com/STAT540-UBC/zz_mcafee-alison_STAT540_2015/blob/master/hw1_q1-2a.md)

and the code to generate the figures is below. I was expecting the means to be very different between treatment and control. 

top <- ggplot(newDat, aes(Treatment, gExp)) + ylim(0,15) + geom_point() + facet_wrap(~ gene)+ stat_summary(fun.y = mean, geom = "point", shape = 20, size = 6, colour = "red"))

**Comment by AlisonMcAfee** [comment]
and the newDat format is below:

      ExternalID       Treatment time     gExp      gene
2796   GSM270890 cigarette_smoke  2_h 13.81002 200779_at
3561   GSM270895 cigarette_smoke 24_h 11.80828 202912_at
7769   GSM270894 cigarette_smoke 24_h 10.50249 214696_at
25533  GSM270873         control  1_h 13.70265 200779_at

By the way thanks for answering so quickly; this is really helpful

**Comment by aliceZhu** [comment]
no worries, Evan and I will look into it, and we can discuss about it during seminar
