### ISSUE TITLE
Error when pushing to repository

### ISSUE THREAD

**Issue by Madelinehazel** [STAT540-UBC/Discussion#46]
My computer crashed recently, and when I restarted it, I had to restart RStudio. I opened up the RProject that was previously connected to my Github repository, and attempted to commit and push a file to my repo. I get this error message: 

"Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists."

I have tried to troubleshoot this but haven't had much success. Does anyone have any suggestions?

**Comment by aliceZhu** [comment]
Are you using Mac or Windows?

Maybe you could try this help page on github:

https://help.github.com/articles/error-permission-denied-publickey/

You could bring it to the seminar next Wed, and we can take a look at it. Or if you want something working right away, you could download SourceTree
