### ISSUE TITLE
FDR

### ISSUE THREAD

**Issue by swils6** [STAT540-UBC/Discussion#48]
One of the questions is: "What is the (estimated) false discovery rate of this "hits" list? How many of these hits do we expect to be false discoveries?

I'm a little confused as to what you want us to do. Do you want us the estimate the average FDR in our hit list, or just explain what setting our hit list to FDR<0.05 means?

Thanks!

**Comment by wdurnoUBC** [comment]
The "hits" list refers to the top 50 hits. FDR is a function of the number of hits you accept. So yes, estimate the FDR and the expected number of false discoveries.

Students seeking clarification on FDR can see the lecture notes for more details.
http://stat540-ubc.github.io/lect11_multipleTesting.pdf

**Comment by swils6** [comment]
In the top 50 hits we originally set out fdr<0.05. Is there a reason why this would change when looking at the top 50?

**Comment by dchiu911** [comment]
Regarding this question, are we expected to use the `qvalue` package?

**Comment by wdurnoUBC** [comment]
@dchiu911, Limma does all the correction you need.

**Comment by gcohenfr** [comment]
Look at the list of genes with fdr<0.05 and compare it with the top-50 list. Are these lists the same?

**Comment by dchiu911** [comment]
Isn't the top-50 hit list just a subset of the list of genes with fdr<0.05?

So are we being asked, (out of the top 50), what is the estimated FDR;
How many we expect, (out of the top 50), to be FD's?

**Comment by gcohenfr** [comment]
> So are we being asked, (out of the top 50), what is the estimated FDR;
> How many we expect, (out of the top 50), to be FD's?
> 
Correct, this is exactly what is being asked.

**Comment by dchiu911** [comment]
Ah thanks! I just had an enlightenment!

**Comment by dtebaykin** [comment]
Maybe I am misunderstanding what FDR is. I thought that if we have 100 hits at FDR < 0.05 and the highest FDR amongst those hits is 0.01 then we should have on average 1 false discovery in that set of 100 hits.
