### ISSUE TITLE
HW1 question - 3c

### ISSUE THREAD

**Issue by catbyrne** [STAT540-UBC/Discussion#50]
Hi, I'm trying to figure out how to make the scatter plot for question 3c. I can't quite figure out what it would look like. What I picture is a strip plot with each of the samples organized by treatment on the x-axis, and then gene expression on the y-axis. However, the question asks for a "scatter plot" not a "strip plot" so I'm not sure how this would work. Any suggestions?

**Comment by aliceZhu** [comment]
it may help to read the Stripplot section in seminar 3: http://stat540-ubc.github.io/sm03c_lattice.html 

Please notice that in this seminar , it says "A stripplot is a univariate scatterplot".

**Comment by catbyrne** [comment]
Thanks Alice!

**Comment by tshalev** [comment]
Does anyone have any idea how to make a connecting line between means in ggplot2? I can do it in lattice but I like ggplot2 better. I have read around and I've only seen it work with qplot; has anyone been able to do this in a regular scatterplot?

**Comment by aliceZhu** [comment]
This page may help, please take a look at the last plot, and the arguments inside geom_line():

https://learnr.wordpress.com/2009/07/02/ggplot2-version-of-figures-in-lattice-multivariate-data-visualization-with-r-part-3/

**Comment by tshalev** [comment]
OK I figured it out... what you need to do is create a stat_summary argument as such:

ggplot(top_bottom_dat, aes(x = time_numeric, y = g_exp, group = time_numeric, colour = Treatment)) +
  facet_wrap(~ gene, scales = "free_x") +
  geom_point() +
 **geom_smooth(method = "lm", formula = y~x, aes(group = 1)) +**
  theme(panel.grid.major.y = element_blank())

This will draw the line connecting the means (for anyone who was wondering).

**Comment by tshalev** [comment]
OK I figured it out... what you need to do is create a stat_summary argument as such:

ggplot(top_bottom_dat, aes(x = Treatment, y = g_exp, colour = Treatment, group = Treatment)) +
facet_wrap(~ gene, scales = "free_x") +
geom_point() +
stat_summary(fun.y = mean, geom = "point", shape = 4, size = 7) +
**stat_summary(fun.y = mean, geom = "line", aes(group = 1)) +**
theme(panel.grid.major.y = element_blank())

This will draw the line connecting the means (for anyone who was wondering).
