### ISSUE TITLE
Density curve? HW01

### ISSUE THREAD

**Issue by chainikonwar** [STAT540-UBC/Discussion#53]
@gcohenfr @aliceZhu  For Q2c (HW01) to plot a histogram of expression values for each treatment condition. I was a thinking to overlay the histogram with a density curve so that the similarity in distribution is more obvious. But I was thinking if that deviates from what the question is actually asking? Or is it still relevant? I hope this is a question I can ask, if not please ignore!

**Comment by gcohenfr** [comment]
Your approach would be appropriate. The most important thing is your interpretation of the results.

**Comment by chainikonwar** [comment]
Thank you
