### ISSUE TITLE
topTable() for single covariate models 

### ISSUE THREAD

**Issue by tanjahoegg** [STAT540-UBC/Discussion#56]
As discussed in the lab earlier today with @aliceZhu, I just wanted to confirm that in the case of a linear model with only one explanatory variable, time for instance, it's ok not to specify the "coef" argument in topTable() as the global F-test results in the same p-value as the test for the slope parameter. Is this correct?

**Comment by AlisonMcAfee** [comment]
yes! It is only with the old version or when you're modelling more than one variable that you need to specify coef. 

But I'll let Alice confirm too.

**Comment by aliceZhu** [comment]
for the default when no coef is specified, the new version removes the intercept when calling topTable. Thus, if your covariate has 2 levels, let coef=2 or don't specify coef will give you the same answer, theoretically. But I haven't tested it on real data yet. If you are not sure, the safest approach is get the hit results for both options, and compare the results in terms of probe list, p-value, etc.

**Comment by tanjahoegg** [comment]
Thanks guys!

**Comment by gcohenfr** [comment]
you are right @tanjahoegg, if you don't specify `coef=`, the global F-test reported (i.e., a test of full vs intercept only models). In the cases that you and @aliceZhu pointed out, as with the lm() function, those F-tests are equivalent to the t-tests of the unique coefficient in the model.

**Comment by dtebaykin** [comment]
I have been wondering - what is the best test to check whether 2 samples of similar lengths (say, a bunch of p-values) are drawn from the same distribution? Would t-test do the trick? I guess another way to ask this is: How close are two different continuous variable distributions?

**Comment by tanjahoegg** [comment]
A t-test only lets you assess whether the two distribution have different means (assuming normality for both distributions). Otherwise, there are tests that take the whole distributions into account, Kolmogorov-Smirnov test or Cramer-von Mises test are two examples.
