### ISSUE TITLE
Code mechanics

### ISSUE THREAD

**Issue by AlisonMcAfee** [STAT540-UBC/Discussion#57]
Hi, I'm just wondering if we are being marked on not only if our code gets the job done, but also how 'pretty' it is? Like fewest lines possible, efficiency, etc.

Cheers

**Comment by gcohenfr** [comment]
The main goal is to write a right code that you understand and master. However, as stated in the "Evaluation" section of HW1, the overall presentation and mechanics is worth 5 points, with full points awarded if it's exceptional. So if you are done, push yourself towards getting efficient and clear codes!! Add explanations and interpret your results. Convince us that you have done an amazing job!!
