### ISSUE TITLE
Problem with function call %>%

### ISSUE THREAD

**Issue by maxala** [STAT540-UBC/Discussion#58]
I'm trying to run the following code:

```{r}
combined  <- cbind.data.frame(mDes, t(mDat))

sort_time  <- combined %>%
  arrange(num_time,treatment) 
```
but it gives me an error:
Error: could not find function "%>%"

It seems like a simple function that should work but it doesn't for me. I've been on this trying to load different packages and searching the web but I just can't seem to get it to work... Anyone with a similar problem or who knows what I'm missing?

**Comment by aliceZhu** [comment]
hi@maxala, you need the dplyr library for that %>%. For the plyr, there is no such stepwise operator, everything works in a nesting format.

This should work now with the code below, please note that I changed your "treatment" to "Treatment" which is the col name specified by the input design.txt

combined  <- cbind.data.frame(mDes, t(mDat))
colnames(mDes)
install.packages("dplyr")
library(dplyr)
sort_time  <- combined %>%
  arrange(time,Treatment)

**Comment by maxala** [comment]
I somehow missed to load dplyr. Thanks for the help!

Regarding the "treatment", I intentionally changed it to lower case so that everything starts with a lower case.
