### ISSUE TITLE
Final project proposal: due March 6

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/Discussion#60]
Due March 6, you have to review, and in some cases expand, your project proposal (1 page). I've added some additional guidelines in the "Assignment" tab of the course page. Also, incorporate the feedback given to your group by instructors and TAs.

**Comment by dtebaykin** [comment]
We do not have to include everything we want to do for our project into this proposal, correct? For example, at the moment we are aiming at a differential gene expression meta-analysis with possible extensions into classification analysis or principal component analysis.
