### ISSUE TITLE
How to display the mean values on plot generated by ggplot2?

### ISSUE THREAD

**Issue by hamzakhanvit** [STAT540-UBC/Discussion#61]
What options should I provide in the stat_summary section of ggplot2 to display the rounded off numerical values of the mean on my plot? @aliceZhu @wdurnoUBC

**Comment by hamzakhanvit** [comment]
Thanks figured it out.. :)

**Comment by aliceZhu** [comment]
hi @hamzakhanvit , in case you want to connect the mean values , one classmate also posted an issue related to yours:

https://github.com/STAT540-UBC/Discussion/issues/50

**Comment by hamzakhanvit** [comment]
Hi Alice!
I wanted to display the mean values as rounded off numbers on my plot. I figured it out by using geom="text" in the stat_summary section. Thank you @aliceZhu
