### ISSUE TITLE
Do the lmfit p-values correspond to f-test or t-test?

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#63]
`lmfit` basically fits a linear model for each gene.

I believe that the `f-test` measures the goodness of fit of the whole model whose covariates are, say Treatment and Time, whereas the `t-test` is meant to be computed for each individual covariate telling us whether we can can reject the hypothesis that the parameter $$\beta$$ for that covariate is zero.

However, `lmfit` shows p-values for each covariate, for each gene. Does that mean the results we get from `lmfit` are basically t-tests ?

Thanks.

**Comment by gcohenfr** [comment]
If you get p-values for each covariate, these are t-tests. If you are looking at a general tests, involving many coefficients simultaneously, these are F-tests. In any case, you need to regularize these using the whole limma machinery to reduce the number of false positive that may arise in small sample size data sets.

**Comment by IssamLaradji** [comment]
Thank you for the helpful explanation!.
