### ISSUE TITLE
Design matrix for quantitative covariate (Q4)

### ISSUE THREAD

**Issue by amanji** [STAT540-UBC/Discussion#64]
I'm slightly confused as to how this is supposed to look. If we treat each time point as a categorical co variate then we should see one column of dummy variables (less one for the baseline) corresponding each category. In treating time as a quantitative co variate, is it normal to see the design matrix with a single column for time and numbers corresponding the time count (i.e. not 1's and 0's)? Im guessing the baseline is at 0 hours here.

Thanks for your help.

**Comment by amanji** [comment]
Looking at slide 6-7 From Lecture 09, It seems like what I'm observing is correct.

**Comment by aliceZhu** [comment]
the scenario is very similar to lecture 9 (they change the categorical covariate dev_stage to quantitative covariate, and then fit the gene expression against the quantitative dev_stage).Thus, their dev_stage is just like time in this hw question. In that example of the lecture slides, it would be helpful to compare the design matrix  obtained from these 2 approaches. That comparison result can be extrapolated to this hw1 question

**Comment by amanji** [comment]
Thank you for your help :)
