### ISSUE TITLE
Is the question in Q4b part of the hint ?

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#65]
The last part of Q4b reads,

`Hint: limma estimated the slope of this line. This plot should look different from plots in Q1, why? `

Is the question here part of the hint ? if not, in what sense should we compare the two plots ?

Q1 asks for a way to display the average expression values (I used boxplots), whereas Q4b requires fitted regression lines for the plot. In my case, it seems they are trivially different. 

Thanks in advance.

**Comment by aliceZhu** [comment]
This question helps you to figure out what the 4b is looking for. So It's always nice to include your justification (such as the ones you brought up above) in your explanation for your plot.

**Comment by gcohenfr** [comment]
Some people may use scatter plots in Q1 to illustrate gene expression data and averages. Reading Q1 again, it doesn't specify what kind of plot you need to use. Thus, as long as you understand what you are plotting and describe your plots correctly you are fine. 

As Alice said, the hint was to differentiate the averages in a scatter plot in Q1 from a line in Q4. Thus, if you haven't done scatter plots in Q1, the last part of the hint does not apply to you
