### ISSUE TITLE
Proposal breakdown

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#67]
For the updated proposal, can we break it into two paragraphs ?

The first paragraph would describe the biological aspects of the project, and the second paragraph would describe the statistical approach that we would like to go about.

Thanks.

**Comment by saramostafavi** [comment]
yes, this would be fine. But you want to make sure to motivate the problem from the beginning. Not fun to read a whole paragraph without knowing what the goal/purpose of the project is.

**Comment by IssamLaradji** [comment]
Thanks for the helpful answer.
