### ISSUE TITLE
Question regarding division of labor

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#68]
The proposal asks us to mention the division of labor. However, as a team, we decided to work on each part of the project together as a whole group. This will help us group together our perspectives and ideas to achieve a consistent high quality standard development throughout the project.

Therefore, we would like work on each aspect of the project together, would that be okay ? or is it necessary to have the tasks divided between us.

Thanks.

**Comment by ppavlidis** [comment]
Gaby should probably jump in, but my two cents:

You may have over-interpreted "division of labour". Everybody must do their projects as a group (maintaining a high quality is a great motive to collaborate closely), but you can't all work on the same figure simultaneously, for example (someone has to type the commands; what will everybody else do?). Hopefully we can agree that's a little silly; but nor do we mean that you have to do your part without discussion with the group.

The goal of asking you to describe the division of labour is to avoid situations like one person doing most of the work, not to enforce some style of collaborating. Just make sure each of you can document what you contributed.

**Comment by IssamLaradji** [comment]
Thank you for the helpful reply!
