### ISSUE TITLE
Group project - Spruce stone cell project (want to join our group?)

### ISSUE THREAD

**Issue by jkbooth** [STAT540-UBC/Discussion#7]
Coniferous trees are susceptable to attack by white pine weevil. Weevil infestation has created a blight in forests, and is damaging to Canada's natural beauty and the forestry industry in BC.
 
Some spruce are resistant to weevil attack. Although the mechanism of resistance is unknown, a recent study found that resistant trees have more stone cells (also called sclerenchyma, the cell type that gives pears a gritty texture).

In order to investigate possible contribution of stone cells to weevil resistance, our lab recently isolated RNA from stone cells from both susceptible and resistant trees for transcriptome analysis. We would like to compare transcripts from stone cells of both genotypes, to cast light on the mechanisms of resistance. We have two genotypes, 2 tissue types each, and 3 biological replicates for each genotype x tissue type.

We have two students from the genome science program already interested in this project (me and @tshalev). Anyone else want to join?

**Comment by cronie1** [comment]
As a plant biologist, I feel it's my duty to hop on board.

**Comment by dankehila** [comment]
I'm interested too!

**Comment by ivanhartling** [comment]
this is Ivan, can I join the group?

**Comment by jkbooth** [comment]
Ok, looks like we've got a group of 5 with me, @tshalev @cronie1 @dankehila and @ivanhartling .

I'm going to close this issue.
