### ISSUE TITLE
github html preview link broken for homework

### ISSUE THREAD

**Issue by hamzakhanvit** [STAT540-UBC/Discussion#70]
Hi,

The github html preview link that I had included in my README file by prepending http://htmlpreview.github.io/? to the link of my raw html homework file doesn't seem to work anymore. Although it was working before, but is currently returning a "cannot load file" error. Is there anyone else facing a similar issue?

**Comment by amanji** [comment]
Yeah same issue, I think the URLs that are generated for your raw html output have tokens that expire after a certain period of time. The only option, I believe, is to generate another raw html output for your homework and append the `http://htmlpreview.github.io/?` in front of the URL that's generated for it.

**Comment by jennybc** [comment]
Yes the tokens for HTML preview of files in private repos are perishable. This is why it's best to consider the Markdown the version you're preparing for the instructor and peer eyeballs. But if you want to use fancier HTML stuff, then you'll have to hope that others are energetic enough to copy the URL for the raw html and to go `http://htmlpreview.github.io/?` themselves. Obviously, leave instructions for them!

**Comment by jennybc** [comment]
I've written up all sorts of tips about making a GitHub repo as browsable as possible here:

http://stat545-ubc.github.io/bit006_github-browsability-wins.html

**Comment by hamzakhanvit** [comment]
Yes, the Markdown version is totally fine. Thanks Jenny and Akiff.

**Comment by aliceZhu** [comment]
yep, the token expires after a while. But we are marking your assignments using both rmd and md files, so don't worry about losing mark for that. Thanks Jenny for the tips!
