### ISSUE TITLE
low depth data

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/Discussion#72]
Q4 in hw2 requires a low depth dataset. This dataset is not available in the example folder yet. I will upload it soon.

**Comment by gcohenfr** [comment]
DONE! the dataset for Q4 is now in the repository. All datasets for hw02 are in examples/yeastPlatforms/data

**Comment by mas29** [comment]
Why are there more genes in the low coverage data vs the high coverage data? (7126 genes in low coverage, 6542 in high coverage)?
