### ISSUE TITLE
Homework legibility

### ISSUE THREAD

**Issue by wdurnoUBC** [STAT540-UBC/Discussion#74]
Hi everyone!
Please make an effort to keep your homework legible. Do not answer questions using code comments or 'print'. Take advantage of R Mardown's wonderful typesetting. Also, while plots must communicate their content clearly, they should also be impressive.

**Comment by IssamLaradji** [comment]
Thanks. I wish this was explicitly stated before the HW1 submission deadline. As this is my first time using `R` Markdown, I thought `print` is the best way to answer questions.

**Comment by wdurnoUBC** [comment]
Hi @IssamLaradji 
I want to emphasize legibility. Your documents just need to be easy to read. Writing in comments and prints is just a slippery slope. In your case, I didn't deduct marks for it. That said, I cannot promise any final grading details until we send it back to you.

**Comment by IssamLaradji** [comment]
Hi @wdurnoUBC 
Thanks for the clarification!
Regards.

**Comment by rmcclosk** [comment]
Do you prefer that we copy the questions into our write-up, or not?

**Comment by chainikonwar** [comment]
@wdurnoUBC @aliceZhu  
As @rmcclosk had asked I also wish to know that do you prefer that we copy the questions into our assignments or not ?
