### ISSUE TITLE
Seminar 10 getting data from GEO

### ISSUE THREAD

**Issue by swils6** [STAT540-UBC/Discussion#75]
I'm hoping someone has an idea how to fix this problem.
I'm using the code in seminar 10 to retrieve the data from GEO, however every time I try to do this, it times out. It does however create a temporary file which does not allow me to try to reload the data again, without deleting it first.

If anyone has an idea as to why this is happening and how to fix it, it would be much appreciated.

Thanks

**Comment by aliceZhu** [comment]
@swils6  Does it happen when you call `datgeo <- getGEO('GSE23177', GSEMatrix = TRUE) `? could you paste the error message here?   Did the same error message happen when you use `getGEO` in seminar 8?

**Comment by swils6** [comment]
Yes, it happens just passing datgeo <- getGEO('GSE23177', GSEMatrix = TRUE). No it didn't happen in seminar 8.

Here's the error:
Error in download.file(sprintf("ftp://ftp.ncbi.nlm.nih.gov/geo/series/%s/%s/matrix/%s",  : 
  cannot open URL 'ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE23nnn/GSE23177/matrix/GSE23177_series_matrix.txt.gz'
In addition: Warning message:
In download.file(sprintf("ftp://ftp.ncbi.nlm.nih.gov/geo/series/%s/%s/matrix/%s",  :
  InternetOpenUrl failed: 'The operation timed out
'
