### ISSUE TITLE
Normalized data

### ISSUE THREAD

**Issue by rmcclosk** [STAT540-UBC/Discussion#76]
Homework 2 says that the data in "GSE37599-data.tsv" are already normalized. But the means and standard deviations of the columns are all different.

```
> d <- read.table("GSE37599-data.tsv", header=T, row.names=1)
> apply(d, 2, mean)
      b1       b2       b3       c1       c2       c3 
4.747446 4.735771 4.740523 4.747134 4.730736 4.745378 
> apply(d, 2, sd)
      b1       b2       b3       c1       c2       c3 
3.441807 3.395179 3.396159 3.429934 3.400960 3.443093
```

Are we supposed to standardize the data ourselves? I don't see this in the question anywhere, but maybe I'm missing something obvious.

**Comment by gcohenfr** [comment]
Normalization and standardization are different things. The RMA normalization makes quantiles equal, not the mean and SD. As you noticed these are close but not exactly the same. I am not sure which method you are using that requires further standardization. You don't need to re-normalized though.

**Comment by rmcclosk** [comment]
Thanks for clearing that up @gcohenfr. The reason I thought it was necessary was because I obtained a very large number of hits using limma, almost every gene. I assumed this was because the  "c" columns have a slightly higher average expression than the "b" columns. I guess I made an error elsewhere in my analysis.
