### ISSUE TITLE
HW2 Q1c

### ISSUE THREAD

**Issue by mgottl04** [STAT540-UBC/Discussion#77]
For Q1c, there is something of a breakdown in the usual numbering system for question sub-problems, at least as far as I understand it. 

There is a lot of text between the header of Q1c and point 'i.' Is the description above 'i' meant to be an overview of where Q1c is going, or is what we need to do before 'i'?  I'm not sure if I should be filtering out the probes that don't have mappings before or after calling topTable. Clarification would be appreciated. Thanks!

**Comment by gcohenfr** [comment]
This is a good point and I was going to clarify it in a coaching doc  tomorrow. The most natural flow is to prefilter after calling topTable. That is, you first identify number of DE probes, you then filter to compare w other anlyses.

In all questions I added some text explaining the aim of the questions and where we are heading. Your analyses does not star there, you will answer to the questions below identify by bullets.

**Comment by gcohenfr** [comment]
Correction: in my previous comment I said: "you first identify number of DE probes, you then filter to compare w other analyses." This is still confusing so I updated my previous comment and made further clarifications in the coaching document available in hw02 folder of the class repository. 

The gene annotation should not affect the statistical tests of differential expression. Thus, as mentioned before and in the hw, you will first run lima, including the topTable() function, and then filter the results. To respond to Q1cii-iv and Q3, use the filtered set of results. In other words, your number of DE probes will contain only those with an FDR below threshold and matching a gene ID.

Hope this clarifies this point. Don't hesitate to ask again if it is still unclear.
