### ISSUE TITLE
helpful notes on using ML in 'real life'

### ISSUE THREAD

**Issue by saramostafavi** [STAT540-UBC/Discussion#78]
Hi all, 

I wanted to share an insightful blog post about being a machine learning "user": http://ml.posthaven.com/machine-learning-done-wrong

A lot of the issues discussed are relevant for bioinformatics. Good to keep these in mind for evaluating bioinformatics/computational biology oriented papers, even if you are not a practitioner yourself. 

Enjoy!
Sara

**Comment by jennybc** [comment]
Nice post! Another thing I frequently see done wrong in machine learning is a failure to make tons of plots exploring the data and the fitted model or predictions or what have you. There seems to be a culture of focusing only on performance measures, either in a table or a figure, and rarely bringing same level of scrutiny to joint exploration of the *data* and the model.
