### ISSUE TITLE
Are there anyone still having problem setting up git with Rstudio?

### ISSUE THREAD

**Issue by aliceZhu** [STAT540-UBC/Discussion#8]
Hi guys,

Since you soon need to submit your seminars and homework to the remote personal github repository, it's important that you get the git configuration settled down asap. If you still have problems, please 
open a new issue in your private personal github repository:

1. go to your private personal github repo created by Jenny, should be sth like:
https://github.com/STAT540-UBC/zz_yourAccountName_STAT540_2015
2. On the repo home page, in the column on the right hand side, click "Issues"
3. in the subsequently linked page, click the green "New issue" button.
4. in the subsequently linked page, put "Git-Rstudio Configuration Problem" in title,
        inside the content of the new issue, please leave your name, email, your OS (version number too, please), and a brief summary of what trouble you encounter (paste error messages if there is any). 
5. tag me (@aliceZhu ) and Evan(@wdurnoUBC) in your issue content, so we can get notified.  

Thus, we TAs can group them accordingly and fix them asap. For Frank and Veronique, I got your problems recorded, so don't worry about replying this issue.  

~Alice

**Comment by jennybc** [comment]
Since this is public repo, students may not want to put their email addresses here. They could also open an issue in their private repo and tag the TAs. Maybe @aliceZhu or @wdurnoUBC should write out instructions for that?

**Comment by aliceZhu** [comment]
thanks Jenny! that's changed to your suggested approach now

**Comment by gcohenfr** [comment]
@aliceZhu, are all repositories working well? if so, we can close this issue

**Comment by aliceZhu** [comment]
@gcohenfr  It seems so based on what I observed in the lab, except there is one student having trouble in pushing contents to the repo (it worked for him before, but he said (since yesterday) his push wiped out some of his previous submits). There is still a couple empty repo (readme file is not initialized either) for some students, not sure whether it's due to technique issue. I will check with them by the end of this week, and if it's all settled, I will close this topic
