### ISSUE TITLE
Silhouette score w.r.t number of clusters

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#82]
Why is it in some cases that the Silhouette score increases with larger number of clusters ?

As in the red circle in the plot below, the average Silhouette score increased at some point. However, the Silhouette score is computed as a function of dissimilarities within and between clusters which always decrease with larger number of clusters.  

It would be helpful if someone could provide an explanation as to why  the Silhouette score sometimes increases as the number of clusters increase.

![222](https://cloud.githubusercontent.com/assets/3382128/6886718/56bcaba6-d5fc-11e4-8ffd-5a3e9bfba6a6.PNG)

Thank you!

**Comment by wdurnoUBC** [comment]
There's a lot of moving parts in that equation. The best argument I can produce is that, while it may be a function of numbers which may reduce, it's also a ratio of those reducing numbers. So it's less important that they be decreasing and only that the right numbers be decreasing relatively--if one wanted to design it to be a decreasing statistic, that is. Having such statistics decrease may be useful, but a guarantee that it decreases is something which the author must strive for by applying theory strategically.
ftp://164.41.49.96/Projects/VANT_AsaFixa/Dissertacao_Roberto/Artigos_PDF/1987/1987_Rousseeuw_Silhouettes%20A%20graphical%20aid%20to%20the%20interpretation%20and%20validation%20of%20cluster%20analysis.pdf

**Comment by IssamLaradji** [comment]
Thank you for the explanation!
