### ISSUE TITLE
Group project: final deliverable

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/Discussion#84]
Group project final deliverable guidelines can be found at the end of Assignments (scroll down). I've posted a rubric [here](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/posterRubric2012.pdf) that you can use to review your poster before printing.

**Comment by jkbooth** [comment]
I think that link is broken (I get a 404).

**Comment by swils6** [comment]
I have a couple questions about the final deliverables
1. You want a revised proposal and a README file contatining summary of work, poster, and code; however, currently our README file is the proprosal- do you want us to just add the summary of the work or have a seperate file? I'm not sure how you want this organized.
2. You state you want everything that someone would need to recapitulate the results. However our dataset is too large for us to push to github, do we just state this?

**Comment by gcohenfr** [comment]
rubric is now in the repository. Thanks for pointing this out!

**Comment by gcohenfr** [comment]
@swils6 and @STAT540-UBC/students, these are good points. 

You can organize your repository as you want and think it is clear to your group others to host all the material related to the project and learn about you have done. However, your repository should contain all the pieces mentioned in the guidelines: summary, proposal, poster, code. One suggestion is to have a nice README.md file summarizing the project, your work, and results. This file can also contain links to important files or directories in your repository. The original proposal can be reviewed if through your analysis you made changes to the original plan (otherwise, you can leave it as is). The proposal can be a separate file in the repository (e.g., proposal.md) or you can integrate it to the README.md file if you see it fits.

Regarding your second point, I understand that some dataset may be too large or for some privacy issues you can't upload it. In that case, just mention this and describe as well as you can the dataset you are working with.

**Comment by gcohenfr** [comment]
One student raised a concern about the privacy of the individual report. These reports will be in your personal repository, thus they will be visible to all class. In general this report is your view and insight about the project work and results. The only point that can be delicate is the "concise summary of main role / contribution of each group member". 

If you think you have something to say in this field that you don't want to share with the rest, give a very general description in the report and send me a separate email with more details.

**Comment by rmcclosk** [comment]
@gcohenfr Is there a special issue format like with homework 2? I can't find any specific instructions.
