### ISSUE TITLE
R markdown project deliverable

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#87]
One of the project's deliverables is the R markdown.

However, since the project guidelines didn't state that `R` is required, we used a different programming language, python. 

Can we post the results (like plots and experimental scores) and links to the python code on the `R` markdown, instead ?

Thank you.

**Comment by gcohenfr** [comment]
Sure, no problem. Any explanation of what you did and the main results will work. 

Gaby

**Comment by IssamLaradji** [comment]
Thank you! 

--Issam
