### ISSUE TITLE
Sample code for getting started with seminar2 take-home problem

### ISSUE THREAD

**Issue by aliceZhu** [STAT540-UBC/Discussion#9]
Hey guys,

Some people asked me about how to make customized functions. Just in case you need help in this issue too, I made some sample code for you to play around below. This should help you getting started with seminar2 if needed. 

If you want to make a new function, try to lay out your code first in a procedural way. Then you could see if there is any reusable chunk of code. If there is, look for what argument it requires, then you can change it to a function. 

Please see the sample code here, hope that helps:
https://github.com/aliceZhu/STAT540_Seminar_ExampleCode/blob/master/calculateProbsInFunction.R

**Comment by jennybc** [comment]
We had several sessions on writing functions in STAT 545.

Look under "Writing your own R functions" in this topic list:
http://stat545-ubc.github.io/topics.html
