### ISSUE TITLE
Looking for a group to be included

### ISSUE THREAD

**Issue by RashedHUBC** [STAT540-UBC/Discussion#94]
Hello I am Rashed, doing my MSc in Biostatistics at the Department of Statistics, UBC. I am looking for a group to join with peoples from Bioinformatics/ any Biological subject/ Genomics. Please reply me if anyone is interested. Thanks.

Regards
Rashed

**Comment by emminic93** [comment]
I am in Genome Science and Tech. There's a couple of us looking for a stats person :)

**Comment by RashedHUBC** [comment]
Sure. We can discuss to form a group to work together.

**Comment by joeho604** [comment]
Hi Rashed,

I think I have spoken to you after the seminar on Wednesday. I'm a MSc student from the microbiology department (studying metagenomics of microbial communities). I would like to join your group. 

-Joe

**Comment by eclaks** [comment]
Hello Rashed, 

I'm the other Emma in the Genome Science and Technology program, researching clonal dynamics and heterogeneity in cancer at single cell resolution. Maybe the group of us could discuss project pitches after class on Monday, and summarize them here?

**Comment by RashedHUBC** [comment]
Hello both Emma and Joe,
Can we discuss tomorrow after the class? Can you all please meet together after the class outside of 2012 classroom? We can talk about the possibilities of the group formation and group project. Thanks

-Rashed

**Comment by eclaks** [comment]
Sure, that sounds good!

**Comment by emminic93** [comment]
Yeah!
