### ISSUE TITLE
Looking for STAT and BIOF students to form group

### ISSUE THREAD

**Issue by joeho604** [STAT540-UBC/Discussion#98]
Hi all,

We (Joe, Dan, and Kevin) are looking for Stat and/or Bioinformatics students to form a group. Kevin and Dan are GSAT students, and I am a microbiology student.  Dan and I are currently working in the Hallam lab (microbiology). We have datasets covering bacterial metagenomics, metatranscriptomics, and even metaproteomics across different environments (covering soil, ocean, hydrocarbon contaminated sites, etc). An example of a well-studied environment is the Sannich Inlet. Our lab studies the nutrient cycling in the Sannich Inlet along with the dynamic changes in microbial communities that exist seasonally. Therefore, our lab collects water sample and sequence the abundance and diversity of bacteria in these ecosystems every month. We have data generated over 5 years of time. 

That is only one example of an environment that we studied. There are many more...If you're interested, please write to this discussion!

-Joe

**Comment by samhinshaw** [comment]
Hey guys, I'd be interested in working on some microbiology meta-omics datasets.  I'm in Dr. Hancock's lab doing microbiology & immunology bioinformatics and have talked with Dr. Hallam before about his work.

**Comment by joeho604** [comment]
Hi @samhinshaw,

Let's meet up during the seminar today. See you there!

-Joe

**Comment by amaliar** [comment]
Amalia Rose
amaliarose@live.com

**Comment by joeho604** [comment]
Kevin Ao

**Comment by kao7** [comment]
Kevin - kevinao77@gmail.com
@joeho604
